In [1]:
import os, sys, importlib
import pandas as pd
import json
import networkx as nt
import matplotlib.pyplot as plt

## data

In [2]:
path_table="../results/table_clean.csv"
df_all=pd.read_csv(path_table)
display(df_all)

,title_theme,title_index,author,theme,cycle,collection,mss,ff,page
0,Heroica,Heroica,Flavius Philostratus,Classical Romances,Cycle of Troy,Royal,16. C. xxiii.,ff. 2-69 b,1
1,Iliaca,Iliaca,Joannes Tzetzes,Classical Romances,Cycle of Troy,Royal,16. C. iv. A. B.,NaN,2
2,Iliaca,Iliaca,Joannes Tzetzes,Classical Romances,Cycle of Troy,Royal,16. D. iii. A. B.,NaN,2
3,Iliaca,Iliaca,Joannes Tzetzes,Classical Romances,Cycle of Troy,Harley,Harley 5662.,ff. 1-56,2
4,Dictys Cretensis,Dictys Cretensis,NaN,Classical Romances,Cycle of Troy,Harley,Harley 3514,NaN,9
...,...,...,...,...,...,...,...,...,...
578,NaN,A Propecye,NaN,NaN,NaN,Additional,Add. 27879 f 239 b,NaN,327
579,NaN,Robin Hood's Garland,NaN,NaN,NaN,Additional,Add. 28638,NaN,520
580,NaN,Ballads of Scotland,NaN,NaN,NaN,Additional,"Add. 29408, 29409",NaN,537
581,NaN,Two Charlemagne Romances,NaN,NaN,NaN,Additional,Add. 31042,"ff66 b-79 b, 82-94",953
582,NaN,Ipomedon and Prothesilaus,NaN,NaN,NaN,Egerton,Egerton 2515,ff. 3-141,746

## vis1.1 : collection network (edge==sum coocurrences of titles)

In [30]:
df=df_all.copy()
df=df[df["collection"].notna()]
display(df.head())
print(len(df_all),'=>', len(df))

print(df[['title_index','collection']].value_counts(dropna=False),"\n")
print(df[['title_index','mss']].value_counts(dropna=False))

,title_theme,title_index,author,theme,cycle,collection,mss,ff,page
0,Heroica,Heroica,Flavius Philostratus,Classical Romances,Cycle of Troy,Royal,16. C. xxiii.,ff. 2-69 b,1
1,Iliaca,Iliaca,Joannes Tzetzes,Classical Romances,Cycle of Troy,Royal,16. C. iv. A. B.,NaN,2
2,Iliaca,Iliaca,Joannes Tzetzes,Classical Romances,Cycle of Troy,Royal,16. D. iii. A. B.,NaN,2
3,Iliaca,Iliaca,Joannes Tzetzes,Classical Romances,Cycle of Troy,Harley,Harley 5662.,ff. 1-56,2
4,Dictys Cretensis,Dictys Cretensis,NaN,Classical Romances,Cycle of Troy,Harley,Harley 3514,NaN,9

583 => 576
title_index                collection
Alexandreis                Additional    12
Turpin's Chronicle         Harley        12
                           Cotton        10
Alexander the Great        Royal          9
Historia Regum Britanniae  Cotton         9
                                         ..
Brut y Brenhinoedd         Cotton         1
Brutus                     Cotton         1
Cassandra                  Sloane         1
Chanson d'Aspremont        Lansdowne      1
Trójumanna saga            Additional     1
Name: count, Length: 327, dtype: int64

title_index          mss
Havelok              13. A. xxi.          4
Alexandreis          8. B. iv.            4
Turpin's Chronicle   Nero A. xi.          4
Alexandreis          Harley 4745          4
                     Burney 312           4
                                         ..
Aspremont            15. E. vi.           1
                     Add. 10,508.         1
Ballads of Scotland  Add. 29408, 29409    1
Battle of Roncevaux  Titus A. xix.        1
Alexander the Great  20. A. v.            1
Name: count, Length: 502, dtype: int64

In [31]:
'''
思路：
每个 collection 是节点
如果两个 collection 都包含同一个 title → edge
edge weight = 共享 title 在两边的出现次数之和（或者乘积）
edge label = title
'''

from itertools import combinations
from collections import defaultdict
import pandas as pd

# 按 collection × title_index 统计
coll_title_counts = df.groupby(['collection','title_index']).size().reset_index(name='count')
print(coll_title_counts)

# 初始化字典，key=(coll1, coll2)
edge_dict = defaultdict(lambda: {'weight':0, 'titles':[]})

# 按 title_index 分组
title_groups = coll_title_counts.groupby('title_index')

for title_index, group in title_groups:
    collections = list(group['collection'])
    counts = list(group['count'])
    
    if len(collections) > 1:
        for (i,j) in combinations(range(len(collections)),2):
            # key 按字母顺序保证唯一性
            key = tuple(sorted([collections[i], collections[j]]))
            edge_dict[key]['weight'] += counts[i] + counts[j]   # 累加权重
            edge_dict[key]['titles'].append(title_index)        # 累加共享 title

# 转成 DataFrame
edges = []
for (coll1, coll2), data in edge_dict.items():
    edges.append({
        'source': coll1,
        'target': coll2,
        'weight': data['weight'],
        'titles': data['titles']
    })

edge_df = pd.DataFrame(edges)
# display(edge_df)

# 可选：只保留 weight >= 2 的边
edge_df_filtered = edge_df[edge_df['weight'] >= 2]
display(edge_df_filtered)

     collection                 title_index  count
0    Additional                  A Propecye      1
1    Additional              Alexander saga      2
2    Additional                 Alexandreis     12
3    Additional            Amis and Amylion      1
4    Additional          Apollonius of Tyre      2
..          ...                         ...    ...
322      Sloane           Quatre fils Aimon      1
323      Sloane          Robyn and Gandelyn      1
324      Sloane           Sydrac and Boctus      1
325      Sloane             Tale of Gamelyn      2
326      Sloane  Whole Prophecy of Scotland      1

[327 rows x 3 columns]

,source,target,weight,titles
0,Arundel,Burney,2,[Alexander the Great]
1,Arundel,Cotton,48,"[Alexander the Great, Apollonius of Tyre, Hist..."
2,Arundel,Harley,46,"[Alexander the Great, Historia Regum Britannia..."
3,Arundel,Royal,45,"[Alexander the Great, Apollonius of Tyre, Hist..."
4,Arundel,Sloane,16,"[Alexander the Great, Apollonius of Tyre, Hist..."
5,Burney,Cotton,11,"[Alexander the Great, Dares Phrygius]"
6,Burney,Harley,22,"[Alexander the Great, Alexandreis, Dares Phryg..."
7,Burney,Royal,29,"[Alexander the Great, Alexandreis, Dares Phryg..."
8,Burney,Sloane,6,"[Alexander the Great, Dares Phrygius]"
9,Cotton,Harley,79,"[Alexander the Great, Dares Phrygius, Fall of ..."
10,Cotton,Royal,99,"[Alexander the Great, Apollonius of Tyre, Dare..."
11,Cotton,Sloane,29,"[Alexander the Great, Apollonius of Tyre, Dare..."
12,Harley,Royal,121,"[Alexander the Great, Alexandreis, Dares Phryg..."
13,Harley,Sloane,32,"[Alexander the Great, Dares Phrygius, Guy of W..."
14,Royal,Sloane,39,"[Alexander the Great, Apollonius of Tyre, Dare..."
15,Additional,Burney,23,"[Alexandreis, Dares Phrygius, Dictys Cretensis]"
16,Additional,Harley,124,"[Alexandreis, Dares Phrygius, Dictys Cretensis..."
17,Additional,Royal,109,"[Alexandreis, Apollonius of Tyre, Aspremont, D..."
18,Additional,Arundel,37,"[Apollonius of Tyre, Historia Regum Britanniae..."
19,Additional,Cotton,73,"[Apollonius of Tyre, Dares Phrygius, Guy of Wa..."
20,Additional,Sloane,17,"[Apollonius of Tyre, Dares Phrygius, Guy of Wa..."
21,Additional,Lansdowne,17,"[Guy of Warwick, Historia Regum Britanniae, Hi..."
22,Cotton,Lansdowne,14,"[Guy of Warwick, Historia Regum Britanniae, Th..."
23,Harley,Lansdowne,31,"[Guy of Warwick, Historia Regum Britanniae, Hi..."
24,Lansdowne,Royal,27,"[Guy of Warwick, Historia Regum Britanniae, Hi..."
25,Lansdowne,Sloane,9,"[Guy of Warwick, Historia Regum Britanniae, Sy..."
26,Arundel,Lansdowne,10,"[Historia Regum Britanniae, Historia Trojana]"
27,Cotton,Egerton,8,[Prophecy of the Tenth Sibyl]
28,Egerton,Royal,14,"[Prophecy of the Tenth Sibyl, Roman de la Rose..."
29,Additional,Egerton,9,"[Roman de la Rose, Tristram]"
30,Egerton,Harley,7,"[Roman de la Rose, Tristram]"

In [33]:
import numpy as np
# --------------NODE SIZE------------------
# 每个 collection 的文本数量
node_sizes_raw = df.groupby('collection')['title_index'].nunique()

# normalize 到 20~60 大小
min_size, max_size = 10, 30
node_sizes = ((node_sizes_raw - node_sizes_raw.min()) / (node_sizes_raw.max() - node_sizes_raw.min()) * (max_size - min_size) + min_size).to_dict()
print(node_sizes)

#-------------NODE COLOR--------------------
from matplotlib import cm, colors

collections = list(df['collection'].unique())

# viridis 颜色映射
cmap = cm.get_cmap('tab20', len(collections))
color_map = {coll: colors.to_hex(cmap(i)) for i, coll in enumerate(collections)}

# ------------network--------------------
from pyvis.network import Network

# notebook=True 在 jupyter 直接显示
net = Network(height='800px', width='100%', notebook=True)

for coll in collections:
    net.add_node(
        coll,
        label=coll,
        title=f"{coll}: {node_sizes_raw[coll]} texts",
        color=color_map[coll],
        size=node_sizes[coll],
        font={
            "size": 25,        # 字体大小
            "face": "arial",   # 字体类型
            "color": "black", # 颜色
        }
    )
    
max_titles_to_show=2

for _, row in edge_df_filtered.iterrows():    
    if len(row['titles'])<max_titles_to_show:
        hover_text= f"{', '.join(row['titles'])}({row['weight']})" 
    else :
        hover_text= f"{', '.join(row['titles'][:max_titles_to_show])}...({row['weight']})" 

    
    net.add_edge(
        row['source'],
        row['target'],
        value=row['weight']/5,
        title=hover_text,
        font={"size": 5, "align":"middle"},
        color="lightgray",
        
        physics=True
    )



# -------------LAYOUT--------------------
net.force_atlas_2based(
    gravity=-200,          # 整体节点拉开的力度，负值越大，节点分得越开
    central_gravity=0.05,  # 越小，节点越靠中心；越大，节点聚到中心
    spring_length=250,     # 弹簧长度，越大，节点间隔越远
    spring_strength=0.05,  # 弹簧刚度，控制边对节点靠近的作用力
    damping=0.4            # 收敛阻尼
)

#-------------------SHOW---------------------
# 生成 HTML
path_html='../figs/collection_network.html'
net.show(path_html)

## ----------------add title---------------

# 自动在 body 开始处插入标题
title_text = "Inter-Collection Network of Shared Manuscript Texts"
with open(path_html, 'r', encoding='utf-8') as f:
    html_content = f.read()

# 在 <body> 标签后插入标题
html_content = html_content.replace(
    '<body>',
    f'<body>\n<h2 style="text-align:center">{title_text}</h2>'
)
# 保存回 HTML 文件
with open(path_html, 'w', encoding='utf-8') as f:
    f.write(html_content)

{'Additional': 30.0, 'Arundel': 11.801801801801801, 'Burney': 10.18018018018018, 'Cotton': 18.28828828828829, 'Egerton': 10.0, 'Harley': 19.90990990990991, 'Lansdowne': 11.621621621621621, 'Royal': 18.82882882882883, 'Sloane': 11.801801801801801}
Warning: When  cdn_resources is 'local' jupyter notebook has issues displaying graphics on chrome/safari. Use cdn_resources='in_line' or cdn_resources='remote' if you have issues viewing graphics in a notebook.
../figs/collection_network.html

C:\Users\yeliu\AppData\Local\Temp\ipykernel_12060\1642905073.py:17: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = cm.get_cmap('tab20', len(collections))

## vis1.2 : mss network: connecté si partage le meme texte
QR : comment les collections se construisent? 

si le regroupement dépend de la similarité entre les mss (==représenté par le partage des mêmes textes) ?

on 1) associe les mss qui enregistre le meme texte 
2) colore les mss selon la collection


si oui, un cluster a une couleur dominante
si non, le cluster a plusieurs couleurs

==> la collection ne se fait pas selon le contenu.

In [34]:
from itertools import combinations
from collections import defaultdict
import pandas as pd

# 按 collection × title_index 统计
coll_title_counts = df.groupby(["collection",'mss','title_index']).size().reset_index(name='count')
print(coll_title_counts)

# 初始化字典，key=(coll1, coll2)
edge_dict = defaultdict(lambda: {'weight':0, 'titles':[]})

# 按 title_index 分组
title_groups = coll_title_counts.groupby('title_index')

for title_index, group in title_groups:
    collections = list(group['mss'])
    counts = list(group['count'])
    
    if len(collections) > 1:
        for (i,j) in combinations(range(len(collections)),2):
            # key 按字母顺序保证唯一性
            key = tuple(sorted([collections[i], collections[j]]))
            edge_dict[key]['weight'] += counts[i] + counts[j]   # 累加权重
            edge_dict[key]['titles'].append(title_index)        # 累加共享 title

# 转成 DataFrame
edges = []
for (coll1, coll2), data in edge_dict.items():
    edges.append({
        'source': coll1,
        'target': coll2,
        'weight': data['weight'],
        'titles': data['titles']
    })

edge_df = pd.DataFrame(edges)
# display(edge_df)  

# 可选：只保留 weight >= 2 的边
edge_df_filtered = edge_df[edge_df['weight'] >= 2]
display(edge_df_filtered)

     collection           mss                                title_index  \
0    Additional  Add. 10,038.                        Titus and Vespasian
1    Additional  Add. 10,094.                             Dares Phrygius
2    Additional  Add. 10,286.                          Sydrac and Boctus
3    Additional  Add. 10,289.                                     Juglet
4    Additional  Add. 10,289.                        Titus and Vespasian
..          ...           ...                                        ...
497      Sloane   Sloane 289.                  Historia Regum Britanniae
498      Sloane  Sloane 3991.  Letter of Dindimus to Alexander the Great
499      Sloane    Sloane 457                                  Cassandra
500      Sloane   Sloane 780.                         Life of Robin Hood
501      Sloane    Sloane 960                          Quatre fils Aimon

     count
0        3
1        1
2        1
3        1
4        3
..     ...
497      1
498      1
499      1
500      1
501      1

[502 rows x 4 columns]

            source              target  weight                        titles
0     Add. 11,238.        Add. 24,969.       2              [Alexander saga]
1     Arundel 123.         Burney 280.       2         [Alexander the Great]
2     Arundel 123.     Cleopatra D. v.       2         [Alexander the Great]
3     Arundel 123.        Galba E. xi.       2         [Alexander the Great]
4     Arundel 123.       Nero D. viii.       2         [Alexander the Great]
...            ...                 ...     ...                           ...
1642    Add. 30864         Arundel 230       4               [Voeux du Paon]
1643    Add. 30864         Harley 3992       4               [Voeux du Paon]
1644   Arundel 230         Harley 3992       4               [Voeux du Paon]
1645   Sloane 1802  Vespasian E. viii.       2  [Whole Prophecy of Scotland]
1646    Add. 4857.          Add. 4859.       3                 [Ívents saga]

[1647 rows x 4 columns]

In [26]:
coll_title_counts[coll_title_counts['title_index']=='Titus and Vespasian']

     collection                mss          title_index  count
0    Additional       Add. 10,038.  Titus and Vespasian      3
4    Additional       Add. 10,289.  Titus and Vespasian      3
118  Additional         Add. 31042  Titus and Vespasian      3
184      Cotton    Caligula A. ii.  Titus and Vespasian      3
259      Cotton  Vespasian E. xvi.  Titus and Vespasian      3
440       Royal       16. E. viii.  Titus and Vespasian      3

In [62]:
import numpy as np
# --------------NODE SIZE------------------
# 每个 collection 的文本数量
node_sizes_raw = df.groupby('mss')['title_index'].nunique()

# normalize 到 20~60 大小
min_size, max_size = 20, 60
node_sizes = ((node_sizes_raw - node_sizes_raw.min()) / (node_sizes_raw.max() - node_sizes_raw.min()) * (max_size - min_size) + min_size).to_dict()
print(node_sizes)

#-------------NODE COLOR--------------------
from matplotlib import cm, colors
mss_collection = df.drop_duplicates('mss').set_index('mss')['collection'].to_dict()
collections = df['collection'].unique()

cmap = cm.get_cmap('tab20', len(collections))
collection_colors = {
    coll: colors.to_hex(cmap(i))
    for i, coll in enumerate(collections)
}
# {'Royal': '#1f77b4',
#  'Harley': '#ff7f0e',
#  'Burney': '#98df8a',
#  'Additional': '#ff9896',
#  'Cotton': '#8c564b',
#  'Sloane': '#e377c2',
#  'Lansdowne': '#c7c7c7',
#  'Arundel': '#dbdb8d',
#  'Egerton': '#9edae5'}


# ------------network--------------------
from pyvis.network import Network
net = Network(height='800px', width='100%', notebook=True)


for mss in node_sizes_raw.index:
    coll = mss_collection[mss]
    net.add_node(
        mss,
        label=mss,
        title=f"{mss}({coll}): {node_sizes_raw[mss]} texts",
        color=collection_colors[coll],
        size=node_sizes[mss]
    )
    
    
max_titles_to_show=2

for _, row in edge_df_filtered.iterrows():    
    if len(row['titles'])<max_titles_to_show:
        hover_text= f"{', '.join(row['titles'])}({row['weight']})" 
    else :
        hover_text= f"{', '.join(row['titles'][:max_titles_to_show])}...({row['weight']})" 

    
    net.add_edge(
        row['source'],
        row['target'],
        value=row['weight']/5,
        title=hover_text,
        font={"size": 5, "align":"middle"},
        color="lightgray",
        physics=True
    )

# -------------LAYOUT--------------------
net.force_atlas_2based(
    gravity=-200,          # 整体节点拉开的力度，负值越大，节点分得越开
    central_gravity=0.05,  # 越小，节点越靠中心；越大，节点聚到中心
    spring_length=250,     # 弹簧长度，越大，节点间隔越远
    spring_strength=0.05,  # 弹簧刚度，控制边对节点靠近的作用力
    damping=0.4            # 收敛阻尼
)

#-------------------SHOW---------------------
# 生成 HTML
path_html='../figs/mss_network_by_collection.html'
net.show(path_html)

## ----------------add title---------------

# 自动在 body 开始处插入标题
title_text = "Inter-Manuscript Network of Shared Texts colored by collection"
with open(path_html, 'r', encoding='utf-8') as f:
    html_content = f.read()

# 在 <body> 标签后插入标题
html_content = html_content.replace(
    '<body>',
    f'<body>\n<h2 style="text-align:center">{title_text}</h2>'
)
# 保存回 HTML 文件
with open(path_html, 'w', encoding='utf-8') as f:
    f.write(html_content)

{'10. A. x.': 20.0, '12. C. iv.': 20.0, '12. C. xii.': 26.666666666666664, '12. C. xx.': 20.0, '12. D. iii.': 23.333333333333332, '13. A. i.': 20.0, '13. A. iii.': 23.333333333333332, '13. A. iv.': 20.0, '13. A. v.': 26.666666666666664, '13. A. xiv.': 20.0, '13. A. xviii.': 20.0, '13. A. xxi.': 23.333333333333332, '13. C. xii.': 23.333333333333332, '13. D. i.': 23.333333333333332, '13. D. ii.': 20.0, '13. D. v.': 20.0, '13. E. i.': 20.0, '13. E. ix.': 20.0, '14. C. i.': 20.0, '14. C. xi.': 20.0, '14. E. ii.': 23.333333333333332, '14. E. iii.': 23.333333333333332, '15. A. x.': 20.0, '15. A. xxii.': 23.333333333333332, '15. B. xi.': 23.333333333333332, '15. C. vi.': 20.0, '15. C. xvi.': 26.666666666666664, '15. E. v.': 20.0, '15. E. vi.': 46.666666666666664, '16. C. iv. A. B.': 20.0, '16. C. xxiii.': 20.0, '16. D. iii. A. B.': 20.0, '16. E.': 20.0, '16. E. viii.': 20.0, '16. F. ix.': 20.0, '16. F. v.': 20.0, '16. G. ii.': 20.0, '17. B. xliii.': 20.0, '17. D. xv.': 20.0, '17. E. ii.': 20.0, '18. B. ii.': 20.0, '18. C. ii.': 20.0, '18. D. ii.': 23.333333333333332, '18. D. vi.': 20.0, '19. A. xviii.': 20.0, '19. B. vii.': 20.0, '19. B. xii.': 20.0, '19. B. xiii.': 20.0, '19. C. vii.': 20.0, '19. C. viii.': 20.0, '19. D. i.': 23.333333333333332, '19. E. ii.': 20.0, '19. E. iii.': 20.0, '20. A. v.': 20.0, '20. A. xvii.': 20.0, '20. B. xix.': 23.333333333333332, '20. B. xx.': 20.0, '20. C. ii.': 23.333333333333332, '20. C. vi.': 20.0, '20. D. ii.': 20.0, '20. D. iii.': 20.0, '20. D. iv.': 20.0, '20. D. vii.': 20.0, '20. D. xi.': 20.0, '4. C. xi.': 23.333333333333332, '5. F. xv.': 20.0, '6. C. viii.': 20.0, '6. E. iii.': 20.0, '7. A. i.': 20.0, '8. B. iv.': 20.0, '8. D. iii.': 20.0, '8. F. ix.': 20.0, '9. B. ix.': 20.0, 'Add. 10,038.': 20.0, 'Add. 10,094.': 20.0, 'Add. 10,286.': 20.0, 'Add. 10,289.': 23.333333333333332, 'Add. 10,290.': 20.0, 'Add. 10,292.': 23.333333333333332, 'Add. 10,293': 20.0, 'Add. 10,294': 20.0, 'Add. 10,295': 20.0, 'Add. 10,296': 20.0, 'Add. 10,321': 20.0, 'Add. 10,508.': 23.333333333333332, 'Add. 11,110.': 20.0, 'Add. 11,113.': 20.0, 'Add. 11,141.': 20.0, 'Add. 11,153.': 20.0, 'Add. 11,157.': 23.333333333333332, 'Add. 11,158.': 20.0, 'Add. 11,163.': 20.0, 'Add. 11,164': 20.0, 'Add. 11,174.': 20.0, 'Add. 11,238.': 20.0, 'Add. 11,241.': 20.0, 'Add. 11,614': 20.0, 'Add. 11,702.': 20.0, 'Add. 12,042': 20.0, 'Add. 12,044': 20.0, 'Add. 12,196.': 20.0, 'Add. 12,213.': 23.333333333333332, 'Add. 12,228': 20.0, 'Add. 14,100': 20.0, 'Add. 14,408.': 20.0, 'Add. 14,682': 20.0, 'Add. 14,697.': 20.0, 'Add. 14,903.': 20.0, 'Add. 14,907.': 20.0, 'Add. 15,002.': 20.0, 'Add. 15,003.': 20.0, 'Add. 15,035.': 20.0, 'Add. 15,042': 20.0, 'Add. 15,210-15,213': 20.0, 'Add. 15,212.': 23.333333333333332, 'Add. 15,213': 20.0, 'Add. 15,429': 20.0, 'Add. 15,477': 20.0, 'Add. 15,566.': 20.0, 'Add. 15,606.': 20.0, 'Add. 15,732': 20.0, 'Add. 16,169.': 20.0, 'Add. 16,441': 20.0, 'Add. 16,563': 20.0, 'Add. 16,888': 20.0, 'Add. 16,955': 20.0, 'Add. 16,956': 20.0, 'Add. 17,084': 20.0, 'Add. 17,443': 20.0, 'Add. 17,914': 20.0, 'Add. 17,920.': 20.0, 'Add. 18,217': 20.0, 'Add. 18,632.': 20.0, 'Add. 18,688': 20.0, 'Add. 18,922.': 20.0, 'Add. 19,513.': 20.0, 'Add. 19,554.': 23.333333333333332, 'Add. 19,709.': 23.333333333333332, 'Add. 20,094.': 20.0, 'Add. 21,218': 20.0, 'Add. 21,246': 20.0, 'Add. 22,155': 20.0, 'Add. 22,283.': 23.333333333333332, 'Add. 22,311': 20.0, 'Add. 22,312': 20.0, 'Add. 22,821': 20.0, 'Add. 23,829': 20.0, 'Add. 23,930.': 20.0, 'Add. 24,946': 20.0, 'Add. 24,969.': 23.333333333333332, 'Add. 24,970': 20.0, 'Add. 24,972.': 20.0, 'Add. 24,973.': 20.0, 'Add. 25,014.': 20.0, 'Add. 25,434': 20.0, 'Add. 25,569.': 20.0, 'Add. 27,979': 20.0, 'Add. 27879': 60.0, 'Add. 27879 f 239 b': 20.0, 'Add. 27879 f 248': 20.0, 'Add. 27879.': 23.333333333333332, 'Add. 28638': 20.0, 'Add. 29408, 29409': 20.0, 'Add. 30863': 20.0, 'Add. 30864': 20.0, 'Add. 30984': 20.0, 'Add. 31,840': 20.0, 'Add. 31042': 26.666666666666664, 'Add. 4857.': 26.666666666666664, 'Add. 4859.': 36.66666666666667, 'Add. 4860.': 26.666666666666664, 'Add. 4863.': 23.333333333333332, 'Add. 4864.': 20.0, 'Add. 4869.': 26.666666666666664, 'Add. 4870.': 20.0, 'Add. 4874.': 23.333333333333332, 'Add. 4875.': 20.0, 'Add. 4884.': 20.0, 'Add. 5474': 20.0, 'Add. 6121.': 20.0, 'Add. 6796': 20.0, 'Add. 6924.': 23.333333333333332, 'Add. 9785': 20.0, 'Arundel 10': 20.0, 'Arundel 119': 20.0, 'Arundel 123.': 23.333333333333332, 'Arundel 138.': 20.0, 'Arundel 174': 20.0, 'Arundel 220.': 20.0, 'Arundel 220. Art. L': 20.0, 'Arundel 230': 20.0, 'Arundel 237': 20.0, 'Arundel 242.': 20.0, 'Arundel 292.': 20.0, 'Arundel 319.': 20.0, 'Arundel 326.': 20.0, 'Arundel 403': 20.0, 'Arundel 409.': 20.0, 'Arundel 546.': 20.0, 'Arundel 57.': 20.0, 'Arundel 6': 20.0, 'Arundel 66.': 20.0, 'Arundel 99': 20.0, 'Augustus A. iv.': 20.0, 'Burney 170': 20.0, 'Burney 186.': 20.0, 'Burney 216.': 20.0, 'Burney 280.': 23.333333333333332, 'Burney 312': 20.0, 'Caligula A. ii.': 43.333333333333336, 'Caligula A. ix.': 20.0, 'Caligula A. x.': 20.0, 'Caligula B. vii.': 33.33333333333333, 'Claudius E. viii.': 20.0, 'Cleopatra A. viii.': 20.0, 'Cleopatra B. v.': 23.333333333333332, 'Cleopatra C. iv.': 23.333333333333332, 'Cleopatra D. iii.': 20.0, 'Cleopatra D. ix.': 20.0, 'Cleopatra D. v.': 20.0, 'Cleopatra D. viii.': 23.333333333333332, 'Cotton Appendix iv.': 20.0, 'Cotton Appendix xxvii.': 20.0, 'Cotton Roll ii. 23': 20.0, 'Domitian xiii.': 20.0, 'Egerton 1069': 20.0, 'Egerton 2022': 20.0, 'Egerton 2515': 20.0, 'Egerton 810': 20.0, 'Egerton 881': 20.0, 'Egerton 989': 20.0, 'Faustina A. viii.': 20.0, 'Faustina B. ix.': 20.0, 'Faustina B. vi.': 20.0, 'Galba E. ix.': 23.333333333333332, 'Galba E. xi.': 26.666666666666664, 'Harley 1008.': 20.0, 'Harley 108.': 20.0, 'Harley 1121.': 20.0, 'Harley 1239.': 20.0, 'Harley 1321': 20.0, 'Harley 1605. Art. I.': 20.0, 'Harley 1629': 20.0, 'Harley 1701.': 20.0, 'Harley 1717.': 20.0, 'Harley 1758.': 20.0, 'Harley 176': 20.0, 'Harley 1883.': 20.0, 'Harley 225.': 20.0, 'Harley 2252.': 23.333333333333332, 'Harley 2253.': 26.666666666666664, 'Harley 2280': 20.0, 'Harley 2361.': 20.0, 'Harley 2386.': 23.333333333333332, 'Harley 2392': 20.0, 'Harley 2488.': 20.0, 'Harley 2492.': 20.0, 'Harley 2500.': 20.0, 'Harley 2678.': 20.0, 'Harley 2682.': 20.0, 'Harley 273.': 20.0, 'Harley 3043.': 20.0, 'Harley 3202.': 20.0, 'Harley 326.': 20.0, 'Harley 3314': 20.0, 'Harley 3514': 20.0, 'Harley 3573': 20.0, 'Harley 3581': 20.0, 'Harley 3637': 20.0, 'Harley 3681': 20.0, 'Harley 3773.': 20.0, 'Harley 3775.': 20.0, 'Harley 3776.': 20.0, 'Harley 3810. Part I.': 20.0, 'Harley 3830.': 20.0, 'Harley 3943': 20.0, 'Harley 3983.': 20.0, 'Harley 3992': 20.0, 'Harley 4003.': 20.0, 'Harley 4123.': 23.333333333333332, 'Harley 4294.': 20.0, 'Harley 4333.': 20.0, 'Harley 4334': 20.0, 'Harley 4361': 20.0, 'Harley 4387': 20.0, 'Harley 4389': 20.0, 'Harley 4404.': 23.333333333333332, 'Harley 4417.': 20.0, 'Harley 4418': 20.0, 'Harley 4419': 20.0, 'Harley 4425': 20.0, 'Harley 4482': 20.0, 'Harley 4486.': 20.0, 'Harley 4487.': 20.0, 'Harley 4690.': 20.0, 'Harley 4745': 20.0, 'Harley 49': 20.0, 'Harley 4912': 20.0, 'Harley 4979': 20.0, 'Harley 5054.': 20.0, 'Harley 51.': 20.0, 'Harley 5115.': 20.0, 'Harley 5243': 20.0, 'Harley 525.': 23.333333333333332, 'Harley 527.': 26.666666666666664, 'Harley 536.': 20.0, 'Harley 5427': 20.0, 'Harley 5437': 20.0, 'Harley 559.': 20.0, 'Harley 5662.': 20.0, 'Harley 6148.': 20.0, 'Harley 6223. Art. I.': 20.0, 'Harley 6340': 20.0, 'Harley 6341': 20.0, 'Harley 6358.': 23.333333333333332, 'Harley 641.': 20.0, 'Harley 6508': 20.0, 'Harley 655.': 20.0, 'Harley 6758': 20.0, 'Harley 7333.': 20.0, 'Harley 7334.': 20.0, 'Harley 746.': 20.0, 'Harley 838.': 20.0, 'Harley 941.': 20.0, 'Harley 978.': 20.0, 'Julius A. v.': 20.0, 'Julius D. xi.': 20.0, 'Julius E. viii.': 20.0, 'Lansdowne 214.': 20.0, 'Lansdowne 229.': 20.0, 'Lansdowne 362.': 20.0, 'Lansdowne 380.': 20.0, 'Lansdowne 388.': 20.0, 'Lansdowne 699.': 20.0, 'Lansdowne 732.': 20.0, 'Lansdowne 757': 20.0, 'Lansdowne 762.': 20.0, 'Lansdowne 766.': 20.0, 'Lansdowne 782': 20.0, 'Lansdowne 793': 20.0, 'Lansdowne 851.': 20.0, 'Nero A. iv.': 20.0, 'Nero A. x.': 20.0, 'Nero A. xi.': 20.0, 'Nero D. ix.': 23.333333333333332, 'Nero D. viii.': 26.666666666666664, 'Otho C. xiii.': 20.0, 'Sloane 1044.': 20.0, 'Sloane 1619': 23.333333333333332, 'Sloane 1619.': 20.0, 'Sloane 1685.': 20.0, 'Sloane 1686.': 20.0, 'Sloane 1785.': 20.0, 'Sloane 1802': 20.0, 'Sloane 2232': 20.0, 'Sloane 2233': 20.0, 'Sloane 2578': 20.0, 'Sloane 2593.': 20.0, 'Sloane 289.': 20.0, 'Sloane 3991.': 20.0, 'Sloane 457': 20.0, 'Sloane 780.': 20.0, 'Sloane 960': 20.0, 'Tiberius A. ix.': 20.0, 'Titus A. xix.': 30.0, 'Titus A. xviii.': 20.0, 'Titus A. xx.': 20.0, 'Titus A. xxv.': 20.0, 'Titus A. xxvii.': 20.0, 'Titus C. xvii.': 20.0, 'Titus D. iii.': 23.333333333333332, 'Titus D. vii.': 20.0, 'Titus D. xix.': 20.0, 'Vespasian A. vii.': 20.0, 'Vespasian A. x.': 20.0, 'Vespasian A. xiii.': 23.333333333333332, 'Vespasian A. xxiii.': 20.0, 'Vespasian B. xiv.': 23.333333333333332, 'Vespasian B. xxiii. Part III.': 20.0, 'Vespasian B. xxv.': 23.333333333333332, 'Vespasian D. ix.': 20.0, 'Vespasian D. xviii.': 20.0, 'Vespasian E. iv.': 23.333333333333332, 'Vespasian E. vii.': 20.0, 'Vespasian E. viii.': 20.0, 'Vespasian E. x.': 23.333333333333332, 'Vespasian E. xvi.': 20.0, 'Vitellius A. x.': 20.0, 'Vitellius A. xiii.': 20.0, 'Vitellius A. xv.': 20.0, 'Vitellius C. viii.': 20.0, 'Vitellius D. iii.': 20.0, 'Vitellius E. x.': 20.0}
Warning: When  cdn_resources is 'local' jupyter notebook has issues displaying graphics on chrome/safari. Use cdn_resources='in_line' or cdn_resources='remote' if you have issues viewing graphics in a notebook.

C:\Users\yeliu\AppData\Local\Temp\ipykernel_12060\985019461.py:16: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = cm.get_cmap('tab20', len(collections))

../figs/mss_network_by_collection.html

## vis1.3 xxx mss belongs to several themes

In [28]:
from itertools import combinations
from collections import defaultdict
import pandas as pd

# 按 collection × title_index 统计
coll_title_counts = df.groupby(["theme",'mss','title_index']).size().reset_index(name='count')
display(coll_title_counts.head())

# 初始化字典，key=(coll1, coll2)
edge_dict = defaultdict(lambda: {'weight':0, 'titles':[]})

# 按 title_index 分组
title_groups = coll_title_counts.groupby('title_index')

for title_index, group in title_groups:
    collections = list(group['mss'])
    counts = list(group['count'])
    
    if len(collections) > 1:
        for (i,j) in combinations(range(len(collections)),2):
            # key 按字母顺序保证唯一性
            key = tuple(sorted([collections[i], collections[j]]))
            edge_dict[key]['weight'] += counts[i] + counts[j]   # 累加权重
            edge_dict[key]['titles'].append(title_index)        # 累加共享 title

# 转成 DataFrame
edges = []
for (coll1, coll2), data in edge_dict.items():
    edges.append({
        'source': coll1,
        'target': coll2,
        'weight': data['weight'],
        'titles': data['titles']
    })

edge_df = pd.DataFrame(edges)
# display(edge_df)

# 可选：只保留 weight >= 2 的边
edge_df_filtered = edge_df[edge_df['weight'] >= 2]
display(edge_df_filtered)

,theme,mss,title_index,count
0,Allegorical and Didactic Romance,14. E. ii.,Le Chemin de Vaillance,1
1,Allegorical and Didactic Romance,14. E. ii.,Livre de l'Ordre de Chevalerie,1
2,Allegorical and Didactic Romance,16. F. v.,Sydrac and Boctus,1
3,Allegorical and Didactic Romance,19. A. xviii.,Roman de la Rose,1
4,Allegorical and Didactic Romance,19. B. xii.,Roman de la Rose,1

,source,target,weight,titles
0,"Add. 11,238.","Add. 24,969.",2,[Alexander saga]
1,15. A. x.,8. B. iv.,8,[Alexandreis]
2,15. A. x.,"Add. 17,084",8,[Alexandreis]
3,15. A. x.,"Add. 18,217",8,[Alexandreis]
4,15. A. x.,"Add. 22,821",8,[Alexandreis]
...,...,...,...,...
928,Add. 30864,Harley 3992,8,"[Voeux du Paon, Voeux du Paon, Voeux du Paon, ..."
929,Add. 30864,Add. 30864,2,[Voeux du Paon]
930,Arundel 230,Harley 3992,8,"[Voeux du Paon, Voeux du Paon, Voeux du Paon, ..."
931,Arundel 230,Arundel 230,2,[Voeux du Paon]
932,Harley 3992,Harley 3992,2,[Voeux du Paon]

In [30]:
mss_theme

{'16. C. xxiii.': 'Classical Romances',
 '16. C. iv. A. B.': 'Classical Romances',
 '16. D. iii. A. B.': 'Classical Romances',
 'Harley 5662.': 'Classical Romances',
 'Harley 3514': 'Classical Romances',
 'Burney 170': 'Classical Romances',
 'Add. 15,429': 'Classical Romances',
 '6. C. viii.': 'Classical Romances',
 '10. A. x.': 'Classical Romances',
 '13. A. v.': 'Classical Romances',
 '15. A. xxii.': 'Classical Romances',
 '15. B. xi.': 'Classical Romances',
 'Caligula B. vii.': 'Classical Romances',
 'Vitellius A. xiii.': 'Classical Romances',
 'Vitellius C. viii.': 'Classical Romances',
 'Vespasian B. xxv.': 'Classical Romances',
 'Cleopatra B. v.': 'Classical Romances',
 'Harley 641.': 'Classical Romances',
 'Burney 216.': 'Classical Romances',
 'Burney 280.': 'Classical Romances',
 'Sloane 1619': 'Classical Romances',
 'Add. 10,094.': 'Classical Romances',
 'Add. 15,042': 'Classical Romances',
 'Add. 19,709.': 'Classical Romances',
 'Harley 4482': 'Classical Romances',
 'Add. 30863': 'Classical Romances',
 '12. D. iii.': 'Classical Romances',
 '13. C. xii.': 'Classical Romances',
 '15. C. xvi.': 'Classical Romances',
 '16. F. ix.': 'Classical Romances',
 'Harley 51.': 'Classical Romances',
 'Harley 176': 'Classical Romances',
 'Harley 3637': 'Classical Romances',
 'Harley 3681': 'Classical Romances',
 'Harley 4123.': 'Classical Romances',
 'Harley 4387': 'Classical Romances',
 'Lansdowne 229.': 'Classical Romances',
 'Arundel 6': 'Classical Romances',
 'Arundel 174': 'Classical Romances',
 'Add. 9785': 'Classical Romances',
 'Add. 15,477': 'Classical Romances',
 'Add. 22,155': 'Classical Romances',
 'Add. 4869.': 'Classical Romances',
 'Add. 11,113.': 'Classical Romances',
 'Burney 186.': 'Classical Romances',
 'Add. 21,246': 'Classical Romances',
 'Harley 1239.': 'Classical Romances',
 'Harley 2280': 'Classical Romances',
 'Harley 2392': 'Classical Romances',
 'Harley 3943': 'Classical Romances',
 'Harley 4912': 'Classical Romances',
 'Add. 12,044': 'Classical Romances',
 '18. D. ii.': 'Classical Romances',
 '18. D. vi.': 'Classical Romances',
 'Augustus A. iv.': 'Classical Romances',
 'Arundel 99': 'Classical Romances',
 'Add. 14,100': 'Classical Romances',
 'Harley 525.': 'Classical Romances',
 'Cotton Appendix xxvii.': 'Classical Romances',
 'Arundel 119': 'Classical Romances',
 'Add. 18,632.': 'Classical Romances',
 'Add. 10,290.': 'Classical Romances',
 '8. B. iv.': 'Classical Romances',
 '15. A. x.': 'Classical Romances',
 'Harley 4745': 'Classical Romances',
 'Harley 5437': 'Classical Romances',
 'Burney 312': 'Classical Romances',
 'Add. 17,084': 'Classical Romances',
 'Add. 18,217': 'Classical Romances',
 'Add. 22,821': 'Classical Romances',
 'Add. 11,238.': 'Classical Romances',
 'Add. 24,969.': 'Classical Romances',
 'Vitellius A. xv.': 'Classical Romances',
 'Arundel 242.': 'Classical Romances',
 'Arundel 546.': 'Classical Romances',
 'Galba E. xi.': 'Classical Romances',
 '19. D. i.': 'Classical Romances',
 'Harley 3992': 'Classical Romances',
 'Arundel 230': 'Classical Romances',
 'Add. 16,956': 'Classical Romances',
 'Add. 30864': 'Classical Romances',
 'Harley 3983.': 'Classical Romances',
 'Harley 4487.': 'Classical Romances',
 '14. C. xi.': 'Classical Romances',
 '20. C. ii.': 'Classical Romances',
 'Vespasian A. xiii.': 'Classical Romances',
 'Titus D. iii.': 'Classical Romances',
 'Arundel 123.': 'Classical Romances',
 'Arundel 292.': 'Classical Romances',
 'Sloane 2233': 'Classical Romances',
 'Add. 4857.': 'Classical Romances',
 'Add. 4864.': 'Classical Romances',
 'Harley 3810. Part I.': 'Classical Romances',
 'Add. 16,441': 'Classical Romances',
 '16. E. viii.': 'Classical Romances',
 'Caligula A. ii.': 'Classical Romances',
 'Vespasian E. xvi.': 'Classical Romances',
 'Add. 10,038.': 'Classical Romances',
 'Add. 10,289.': 'Classical Romances',
 'Add. 31042': 'Classical Romances',
 '13. A. xiv.': 'Classical Romances',
 'Caligula A. x.': 'Classical Romances',
 'Vespasian E. iv.': 'Classical Romances',
 'Domitian xiii.': 'Classical Romances',
 'Egerton 810': 'Classical Romances',
 'Add. 4859.': 'Classical Romances',
 'Add. 11,141.': 'Classical Romances',
 'Nero D. viii.': 'British and English Traditions',
 'Vespasian E. x.': 'British and English Traditions',
 'Titus A. xix.': 'British and English Traditions',
 'Cleopatra D. viii.': 'British and English Traditions',
 'Cleopatra D. ix.': 'British and English Traditions',
 'Harley 941.': 'British and English Traditions',
 'Harley 2386.': 'British and English Traditions',
 '14. C. i.': 'British and English Traditions',
 '13. A. xxi.': 'British and English Traditions',
 'Vitellius A. x.': 'British and English Traditions',
 'Harley 6508': 'British and English Traditions',
 'Caligula A. ix.': 'British and English Traditions',
 'Harley 1605. Art. I.': 'British and English Traditions',
 'Julius D. xi.': 'British and English Traditions',
 'Vespasian A. x.': 'British and English Traditions',
 '13. E. i.': 'British and English Traditions',
 'Julius E. viii.': 'British and English Traditions',
 'Harley 655.': 'British and English Traditions',
 'Harley 1717.': 'British and English Traditions',
 'Vitellius E. x.': 'British and English Traditions',
 'Lansdowne 762.': 'British and English Traditions',
 'Add. 27879 f 248': 'British and English Traditions',
 '14. E. iii.': 'British and English Traditions',
 '19. C. vii.': 'British and English Traditions',
 'Add. 10,292.': 'British and English Traditions',
 'Harley 6223. Art. I.': 'British and English Traditions',
 'Harley 6340': 'British and English Traditions',
 'Add. 27879': 'British and English Traditions',
 '19. B. vii.': 'British and English Traditions',
 '19. C. viii.': 'British and English Traditions',
 '20. B. xix.': 'British and English Traditions',
 '20. C. vi.': 'British and English Traditions',
 '20. D. iii.': 'British and English Traditions',
 '20. D. iv.': 'British and English Traditions',
 'Harley 4419': 'British and English Traditions',
 'Harley 6341': 'British and English Traditions',
 'Lansdowne 757': 'British and English Traditions',
 'Add. 10,293': 'British and English Traditions',
 'Add. 10,294': 'British and English Traditions',
 'Add. 17,443': 'British and English Traditions',
 '20. D. ii.': 'British and English Traditions',
 'Harley 49': 'British and English Traditions',
 'Harley 4389': 'British and English Traditions',
 'Add. 5474': 'British and English Traditions',
 'Add. 23,829': 'British and English Traditions',
 'Egerton 989': 'British and English Traditions',
 'Add. 12,228': 'British and English Traditions',
 'Add. 23,930.': 'British and English Traditions',
 'Harley 1629': 'British and English Traditions',
 'Add. 25,434': 'British and English Traditions',
 'Faustina B. vi.': 'British and English Traditions',
 '15. E. v.': 'British and English Traditions',
 '19. E. ii.': 'British and English Traditions',
 '19. E. iii.': 'British and English Traditions',
 'Add. 10,295': 'British and English Traditions',
 'Arundel 220. Art. L': 'British and English Traditions',
 'Nero A. x.': 'British and English Traditions',
 'Add. 19,554.': 'British and English Traditions',
 'Galba E. ix.': 'British and English Traditions',
 'Add. 14,907.': 'British and English Traditions',
 'Add. 11,157.': 'British and English Traditions',
 'Harley 2252.': 'British and English Traditions',
 'Add. 4863.': 'British and English Traditions',
 'Harley 978.': 'British and English Traditions',
 '17. B. xliii.': 'British and English Traditions',
 'Add. 14,697.': 'British and English Traditions',
 'Add. 15,002.': 'British and English Traditions',
 'Harley 527.': 'British and English Traditions',
 'Harley 2253.': 'British and English Traditions',
 '15. E. vi.': 'British and English Traditions',
 '8. F. ix.': 'British and English Traditions',
 'Vespasian D. ix.': 'British and English Traditions',
 'Harley 3775.': 'British and English Traditions',
 'Harley 5243': 'British and English Traditions',
 'Harley 7333.': 'British and English Traditions',
 'Lansdowne 699.': 'British and English Traditions',
 'Sloane 1044.': 'British and English Traditions',
 'Add. 14,408.': 'British and English Traditions',
 '12. C. xii.': 'British and English Traditions',
 '17. D. xv.': 'British and English Traditions',
 '18. C. ii.': 'British and English Traditions',
 'Harley 1758.': 'British and English Traditions',
 'Harley 7334.': 'British and English Traditions',
 'Lansdowne 851.': 'British and English Traditions',
 'Sloane 1685.': 'British and English Traditions',
 'Sloane 1686.': 'British and English Traditions',
 'Sloane 2593.': 'British and English Traditions',
 'Add. 22,311': 'British and English Traditions',
 '4. C. xi.': 'French Traditions',
 '13. D. i.': 'French Traditions',
 'Nero A. xi.': 'French Traditions',
 'Harley 108.': 'French Traditions',
 'Harley 273.': 'French Traditions',
 'Harley 2361.': 'French Traditions',
 'Harley 2500.': 'French Traditions',
 'Harley 3043.': 'French Traditions',
 'Harley 6358.': 'French Traditions',
 'Arundel 220.': 'French Traditions',
 'Add. 6924.': 'French Traditions',
 'Add. 12,213.': 'French Traditions',
 'Add. 17,920.': 'French Traditions',
 'Add. 19,513.': 'French Traditions',
 '13. A. xviii.': 'French Traditions',
 'Add. 21,218': 'French Traditions',
 'Add. 10,508.': 'French Traditions',
 'Harley 4404.': 'French Traditions',
 '16. G. ii.': 'French Traditions',
 'Sloane 960': 'French Traditions',
 '20. D. xi.': 'French Traditions',
 'Harley 1321': 'French Traditions',
 'Harley 4334': 'French Traditions',
 'Add. 22,312': 'French Traditions',
 'Add. 10,321': 'French Traditions',
 'Add. 4860.': 'French Traditions',
 'Add. 4874.': 'French Traditions',
 '18. B. ii.': 'French Traditions',
 'Harley 4418': 'French Traditions',
 'Add. 6796': 'French Traditions',
 'Add. 15,212.': 'French Traditions',
 'Lansdowne 362.': 'Miscellaneous Romance',
 'Add. 25,569.': 'Miscellaneous Romance',
 'Add. 15,213': 'Miscellaneous Romance',
 'Harley 3314': 'Miscellaneous Romance',
 'Add. 14,682': 'Miscellaneous Romance',
 'Add. 15,606.': 'Miscellaneous Romance',
 'Harley 1701.': 'Miscellaneous Romance',
 'Add. 22,283.': 'Miscellaneous Romance',
 'Add. 18,688': 'Miscellaneous Romance',
 'Add. 16,955': 'Miscellaneous Romance',
 'Nero D. ix.': 'Miscellaneous Romance',
 'Add. 11,614': 'Miscellaneous Romance',
 'Harley 326.': 'Miscellaneous Romance',
 'Add. 12,196.': 'Miscellaneous Romance',
 'Lansdowne 766.': 'Miscellaneous Romance',
 'Harley 3573': 'Miscellaneous Romance',
 'Harley 5427': 'Miscellaneous Romance',
 'Harley 3581': 'Miscellaneous Romance',
 'Harley 6758': 'Miscellaneous Romance',
 'Harley 2678.': 'Miscellaneous Romance',
 'Harley 3830.': 'Miscellaneous Romance',
 '12. C. xx.': 'Miscellaneous Romance',
 'Harley 1883.': 'Miscellaneous Romance',
 'Harley 2492.': 'Miscellaneous Romance',
 'Sloane 457': 'Miscellaneous Romance',
 'Add. 15,210-15,213': 'Miscellaneous Romance',
 'Add. 27,979': 'Miscellaneous Romance',
 'Add. 24,946': 'Miscellaneous Romance',
 'Add. 11,241.': 'Miscellaneous Romance',
 'Add. 24,973.': 'Miscellaneous Romance',
 '19. A. xviii.': 'Allegorical and Didactic Romance',
 '19. B. xii.': 'Allegorical and Didactic Romance',
 '19. B. xiii.': 'Allegorical and Didactic Romance',
 '20. A. xvii.': 'Allegorical and Didactic Romance',
 '20. D. vii.': 'Allegorical and Didactic Romance',
 'Harley 4425': 'Allegorical and Didactic Romance',
 'Add. 12,042': 'Allegorical and Didactic Romance',
 'Add. 16,169.': 'Allegorical and Didactic Romance',
 'Add. 31,840': 'Allegorical and Didactic Romance',
 'Egerton 881': 'Allegorical and Didactic Romance',
 'Egerton 1069': 'Allegorical and Didactic Romance',
 'Egerton 2022': 'Allegorical and Didactic Romance',
 '14. E. ii.': 'Allegorical and Didactic Romance',
 '16. F. v.': 'Allegorical and Didactic Romance',
 'Harley 1121.': 'Allegorical and Didactic Romance',
 'Harley 4294.': 'Allegorical and Didactic Romance',
 'Harley 4361': 'Allegorical and Didactic Romance',
 'Harley 4417.': 'Allegorical and Didactic Romance',
 'Harley 4486.': 'Allegorical and Didactic Romance',
 'Lansdowne 793': 'Allegorical and Didactic Romance',
 'Sloane 2232': 'Allegorical and Didactic Romance',
 'Add. 10,286.': 'Allegorical and Didactic Romance',
 'Add. 16,563': 'Allegorical and Didactic Romance',
 'Add. 17,914': 'Allegorical and Didactic Romance',
 'Add. 30984': 'Appendix',
 'Harley 3776.': 'Appendix'}

In [29]:
import numpy as np
# --------------NODE SIZE------------------
# 每个 collection 的文本数量
node_sizes_raw = df.groupby('mss')['title_index'].nunique()

# normalize 到 20~60 大小
min_size, max_size = 20, 60
node_sizes = ((node_sizes_raw - node_sizes_raw.min()) / (node_sizes_raw.max() - node_sizes_raw.min()) * (max_size - min_size) + min_size).to_dict()
print(node_sizes)

#-------------NODE COLOR--------------------
from matplotlib import cm, colors
mss_theme = df.drop_duplicates('mss').set_index('mss')['theme'].to_dict()
themes = df['theme'].unique()

cmap = cm.get_cmap('tab20', len(themes))
theme_colors = {
    coll: colors.to_hex(cmap(i))
    for i, coll in enumerate(themes)
}
print(theme_colors)

# ------------network--------------------
from pyvis.network import Network
net = Network(height='800px', width='100%', notebook=True)


for mss in node_sizes_raw.index:
    theme = mss_theme[mss]
    net.add_node(
        mss,
        label=mss,
        title=f"{mss}({theme}) : {node_sizes_raw[mss]} texts",
        color=theme_colors[theme],
        size=node_sizes[mss]
    )
    
    
max_titles_to_show=2

for _, row in edge_df_filtered.iterrows():    
    if len(row['titles'])<max_titles_to_show:
        hover_text= f"{', '.join(row['titles'])}({row['weight']})" 
    else :
        hover_text= f"{', '.join(row['titles'][:max_titles_to_show])}...({row['weight']})" 

    
    net.add_edge(
        row['source'],
        row['target'],
        value=row['weight']/5,
        title=hover_text,
        font={"size": 5, "align":"middle"},
        color="lightgray",
        physics=True
    )

# -------------LAYOUT--------------------
net.force_atlas_2based(
    gravity=-200,          # 整体节点拉开的力度，负值越大，节点分得越开
    central_gravity=0.05,  # 越小，节点越靠中心；越大，节点聚到中心
    spring_length=250,     # 弹簧长度，越大，节点间隔越远
    spring_strength=0.05,  # 弹簧刚度，控制边对节点靠近的作用力
    damping=0.4            # 收敛阻尼
)

#-------------------SHOW---------------------
# 生成 HTML
path_html='../figs/mss_network_theme.html'
net.show(path_html)

## ----------------add title---------------

# 自动在 body 开始处插入标题
title_text = "Inter-Manuscript Network of Shared Texts colored by theme"
with open(path_html, 'r', encoding='utf-8') as f:
    html_content = f.read()

# 在 <body> 标签后插入标题
html_content = html_content.replace(
    '<body>',
    f'<body>\n<h2 style="text-align:center">{title_text}</h2>'
)
# 保存回 HTML 文件
with open(path_html, 'w', encoding='utf-8') as f:
    f.write(html_content)

{'10. A. x.': 20.0, '12. C. xii.': 20.0, '12. C. xx.': 20.0, '12. D. iii.': 20.0, '13. A. v.': 20.0, '13. A. xiv.': 20.0, '13. A. xviii.': 20.0, '13. A. xxi.': 28.0, '13. C. xii.': 20.0, '13. D. i.': 20.0, '13. E. i.': 20.0, '14. C. i.': 20.0, '14. C. xi.': 20.0, '14. E. ii.': 28.0, '14. E. iii.': 28.0, '15. A. x.': 20.0, '15. A. xxii.': 28.0, '15. B. xi.': 28.0, '15. C. xvi.': 28.0, '15. E. v.': 20.0, '15. E. vi.': 60.0, '16. C. iv. A. B.': 20.0, '16. C. xxiii.': 20.0, '16. D. iii. A. B.': 20.0, '16. E. viii.': 20.0, '16. F. ix.': 20.0, '16. F. v.': 20.0, '16. G. ii.': 20.0, '17. B. xliii.': 20.0, '17. D. xv.': 20.0, '18. B. ii.': 20.0, '18. C. ii.': 20.0, '18. D. ii.': 28.0, '18. D. vi.': 20.0, '19. A. xviii.': 20.0, '19. B. vii.': 20.0, '19. B. xii.': 20.0, '19. B. xiii.': 20.0, '19. C. vii.': 20.0, '19. C. viii.': 20.0, '19. D. i.': 20.0, '19. E. ii.': 20.0, '19. E. iii.': 20.0, '20. A. xvii.': 20.0, '20. B. xix.': 28.0, '20. C. ii.': 28.0, '20. C. vi.': 20.0, '20. D. ii.': 20.0, '20. D. iii.': 20.0, '20. D. iv.': 20.0, '20. D. vii.': 20.0, '20. D. xi.': 20.0, '4. C. xi.': 20.0, '6. C. viii.': 20.0, '8. B. iv.': 20.0, '8. F. ix.': 20.0, 'Add. 10,038.': 20.0, 'Add. 10,094.': 20.0, 'Add. 10,286.': 20.0, 'Add. 10,289.': 20.0, 'Add. 10,290.': 20.0, 'Add. 10,292.': 28.0, 'Add. 10,293': 20.0, 'Add. 10,294': 20.0, 'Add. 10,295': 20.0, 'Add. 10,321': 20.0, 'Add. 10,508.': 28.0, 'Add. 11,113.': 20.0, 'Add. 11,141.': 20.0, 'Add. 11,157.': 20.0, 'Add. 11,238.': 20.0, 'Add. 11,241.': 20.0, 'Add. 11,614': 20.0, 'Add. 12,042': 20.0, 'Add. 12,044': 20.0, 'Add. 12,196.': 20.0, 'Add. 12,213.': 28.0, 'Add. 12,228': 20.0, 'Add. 14,100': 20.0, 'Add. 14,408.': 20.0, 'Add. 14,682': 20.0, 'Add. 14,697.': 20.0, 'Add. 14,907.': 20.0, 'Add. 15,002.': 20.0, 'Add. 15,042': 20.0, 'Add. 15,210-15,213': 20.0, 'Add. 15,212.': 28.0, 'Add. 15,213': 20.0, 'Add. 15,429': 20.0, 'Add. 15,477': 20.0, 'Add. 15,606.': 20.0, 'Add. 16,169.': 20.0, 'Add. 16,441': 20.0, 'Add. 16,563': 20.0, 'Add. 16,955': 20.0, 'Add. 16,956': 20.0, 'Add. 17,084': 20.0, 'Add. 17,443': 20.0, 'Add. 17,914': 20.0, 'Add. 17,920.': 20.0, 'Add. 18,217': 20.0, 'Add. 18,632.': 20.0, 'Add. 18,688': 20.0, 'Add. 19,513.': 20.0, 'Add. 19,554.': 28.0, 'Add. 19,709.': 20.0, 'Add. 21,218': 20.0, 'Add. 21,246': 20.0, 'Add. 22,155': 20.0, 'Add. 22,283.': 20.0, 'Add. 22,311': 20.0, 'Add. 22,312': 20.0, 'Add. 22,821': 20.0, 'Add. 23,829': 20.0, 'Add. 23,930.': 20.0, 'Add. 24,946': 20.0, 'Add. 24,969.': 20.0, 'Add. 24,973.': 20.0, 'Add. 25,434': 20.0, 'Add. 25,569.': 20.0, 'Add. 27,979': 20.0, 'Add. 27879': 60.0, 'Add. 27879 f 248': 20.0, 'Add. 30863': 20.0, 'Add. 30864': 20.0, 'Add. 30984': 20.0, 'Add. 31,840': 20.0, 'Add. 31042': 28.0, 'Add. 4857.': 20.0, 'Add. 4859.': 28.0, 'Add. 4860.': 20.0, 'Add. 4863.': 20.0, 'Add. 4864.': 20.0, 'Add. 4869.': 36.0, 'Add. 4874.': 20.0, 'Add. 5474': 20.0, 'Add. 6796': 20.0, 'Add. 6924.': 20.0, 'Add. 9785': 20.0, 'Arundel 119': 20.0, 'Arundel 123.': 20.0, 'Arundel 174': 20.0, 'Arundel 220.': 20.0, 'Arundel 220. Art. L': 20.0, 'Arundel 230': 20.0, 'Arundel 242.': 20.0, 'Arundel 292.': 20.0, 'Arundel 546.': 20.0, 'Arundel 6': 20.0, 'Arundel 99': 20.0, 'Augustus A. iv.': 20.0, 'Burney 170': 20.0, 'Burney 186.': 20.0, 'Burney 216.': 20.0, 'Burney 280.': 20.0, 'Burney 312': 20.0, 'Caligula A. ii.': 60.0, 'Caligula A. ix.': 20.0, 'Caligula A. x.': 20.0, 'Caligula B. vii.': 36.0, 'Cleopatra B. v.': 20.0, 'Cleopatra D. ix.': 20.0, 'Cleopatra D. viii.': 20.0, 'Cotton Appendix xxvii.': 20.0, 'Domitian xiii.': 20.0, 'Egerton 1069': 20.0, 'Egerton 2022': 20.0, 'Egerton 810': 20.0, 'Egerton 881': 20.0, 'Egerton 989': 20.0, 'Faustina B. vi.': 20.0, 'Galba E. ix.': 20.0, 'Galba E. xi.': 20.0, 'Harley 108.': 20.0, 'Harley 1121.': 20.0, 'Harley 1239.': 20.0, 'Harley 1321': 20.0, 'Harley 1605. Art. I.': 20.0, 'Harley 1629': 20.0, 'Harley 1701.': 20.0, 'Harley 1717.': 20.0, 'Harley 1758.': 20.0, 'Harley 176': 20.0, 'Harley 1883.': 20.0, 'Harley 2252.': 28.0, 'Harley 2253.': 20.0, 'Harley 2280': 20.0, 'Harley 2361.': 20.0, 'Harley 2386.': 28.0, 'Harley 2392': 20.0, 'Harley 2492.': 20.0, 'Harley 2500.': 20.0, 'Harley 2678.': 20.0, 'Harley 273.': 20.0, 'Harley 3043.': 20.0, 'Harley 326.': 20.0, 'Harley 3314': 20.0, 'Harley 3514': 20.0, 'Harley 3573': 20.0, 'Harley 3581': 20.0, 'Harley 3637': 20.0, 'Harley 3681': 20.0, 'Harley 3775.': 20.0, 'Harley 3776.': 20.0, 'Harley 3810. Part I.': 20.0, 'Harley 3830.': 20.0, 'Harley 3943': 20.0, 'Harley 3983.': 20.0, 'Harley 3992': 20.0, 'Harley 4123.': 20.0, 'Harley 4294.': 20.0, 'Harley 4334': 20.0, 'Harley 4361': 20.0, 'Harley 4387': 20.0, 'Harley 4389': 20.0, 'Harley 4404.': 28.0, 'Harley 4417.': 20.0, 'Harley 4418': 20.0, 'Harley 4419': 20.0, 'Harley 4425': 20.0, 'Harley 4482': 20.0, 'Harley 4486.': 20.0, 'Harley 4487.': 20.0, 'Harley 4745': 20.0, 'Harley 49': 20.0, 'Harley 4912': 20.0, 'Harley 51.': 20.0, 'Harley 5243': 20.0, 'Harley 525.': 28.0, 'Harley 527.': 28.0, 'Harley 5427': 20.0, 'Harley 5437': 20.0, 'Harley 5662.': 20.0, 'Harley 6223. Art. I.': 20.0, 'Harley 6340': 20.0, 'Harley 6341': 20.0, 'Harley 6358.': 20.0, 'Harley 641.': 20.0, 'Harley 6508': 20.0, 'Harley 655.': 20.0, 'Harley 6758': 20.0, 'Harley 7333.': 20.0, 'Harley 7334.': 20.0, 'Harley 941.': 20.0, 'Harley 978.': 20.0, 'Julius D. xi.': 20.0, 'Julius E. viii.': 20.0, 'Lansdowne 229.': 20.0, 'Lansdowne 362.': 20.0, 'Lansdowne 699.': 20.0, 'Lansdowne 757': 20.0, 'Lansdowne 762.': 20.0, 'Lansdowne 766.': 20.0, 'Lansdowne 793': 20.0, 'Lansdowne 851.': 20.0, 'Nero A. x.': 20.0, 'Nero A. xi.': 20.0, 'Nero D. ix.': 28.0, 'Nero D. viii.': 20.0, 'Sloane 1044.': 20.0, 'Sloane 1619': 28.0, 'Sloane 1685.': 20.0, 'Sloane 1686.': 20.0, 'Sloane 2232': 20.0, 'Sloane 2233': 20.0, 'Sloane 2593.': 20.0, 'Sloane 457': 20.0, 'Sloane 960': 20.0, 'Titus A. xix.': 44.0, 'Titus D. iii.': 28.0, 'Vespasian A. x.': 20.0, 'Vespasian A. xiii.': 28.0, 'Vespasian B. xxv.': 28.0, 'Vespasian D. ix.': 20.0, 'Vespasian E. iv.': 28.0, 'Vespasian E. x.': 20.0, 'Vespasian E. xvi.': 20.0, 'Vitellius A. x.': 20.0, 'Vitellius A. xiii.': 20.0, 'Vitellius A. xv.': 20.0, 'Vitellius C. viii.': 20.0, 'Vitellius E. x.': 20.0}
{'Classical Romances': '#1f77b4', 'British and English Traditions': '#2ca02c', 'French Traditions': '#9467bd', 'Miscellaneous Romance': '#e377c2', 'Allegorical and Didactic Romance': '#bcbd22', 'Appendix': '#9edae5'}
Warning: When  cdn_resources is 'local' jupyter notebook has issues displaying graphics on chrome/safari. Use cdn_resources='in_line' or cdn_resources='remote' if you have issues viewing graphics in a notebook.
../figs/mss_network_theme.html

C:\Users\yeliu\AppData\Local\Temp\ipykernel_21292\1581401131.py:16: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = cm.get_cmap('tab20', len(themes))

## vis2.1 XXX: connecter les textes dans la meme collection, coloré selon le thème


RQ : si collection se fait par le theme?

TOOOOOO dense!!!!

In [3]:
df=df_all.copy()
df_clean=df[df["collection"].notna()]
print(len(df_all), len(df_clean))
df_clean=df_clean.dropna(subset='theme')
print(df_clean.theme.value_counts(dropna=False),"\n")
df_clean

583 576
theme
Classical Romances                  146
British and English Traditions      109
French Traditions                    47
Miscellaneous Romance                38
Appendix                             38
Allegorical and Didactic Romance     25
Name: count, dtype: int64

,title_theme,title_index,author,theme,cycle,collection,mss,ff,page
0,Heroica,Heroica,Flavius Philostratus,Classical Romances,Cycle of Troy,Royal,16. C. xxiii.,ff. 2-69 b,1
1,Iliaca,Iliaca,Joannes Tzetzes,Classical Romances,Cycle of Troy,Royal,16. C. iv. A. B.,NaN,2
2,Iliaca,Iliaca,Joannes Tzetzes,Classical Romances,Cycle of Troy,Royal,16. D. iii. A. B.,NaN,2
3,Iliaca,Iliaca,Joannes Tzetzes,Classical Romances,Cycle of Troy,Harley,Harley 5662.,ff. 1-56,2
4,Dictys Cretensis,Dictys Cretensis,NaN,Classical Romances,Cycle of Troy,Harley,Harley 3514,NaN,9
...,...,...,...,...,...,...,...,...,...
404,Turpin's Chronicle,Turpin's Chronicle,NaN,Appendix,NaN,Additional,Add. 6924.,ff. 297-303,950
405,Turpin's Chronicle,Turpin's Chronicle,NaN,Appendix,NaN,Additional,"Add. 12,213.",ff. 1-184 b,950
406,Turpin's Chronicle,Turpin's Chronicle,NaN,Appendix,NaN,Additional,"Add. 17,920.",ff. 6 b-19 b,950
407,Turpin's Chronicle,Turpin's Chronicle,NaN,Appendix,NaN,Additional,"Add. 19,513.",ff. 141-163,950
408,Itinerary to Compostella,"Tinctoris, Compostella",NaN,Appendix,NaN,Additional,"Add. 12,213.",ff. 160 b-181 b,951

### par collection

In [5]:
df=df_clean[df_clean['collection']=="Royal"]
display(df.head())

,title_theme,title_index,author,theme,cycle,collection,mss,ff,page
0,Heroica,Heroica,Flavius Philostratus,Classical Romances,Cycle of Troy,Royal,16. C. xxiii.,ff. 2-69 b,1
1,Iliaca,Iliaca,Joannes Tzetzes,Classical Romances,Cycle of Troy,Royal,16. C. iv. A. B.,NaN,2
2,Iliaca,Iliaca,Joannes Tzetzes,Classical Romances,Cycle of Troy,Royal,16. D. iii. A. B.,NaN,2
7,Dares Phrygius,Dares Phrygius,NaN,Classical Romances,Cycle of Troy,Royal,6. C. viii.,ff. 123-133 b,12
8,Dares Phrygius,Dares Phrygius,NaN,Classical Romances,Cycle of Troy,Royal,10. A. x.,ff. 188-192 b,12

In [6]:
text_mss = df.groupby('title_index')['mss'].apply(lambda x: set(x)).to_dict()
print(text_mss)

from itertools import combinations
edges = []
for text1, text2 in combinations(text_mss.keys(), 2):

    shared_mss = text_mss[text1].intersection(text_mss[text2])

    weight = len(shared_mss)

    if weight > 0:

        edges.append({
            "source": text1,
            "target": text2,
            "weight": weight,
            "shared_mss": list(shared_mss)
        })
edge_df = pd.DataFrame(edges)
print(edge_df.shape)
display(edge_df)

{'Alexandreis': {'8. B. iv.', '15. A. x.'}, 'Apollonius of Tyre': {'14. C. xi.', '20. C. ii.'}, 'Aspremont': {'15. E. vi.'}, 'Cleriadus et Meliadice': {'20. C. ii.'}, 'Dares Phrygius': {'10. A. x.', '15. A. xxii.', '15. B. xi.', '6. C. viii.', '13. A. v.'}, 'Fierabras': {'15. E. vi.'}, 'Fulk Fitz-Warin': {'12. C. xii.'}, "Guillaume d'Orange": {'20. D. xi.', '20. B. xix.'}, 'Guy of Warwick': {'8. F. ix.'}, 'Havelok': {'13. A. xxi.'}, 'Heroica': {'16. C. xxiii.'}, 'Historia Regum Britannia': {'14. C. i.', '15. C. xvi.'}, 'Historia Trojana': {'12. D. iii.', '16. F. ix.', '13. C. xii.', '15. C. xvi.'}, 'Iliaca': {'16. C. iv. A. B.', '16. D. iii. A. B.'}, 'Karolellus': {'13. A. xviii.'}, "La Vengeance d'Alexandre": {'19. D. i.'}, 'Lancelot du Lac': {'14. E. iii.', '20. B. xix.', '20. D. iv.', '20. C. vi.', '20. D. iii.', '19. B. vii.', '19. C. viii.'}, 'Le Chemin de Vaillance': {'14. E. ii.'}, "Livre de l'Ordre de Chevalerie": {'14. E. ii.'}, 'Mélusine': {'18. B. ii.'}, 'Ogier le Danois': {'15. E. vi.'}, 'Perceforest': {'19. E. iii.', '15. E. v.', '19. E. ii.'}, 'Pontus and Sidoine': {'15. E. vi.'}, 'Prophecy of the Tenth Sibyl': {'13. A. xiv.', '15. B. xi.', '15. A. xxii.'}, 'Quatre fils Aimon': {'16. G. ii.', '15. E. vi.'}, 'Roman de Brut': {'13. A. xxi.'}, 'Roman de la Rose': {'19. B. xii.', '20. A. xvii.', '19. A. xviii.', '20. D. vii.', '19. B. xiii.'}, 'Romance of Thebes': {'18. D. ii.'}, 'Saint Graal': {'19. C. vii.', '14. E. iii.'}, 'Simon de Pouille': {'15. E. vi.'}, 'Sir Gowghter': {'17. B. xliii.'}, 'Sydrac and Boctus': {'16. F. v.'}, 'Tale of Gamelyn': {'17. D. xv.', '18. C. ii.'}, 'Tale of Two Lovers': {'12. C. xx.'}, 'Titus and Vespasian': {'16. E. viii.'}, 'Tristram': {'20. D. ii.'}, 'Troy Book': {'18. D. vi.', '18. D. ii.'}, "Turpin's Chronicle": {'4. C. xi.', '13. D. i.'}, 'Vita Merlini': {'13. E. i.'}}
(23, 4)

,source,target,weight,shared_mss
0,Apollonius of Tyre,Cleriadus et Meliadice,1,[20. C. ii.]
1,Aspremont,Fierabras,1,[15. E. vi.]
2,Aspremont,Ogier le Danois,1,[15. E. vi.]
3,Aspremont,Pontus and Sidoine,1,[15. E. vi.]
4,Aspremont,Quatre fils Aimon,1,[15. E. vi.]
5,Aspremont,Simon de Pouille,1,[15. E. vi.]
6,Dares Phrygius,Prophecy of the Tenth Sibyl,2,"[15. A. xxii., 15. B. xi.]"
7,Fierabras,Ogier le Danois,1,[15. E. vi.]
8,Fierabras,Pontus and Sidoine,1,[15. E. vi.]
9,Fierabras,Quatre fils Aimon,1,[15. E. vi.]
10,Fierabras,Simon de Pouille,1,[15. E. vi.]
11,Guillaume d'Orange,Lancelot du Lac,1,[20. B. xix.]
12,Havelok,Roman de Brut,1,[13. A. xxi.]
13,Historia Regum Britannia,Historia Trojana,1,[15. C. xvi.]
14,Lancelot du Lac,Saint Graal,1,[14. E. iii.]
15,Le Chemin de Vaillance,Livre de l'Ordre de Chevalerie,1,[14. E. ii.]
16,Ogier le Danois,Pontus and Sidoine,1,[15. E. vi.]
17,Ogier le Danois,Quatre fils Aimon,1,[15. E. vi.]
18,Ogier le Danois,Simon de Pouille,1,[15. E. vi.]
19,Pontus and Sidoine,Quatre fils Aimon,1,[15. E. vi.]
20,Pontus and Sidoine,Simon de Pouille,1,[15. E. vi.]
21,Quatre fils Aimon,Simon de Pouille,1,[15. E. vi.]
22,Romance of Thebes,Troy Book,1,[18. D. ii.]

In [7]:
from pyvis.network import Network

#-------------node size---------------
text_freq = df.groupby('title_index')['mss'].nunique()

min_size, max_size = 10, 30

node_sizes = ((text_freq - text_freq.min()) /
             (text_freq.max() - text_freq.min() + 1e-9) *
             (max_size - min_size) + min_size).to_dict()


#-------------node color---------------
from matplotlib import cm, colors

text_theme = df.drop_duplicates('title_index').set_index('title_index')['theme'].to_dict()
text_theme

themes = df['theme'].unique()
cmap = cm.get_cmap('tab10', len(themes))
theme_colors = {
    theme: colors.to_hex(cmap(i))
    for i, theme in enumerate(themes)
}
# {'Classical Romances': '#1f77b4',
#  'British and English Traditions': '#2ca02c',
#  'French Traditions': '#9467bd',
#  'Miscellaneous Romance': '#e377c2',
#  'Allegorical and Didactic Romance': '#bcbd22',
#  'Appendix': '#17becf'}


#----------------pyvis------------------
# notebook=True 在 jupyter 直接显示
net = Network(height='800px', width='100%', notebook=True)

for text in text_freq.index:
    theme = text_theme[text]
    net.add_node(
        text,
        label=text,
        size=node_sizes[text],
        color=theme_colors[theme],
        title=f"{text}, Theme: {theme}"
    )
for _, row in edge_df.iterrows():
    net.add_edge(
        row['source'],
        row['target'],
        value=row['weight']*5,
        color="gray",
        title=f"Shared MSS: {','.join(row['shared_mss'])}"
    )
    
# -------------LAYOUT--------------------
net.force_atlas_2based(
    gravity=-200,          # 整体节点拉开的力度，负值越大，节点分得越开
    central_gravity=0.05,  # 越小，节点越靠中心；越大，节点聚到中心
    spring_length=250,     # 弹簧长度，越大，节点间隔越远
    spring_strength=0.05,  # 弹簧刚度，控制边对节点靠近的作用力
    damping=0.4            # 收敛阻尼
)

#-------------------SHOW---------------------
# 生成 HTML
path_html='../figs/text_in_mss_royal_network.html'
net.show(path_html)

## ----------------add title---------------

# 自动在 body 开始处插入标题
title_text = "Texts Network on Shared Manuscripts colored by Theme"
with open(path_html, 'r', encoding='utf-8') as f:
    html_content = f.read()

# 在 <body> 标签后插入标题
html_content = html_content.replace(
    '<body>',
    f'<body>\n<h2 style="text-align:center">{title_text}</h2>'
)
# 保存回 HTML 文件
with open(path_html, 'w', encoding='utf-8') as f:
    f.write(html_content)

Warning: When  cdn_resources is 'local' jupyter notebook has issues displaying graphics on chrome/safari. Use cdn_resources='in_line' or cdn_resources='remote' if you have issues viewing graphics in a notebook.
../figs/text_in_mss_royal_network.html

C:\Users\yeliu\AppData\Local\Temp\ipykernel_37132\4227385379.py:20: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = cm.get_cmap('tab10', len(themes))

In [56]:

coll_mss = df.groupby('title_index')['collection'].apply(lambda x: set(x)).to_dict()
print(coll_mss)

from itertools import combinations
edges = []
for text1, text2 in combinations(coll_mss.keys(), 2):

    shared_mss = coll_mss[text1].intersection(coll_mss[text2])

    weight = len(shared_mss)

    if weight > 0:

        edges.append({
            "source": text1,
            "target": text2,
            "weight": weight,
            "shared_collection": list(shared_mss)
        })
edge_df = pd.DataFrame(edges)
print(edge_df.shape)
display(edge_df)

{'Alexander saga': {'Additional'}, 'Alexandreis': {'Additional', 'Royal', 'Harley', 'Burney'}, 'Amadis de Gaula': {'Lansdowne'}, 'Amys and Amylion': {'Harley'}, 'Apollonius of Tyre': {'Royal', 'Sloane', 'Arundel', 'Cotton', 'Additional'}, 'Aronus and Marina': {'Harley'}, 'Artus de Bretagne': {'Additional'}, 'Aspremont': {'Royal', 'Additional'}, 'Battle of Roncevaux': {'Cotton'}, 'Birth of Merlin': {'Arundel'}, "Blanchandin et Orgueillose d'Amors": {'Additional'}, 'Boy and Mantle': {'Additional'}, 'Brutus': {'Cotton'}, 'Cassandra': {'Sloane'}, 'Chanson de Brut': {'Harley'}, 'Cleriadus et Meliadice': {'Royal'}, 'Contes et Fabliaux': {'Additional'}, 'Corbaccio': {'Harley'}, 'Dares Phrygius': {'Royal', 'Sloane', 'Cotton', 'Burney', 'Harley', 'Additional'}, 'Dictys Cretensis': {'Additional', 'Harley', 'Burney'}, 'Doon de la Roche': {'Harley'}, 'Emare': {'Cotton'}, 'Enfances Ogier': {'Harley'}, 'Ereks saga Artuskappa': {'Additional'}, 'Fiammetta': {'Harley'}, 'Fierabras': {'Royal'}, 'Filocolo': {'Harley', 'Additional'}, 'Filostrato': {'Additional'}, 'Floire et Blancheflor': {'Additional'}, 'Florence de Rome': {'Lansdowne'}, 'Floridam and Elluide': {'Cotton'}, 'Florimont': {'Harley'}, 'Fulk Fitz-Warin': {'Royal'}, 'Gabons saga ok Vigolea': {'Additional'}, 'Gesta Regum Britannia': {'Cotton'}, 'Girard de Roussillon': {'Harley'}, 'Gui de Bourgogne': {'Harley'}, "Guillaume d'Orange": {'Royal', 'Harley'}, 'Guiron le Courtois': {'Additional'}, 'Guy of Warwick': {'Royal', 'Sloane', 'Cotton', 'Lansdowne', 'Harley', 'Additional'}, 'Hanes Taliesin': {'Additional'}, 'Havelok': {'Royal'}, 'Heroica': {'Royal'}, 'Historia Regum Britannia': {'Royal'}, 'Historia Trojana': {'Royal', 'Arundel', 'Lansdowne', 'Harley', 'Additional'}, 'History of Troy': {'Burney'}, 'Iliaca': {'Royal', 'Harley'}, 'Ipomedon': {'Harley'}, 'Iwein': {'Additional'}, 'Karolellus': {'Royal'}, "King Arthur's Death": {'Additional'}, 'King Horn': {'Harley'}, 'King Humber': {'Additional'}, 'King Robert of Sicily': {'Harley', 'Additional'}, "La Vengeance d'Alexandre": {'Royal'}, 'Lancelot du Lac': {'Royal', 'Lansdowne', 'Harley', 'Additional'}, 'Lays of Marie de France': {'Harley'}, "Lazamon's Brut": {'Cotton'}, 'Le Chemin de Vaillance': {'Royal'}, "Les deux Chevaliers, and Le dit de Guillaume d'Angleterre": {'Additional'}, 'Letters of Dindimus to Alexander the Great': {'Cotton'}, 'Life of Harold, King of England': {'Harley'}, 'Life of Virgilius': {'Additional'}, "Livre de l'Ordre de Chevalerie": {'Royal'}, 'Lybeaus Desconus': {'Cotton'}, 'Magus saga Jarls': {'Additional'}, 'Marvels of India': {'Arundel', 'Cotton'}, 'Meliadus': {'Additional'}, 'Meriadoc and Gawain': {'Cotton'}, 'Merlin': {'Harley', 'Additional'}, 'Miscellaneous Ballads': {'Additional'}, 'Morte Arthur': {'Harley'}, 'Mélusine': {'Royal', 'Harley', 'Additional'}, 'Octavian the Emperor': {'Cotton'}, 'Ogier le Danois': {'Royal'}, 'Partonopeus de Blois': {'Additional'}, 'Perceforest': {'Royal'}, 'Peredur ab Efrawc': {'Additional'}, 'Petit Jean de Saintré': {'Additional', 'Cotton'}, 'Philomena': {'Additional'}, 'Pontus and Sidoine': {'Royal'}, 'Prophecies de Merlin': {'Harley', 'Additional'}, 'Prophecies of Merlin and others': {'Harley'}, 'Prophecy of the Tenth Sibyl': {'Royal', 'Egerton', 'Cotton'}, 'Quatre fils Aimon': {'Royal', 'Sloane'}, 'Reali di Francia': {'Additional'}, 'Riccardetto': {'Additional'}, 'Richard Coeur-de-Lion': {'Additional'}, 'Rimur from Trójumanna saga': {'Additional'}, 'Robin Hood': {'Additional'}, 'Robyn and Gandelyn': {'Sloane'}, "Roman d'Athis et Profilas": {'Additional'}, "Roman d'Eneas": {'Additional'}, 'Roman de Brut': {'Royal', 'Harley', 'Cotton'}, 'Roman de Troie': {'Harley', 'Additional'}, 'Roman de la Rose': {'Royal', 'Egerton', 'Harley', 'Additional'}, 'Romance of Jason': {'Additional'}, 'Romance of Thebes': {'Additional', 'Royal', 'Arundel', 'Cotton'}, 'Romance of Troy': {'Harley'}, 'Romance of the Peers of France': {'Additional'}, 'Romances and Ballads': {'Additional'}, 'Saint Graal': {'Royal', 'Additional'}, 'Samsons saga Fagra': {'Additional'}, 'Scottish Ballads': {'Additional'}, 'Simon de Pouille': {'Royal'}, 'Sir Eglamour of Artois': {'Cotton'}, 'Sir Gawain and the Green Knight': {'Cotton'}, 'Sir Gowghter': {'Royal'}, 'Sir Isumbras': {'Cotton'}, 'Sir Lancelot of Dulake': {'Additional'}, 'Sir Orpheo': {'Harley'}, 'Story of Albina and her Sisters': {'Harley', 'Cotton'}, 'Sydrac and Boctus': {'Royal', 'Sloane', 'Lansdowne', 'Harley', 'Additional'}, 'Tale of Antiochus': {'Harley'}, 'Tale of Gamelyn': {'Royal', 'Sloane', 'Lansdowne', 'Harley'}, 'Tale of Two Lovers': {'Royal', 'Harley'}, 'Tales and Fables': {'Additional'}, 'The Chaste Duchess': {'Additional'}, 'The Diana of Montemayor': {'Additional'}, "The Three Kings' Sons": {'Harley'}, 'Theagenes and Stelliana': {'Harley'}, 'Theseus de Cologne': {'Additional'}, 'Thomas of Erceldoune': {'Lansdowne', 'Cotton'}, 'Tinctoris, Compostella': {'Additional'}, 'Titurel': {'Additional'}, 'Titus and Vespasian': {'Additional', 'Royal', 'Cotton'}, 'Treatise on the Brahmins': {'Arundel'}, 'Tristram': {'Royal', 'Egerton', 'Harley', 'Additional'}, 'Troilus and Cryseyde': {'Harley', 'Additional'}, 'Troy Book': {'Royal', 'Arundel', 'Cotton'}, 'Trójumanna saga': {'Additional'}, "Turpin's Chronicle": {'Royal', 'Arundel', 'Cotton', 'Harley', 'Additional'}, 'Two Romantic Tales': {'Additional'}, 'Uberto and Philomena': {'Additional'}, 'Vita Merlini': {'Royal', 'Harley', 'Cotton'}, 'Voeux du Paon': {'Arundel', 'Harley', 'Additional'}, 'Wigalois': {'Additional'}, 'Ywain and Gawain': {'Cotton'}}
(4162, 4)

,source,target,weight,shared_collection
0,Alexander saga,Alexandreis,1,[Additional]
1,Alexander saga,Apollonius of Tyre,1,[Additional]
2,Alexander saga,Artus de Bretagne,1,[Additional]
3,Alexander saga,Aspremont,1,[Additional]
4,Alexander saga,Blanchandin et Orgueillose d'Amors,1,[Additional]
...,...,...,...,...
4157,Uberto and Philomena,Voeux du Paon,1,[Additional]
4158,Uberto and Philomena,Wigalois,1,[Additional]
4159,Vita Merlini,Voeux du Paon,1,[Harley]
4160,Vita Merlini,Ywain and Gawain,1,[Cotton]
4161,Voeux du Paon,Wigalois,1,[Additional]

In [58]:
from pyvis.network import Network
#-------------node size---------------
text_freq = df.groupby('title_index')['mss'].nunique()

min_size, max_size = 10, 30

node_sizes = ((text_freq - text_freq.min()) /
             (text_freq.max() - text_freq.min() + 1e-9) *
             (max_size - min_size) + min_size).to_dict()


#-------------node color---------------
from matplotlib import cm, colors
text_theme = df.drop_duplicates('title_index').set_index('title_index')['theme'].to_dict()
text_theme

themes = df['theme'].unique()
cmap = cm.get_cmap('tab10', len(themes))
theme_colors = {
    theme: colors.to_hex(cmap(i))
    for i, theme in enumerate(themes)
}
# {'Classical Romances': '#1f77b4',
#  'British and English Traditions': '#2ca02c',
#  'French Traditions': '#9467bd',
#  'Miscellaneous Romance': '#e377c2',
#  'Allegorical and Didactic Romance': '#bcbd22',
#  'Appendix': '#17becf'}


#----------------pyvis------------------
# notebook=True 在 jupyter 直接显示
net = Network(height='800px', width='100%', notebook=True)

for text in text_freq.index:
    theme = text_theme[text]
    net.add_node(
        text,
        label=text,
        size=node_sizes[text],
        color=theme_colors[theme],
        title=f"{text}, Theme: {theme}"
    )
for _, row in edge_df.iterrows():
    net.add_edge(
        row['source'],
        row['target'],
        value=row['weight']*5,
        color="gray",
        title=f"Shared Collection: {','.join(row['shared_collection'])}"
    )
    
# -------------LAYOUT--------------------
net.force_atlas_2based(
    gravity=-200,          # 整体节点拉开的力度，负值越大，节点分得越开
    central_gravity=0.05,  # 越小，节点越靠中心；越大，节点聚到中心
    spring_length=250,     # 弹簧长度，越大，节点间隔越远
    spring_strength=0.05,  # 弹簧刚度，控制边对节点靠近的作用力
    damping=0.4            # 收敛阻尼
)

#-------------------SHOW---------------------
# 生成 HTML
path_html='../figs/text_in_collection_network.html'
net.show(path_html)

## ----------------add title---------------

# 自动在 body 开始处插入标题
title_text = "Texts Network on Shared Collection colored by Theme"
with open(path_html, 'r', encoding='utf-8') as f:
    html_content = f.read()

# 在 <body> 标签后插入标题
html_content = html_content.replace(
    '<body>',
    f'<body>\n<h2 style="text-align:center">{title_text}</h2>'
)
# 保存回 HTML 文件
with open(path_html, 'w', encoding='utf-8') as f:
    f.write(html_content)

C:\Users\yeliu\AppData\Local\Temp\ipykernel_21292\2852827970.py:18: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = cm.get_cmap('tab10', len(themes))

Warning: When  cdn_resources is 'local' jupyter notebook has issues displaying graphics on chrome/safari. Use cdn_resources='in_line' or cdn_resources='remote' if you have issues viewing graphics in a notebook.
../figs/text_in_collection_network.html

## vis2.2 : connecte les textes s'il sont dans le meme mss, coloré selon le thème


RQ : si  les textes dans le meme manuscript ont le theme?


我们按照mss来连接texts，然后按照theme给texts着色，是不是回答mss是否是按照theme来集合texts的？如果一个cluster中有主导颜色则为是？我现在去掉了theme 为unk的数据，观察到图上大部分的点是没有链接的，但是仍形成了四个简单的小clusters，

In [12]:
df=df_all.copy()
df=df[df["collection"].notna()]
print(len(df_all), len(df))
# print(df.theme.value_counts(dropna=False),"\n")

# nan in "theme":
df=df.dropna(subset='theme')

print(df[["mss",'title_index']].value_counts(dropna=False))

display(df)

583 576
mss               title_index
13. A. xxi.       Havelok                            4
Nero A. xi.       Turpin's Chronicle                 4
Harley 4745       Alexandreis                        4
8. B. iv.         Alexandreis                        4
15. A. x.         Alexandreis                        4
                                                    ..
Harley 5662.      Iliaca                             1
13. A. xiv.       Prophecy of the Tenth Sibyl        1
Vespasian E. iv.  Vita Merlini                       1
Vespasian E. x.   Story of Albina and her Sisters    1
Vitellius A. x.   Roman de Brut                      1
Name: count, Length: 331, dtype: int64

,title_theme,title_index,author,theme,cycle,collection,mss,ff,page
0,Heroica,Heroica,Flavius Philostratus,Classical Romances,Cycle of Troy,Royal,16. C. xxiii.,ff. 2-69 b,1
1,Iliaca,Iliaca,Joannes Tzetzes,Classical Romances,Cycle of Troy,Royal,16. C. iv. A. B.,NaN,2
2,Iliaca,Iliaca,Joannes Tzetzes,Classical Romances,Cycle of Troy,Royal,16. D. iii. A. B.,NaN,2
3,Iliaca,Iliaca,Joannes Tzetzes,Classical Romances,Cycle of Troy,Harley,Harley 5662.,ff. 1-56,2
4,Dictys Cretensis,Dictys Cretensis,NaN,Classical Romances,Cycle of Troy,Harley,Harley 3514,NaN,9
...,...,...,...,...,...,...,...,...,...
404,Turpin's Chronicle,Turpin's Chronicle,NaN,Appendix,NaN,Additional,Add. 6924.,ff. 297-303,950
405,Turpin's Chronicle,Turpin's Chronicle,NaN,Appendix,NaN,Additional,"Add. 12,213.",ff. 1-184 b,950
406,Turpin's Chronicle,Turpin's Chronicle,NaN,Appendix,NaN,Additional,"Add. 17,920.",ff. 6 b-19 b,950
407,Turpin's Chronicle,Turpin's Chronicle,NaN,Appendix,NaN,Additional,"Add. 19,513.",ff. 141-163,950
408,Itinerary to Compostella,"Tinctoris, Compostella",NaN,Appendix,NaN,Additional,"Add. 12,213.",ff. 160 b-181 b,951

In [13]:
text_mss = df.groupby('title_index')['mss'].apply(lambda x: set(x)).to_dict()
print(text_mss)

from itertools import combinations
edges = []
for text1, text2 in combinations(text_mss.keys(), 2):

    shared_mss = text_mss[text1].intersection(text_mss[text2])

    weight = len(shared_mss)

    if weight > 0:

        edges.append({
            "source": text1,
            "target": text2,
            "weight": weight,
            "shared_mss": list(shared_mss)
        })
edge_df = pd.DataFrame(edges)
print(edge_df.shape)
display(edge_df)

{'Alexander saga': {'Add. 24,969.', 'Add. 11,238.'}, 'Alexandreis': {'Add. 18,217', '8. B. iv.', 'Add. 17,084', 'Add. 22,821', 'Burney 312', 'Harley 5437', '15. A. x.', 'Harley 4745'}, 'Amadis de Gaula': {'Lansdowne 766.'}, 'Amys and Amylion': {'Harley 2386.'}, 'Apollonius of Tyre': {'Vespasian A. xiii.', 'Sloane 2233', 'Arundel 292.', '20. C. ii.', 'Titus D. iii.', 'Arundel 123.', 'Sloane 1619', '14. C. xi.', 'Add. 4864.', 'Add. 4857.'}, 'Aronus and Marina': {'Harley 2678.'}, 'Artus de Bretagne': {'Add. 10,295'}, 'Aspremont': {'Add. 10,508.', '15. E. vi.'}, 'Battle of Roncevaux': {'Titus A. xix.'}, 'Birth of Merlin': {'Arundel 220. Art. L'}, "Blanchandin et Orgueillose d'Amors": {'Add. 15,212.'}, 'Boy and Mantle': {'Add. 27879'}, 'Brutus': {'Vespasian A. x.'}, 'Cassandra': {'Sloane 457'}, 'Chanson de Brut': {'Harley 1605. Art. I.'}, 'Cleriadus et Meliadice': {'20. C. ii.'}, 'Contes et Fabliaux': {'Add. 15,210-15,213'}, 'Corbaccio': {'Harley 3581'}, 'Dares Phrygius': {'Harley 641.', 'Vespasian B. xxv.', '10. A. x.', 'Vitellius C. viii.', 'Caligula B. vii.', 'Add. 15,042', '15. A. xxii.', '15. B. xi.', '6. C. viii.', 'Cleopatra B. v.', 'Sloane 1619', '13. A. v.', 'Burney 216.', 'Add. 10,094.', 'Add. 19,709.', 'Vitellius A. xiii.', 'Burney 280.'}, 'Dictys Cretensis': {'Burney 170', 'Add. 15,429', 'Harley 3514'}, 'Doon de la Roche': {'Harley 4404.'}, 'Emare': {'Caligula A. ii.'}, 'Enfances Ogier': {'Harley 4404.'}, 'Ereks saga Artuskappa': {'Add. 4859.'}, 'Fiammetta': {'Harley 5427', 'Harley 3573'}, 'Fierabras': {'15. E. vi.'}, 'Filocolo': {'Add. 14,682', 'Harley 3314'}, 'Filostrato': {'Add. 21,246'}, 'Floire et Blancheflor': {'Add. 15,213'}, 'Florence de Rome': {'Lansdowne 362.'}, 'Floridam and Elluide': {'Nero D. ix.'}, 'Florimont': {'Harley 4487.', 'Harley 3983.'}, 'Fulk Fitz-Warin': {'12. C. xii.'}, 'Gabons saga ok Vigolea': {'Add. 11,157.'}, 'Gesta Regum Britannia': {'Julius D. xi.'}, 'Girard de Roussillon': {'Harley 4334'}, 'Gui de Bourgogne': {'Harley 527.'}, "Guillaume d'Orange": {'20. D. xi.', 'Harley 1321', '20. B. xix.'}, 'Guiron le Courtois': {'Add. 23,930.'}, 'Guy of Warwick': {'Harley 5243', 'Harley 7333.', 'Vespasian D. ix.', 'Lansdowne 699.', 'Sloane 1044.', '8. F. ix.', 'Harley 3775.', 'Add. 14,408.'}, 'Hanes Taliesin': {'Add. 14,697.', 'Add. 15,002.'}, 'Havelok': {'13. A. xxi.'}, 'Heroica': {'16. C. xxiii.'}, 'Historia Regum Britannia': {'14. C. i.', '15. C. xvi.'}, 'Historia Trojana': {'Harley 4387', '12. D. iii.', 'Harley 3637', 'Add. 9785', 'Harley 3681', '13. C. xii.', 'Harley 4123.', 'Arundel 6', 'Add. 15,477', 'Lansdowne 229.', 'Add. 22,155', 'Harley 51.', '15. C. xvi.', 'Harley 176', '16. F. ix.', 'Arundel 174'}, 'History of Troy': {'Burney 186.'}, 'Iliaca': {'Harley 5662.', '16. C. iv. A. B.', '16. D. iii. A. B.'}, 'Ipomedon': {'Harley 2252.'}, 'Iwein': {'Add. 19,554.'}, 'Karolellus': {'13. A. xviii.'}, "King Arthur's Death": {'Add. 27879'}, 'King Horn': {'Harley 527.', 'Harley 2253.'}, 'King Humber': {'Add. 27879 f 248'}, 'King Robert of Sicily': {'Harley 525.', 'Harley 1701.', 'Add. 22,283.'}, "La Vengeance d'Alexandre": {'19. D. i.'}, 'Lancelot du Lac': {'14. E. iii.', 'Lansdowne 757', '20. B. xix.', '20. D. iv.', '20. C. vi.', '20. D. iii.', 'Harley 4419', 'Add. 10,293', 'Add. 10,294', '19. B. vii.', 'Harley 6341', 'Add. 17,443', '19. C. viii.'}, 'Lays of Marie de France': {'Harley 978.'}, "Lazamon's Brut": {'Caligula A. ix.'}, 'Le Chemin de Vaillance': {'14. E. ii.'}, "Les deux Chevaliers, and Le dit de Guillaume d'Angleterre": {'Add. 15,606.'}, 'Letters of Dindimus to Alexander the Great': {'Galba E. xi.'}, 'Life of Harold, King of England': {'Harley 3776.'}, 'Life of Virgilius': {'Add. 4859.', 'Add. 11,141.'}, "Livre de l'Ordre de Chevalerie": {'14. E. ii.'}, 'Lybeaus Desconus': {'Caligula A. ii.'}, 'Magus saga Jarls': {'Add. 4874.', 'Add. 4869.', 'Add. 4860.'}, 'Marvels of India': {'Vitellius A. xv.', 'Arundel 242.'}, 'Meliadus': {'Add. 12,228'}, 'Meriadoc and Gawain': {'Faustina B. vi.'}, 'Merlin': {'Add. 27879', 'Harley 6223. Art. I.', 'Harley 6340', 'Add. 10,292.'}, 'Miscellaneous Ballads': {'Add. 27879'}, 'Morte Arthur': {'Harley 2252.'}, 'Mélusine': {'Harley 4418', '18. B. ii.', 'Add. 6796'}, 'Octavian the Emperor': {'Caligula A. ii.'}, 'Ogier le Danois': {'15. E. vi.'}, 'Partonopeus de Blois': {'Add. 15,212.'}, 'Perceforest': {'19. E. iii.', '15. E. v.', '19. E. ii.'}, 'Peredur ab Efrawc': {'Add. 14,907.'}, 'Petit Jean de Saintré': {'Nero D. ix.', 'Add. 11,614'}, 'Philomena': {'Add. 21,218'}, 'Pontus and Sidoine': {'15. E. vi.'}, 'Prophecies de Merlin': {'Harley 1629', 'Add. 25,434'}, 'Prophecies of Merlin and others': {'Harley 1717.'}, 'Prophecy of the Tenth Sibyl': {'13. A. xiv.', 'Vespasian B. xxv.', 'Caligula B. vii.', 'Titus D. iii.', '15. B. xi.', '15. A. xxii.', 'Egerton 810', 'Vespasian E. iv.', 'Caligula A. x.', 'Domitian xiii.'}, 'Quatre fils Aimon': {'16. G. ii.', 'Sloane 960', '15. E. vi.'}, 'Reali di Francia': {'Add. 22,312'}, 'Riccardetto': {'Add. 10,321'}, 'Richard Coeur-de-Lion': {'Add. 31042'}, 'Rimur from Trójumanna saga': {'Add. 11,113.'}, 'Robin Hood': {'Add. 27879'}, 'Robyn and Gandelyn': {'Sloane 2593.'}, "Roman d'Athis et Profilas": {'Add. 16,441'}, "Roman d'Eneas": {'Add. 14,100'}, 'Roman de Brut': {'Harley 6508', 'Vitellius A. x.', '13. A. xxi.'}, 'Roman de Troie': {'Add. 30863', 'Harley 4482'}, 'Roman de la Rose': {'19. B. xii.', 'Egerton 1069', 'Egerton 2022', '20. A. xvii.', '19. A. xviii.', 'Add. 12,042', 'Add. 31,840', 'Harley 4425', 'Add. 16,169.', '20. D. vii.', '19. B. xiii.', 'Egerton 881'}, 'Romance of Jason': {'Add. 10,290.'}, 'Romance of Thebes': {'Cotton Appendix xxvii.', '18. D. ii.', 'Add. 18,632.', 'Arundel 119'}, 'Romance of Troy': {'Harley 525.'}, 'Romance of the Peers of France': {'Add. 10,508.'}, 'Romances and Ballads': {'Add. 27,979'}, 'Saint Graal': {'19. C. vii.', '14. E. iii.', 'Add. 10,292.'}, 'Samsons saga Fagra': {'Add. 4863.'}, 'Scottish Ballads': {'Add. 22,311'}, 'Simon de Pouille': {'15. E. vi.'}, 'Sir Eglamour of Artois': {'Caligula A. ii.'}, 'Sir Gawain and the Green Knight': {'Nero A. x.'}, 'Sir Gowghter': {'17. B. xliii.'}, 'Sir Isumbras': {'Caligula A. ii.'}, 'Sir Lancelot of Dulake': {'Add. 27879'}, 'Sir Orpheo': {'Harley 3810. Part I.'}, 'Story of Albina and her Sisters': {'Titus A. xix.', 'Vespasian E. x.', 'Nero D. viii.', 'Cleopatra D. viii.', 'Harley 2386.', 'Harley 941.', 'Cleopatra D. ix.'}, 'Sydrac and Boctus': {'Harley 4361', 'Sloane 2232', '16. F. v.', 'Lansdowne 793', 'Add. 10,286.', 'Add. 16,563', 'Harley 1121.', 'Add. 17,914', 'Harley 4486.', 'Harley 4294.', 'Harley 4417.'}, 'Tale of Antiochus': {'Harley 3830.'}, 'Tale of Gamelyn': {'Sloane 1686.', 'Sloane 1685.', '18. C. ii.', '17. D. xv.', 'Lansdowne 851.', 'Harley 7334.', 'Harley 1758.'}, 'Tale of Two Lovers': {'Harley 1883.', '12. C. xx.', 'Harley 2492.'}, 'Tales and Fables': {'Add. 24,946'}, 'The Chaste Duchess': {'Add. 25,569.'}, 'The Diana of Montemayor': {'Add. 18,688'}, "The Three Kings' Sons": {'Harley 326.'}, 'Theagenes and Stelliana': {'Harley 6758'}, 'Theseus de Cologne': {'Add. 16,955'}, 'Thomas of Erceldoune': {'Vitellius E. x.', 'Lansdowne 762.'}, 'Tinctoris, Compostella': {'Add. 12,213.'}, 'Titurel': {'Add. 30984'}, 'Titus and Vespasian': {'Add. 10,038.', 'Caligula A. ii.', 'Vespasian E. xvi.', 'Add. 10,289.', '16. E. viii.', 'Add. 31042'}, 'Treatise on the Brahmins': {'Arundel 546.'}, 'Tristram': {'Egerton 989', 'Add. 5474', 'Harley 49', 'Add. 23,829', '20. D. ii.', 'Harley 4389'}, 'Troilus and Cryseyde': {'Add. 12,044', 'Harley 3943', 'Harley 2392', 'Harley 2280', 'Harley 1239.', 'Harley 4912'}, 'Troy Book': {'18. D. vi.', 'Augustus A. iv.', '18. D. ii.', 'Arundel 99'}, 'Trójumanna saga': {'Add. 4869.'}, "Turpin's Chronicle": {'Vespasian A. xiii.', '13. D. i.', 'Nero A. xi.', 'Titus A. xix.', 'Harley 273.', 'Harley 2500.', 'Caligula B. vii.', 'Harley 108.', 'Harley 3043.', 'Add. 17,920.', '4. C. xi.', 'Add. 19,513.', 'Add. 6924.', 'Add. 12,213.', 'Arundel 220.', 'Harley 2361.', 'Harley 6358.'}, 'Two Romantic Tales': {'Add. 11,241.', 'Add. 4869.', 'Add. 24,973.'}, 'Uberto and Philomena': {'Add. 12,196.'}, 'Vita Merlini': {'13. E. i.', 'Julius E. viii.', 'Titus A. xix.', 'Harley 655.', 'Vespasian E. iv.'}, 'Voeux du Paon': {'Add. 16,956', 'Add. 30864', 'Arundel 230', 'Harley 3992'}, 'Wigalois': {'Add. 19,554.'}, 'Ywain and Gawain': {'Galba E. ix.'}}
(81, 4)

,source,target,weight,shared_mss
0,Amys and Amylion,Story of Albina and her Sisters,1,[Harley 2386.]
1,Apollonius of Tyre,Cleriadus et Meliadice,1,[20. C. ii.]
2,Apollonius of Tyre,Dares Phrygius,1,[Sloane 1619]
3,Apollonius of Tyre,Prophecy of the Tenth Sibyl,1,[Titus D. iii.]
4,Apollonius of Tyre,Turpin's Chronicle,1,[Vespasian A. xiii.]
...,...,...,...,...
76,Story of Albina and her Sisters,Turpin's Chronicle,1,[Titus A. xix.]
77,Story of Albina and her Sisters,Vita Merlini,1,[Titus A. xix.]
78,"Tinctoris, Compostella",Turpin's Chronicle,1,"[Add. 12,213.]"
79,Trójumanna saga,Two Romantic Tales,1,[Add. 4869.]
80,Turpin's Chronicle,Vita Merlini,1,[Titus A. xix.]

In [14]:
text_coll = df.drop_duplicates('title_index').set_index('title_index')['collection'].to_dict()
text_coll

{'Heroica': 'Royal',
 'Iliaca': 'Royal',
 'Dictys Cretensis': 'Harley',
 'Dares Phrygius': 'Royal',
 'Roman de Troie': 'Harley',
 'Historia Trojana': 'Royal',
 'Trójumanna saga': 'Additional',
 'Rimur from Trójumanna saga': 'Additional',
 'History of Troy': 'Burney',
 'Filostrato': 'Additional',
 'Troilus and Cryseyde': 'Harley',
 'Troy Book': 'Royal',
 "Roman d'Eneas": 'Additional',
 'Romance of Troy': 'Harley',
 'Romance of Thebes': 'Royal',
 'Romance of Jason': 'Additional',
 'Alexandreis': 'Royal',
 'Alexander saga': 'Additional',
 'Marvels of India': 'Cotton',
 'Treatise on the Brahmins': 'Arundel',
 'Letters of Dindimus to Alexander the Great': 'Cotton',
 "La Vengeance d'Alexandre": 'Royal',
 'Voeux du Paon': 'Harley',
 'Florimont': 'Harley',
 'Apollonius of Tyre': 'Royal',
 'Sir Orpheo': 'Harley',
 "Roman d'Athis et Profilas": 'Additional',
 'Titus and Vespasian': 'Royal',
 'Prophecy of the Tenth Sibyl': 'Royal',
 'Life of Virgilius': 'Additional',
 'Story of Albina and her Sisters': 'Cotton',
 'Historia Regum Britannia': 'Royal',
 'Roman de Brut': 'Royal',
 "Lazamon's Brut": 'Cotton',
 'Chanson de Brut': 'Harley',
 'Gesta Regum Britannia': 'Cotton',
 'Brutus': 'Cotton',
 'Vita Merlini': 'Royal',
 'Prophecies of Merlin and others': 'Harley',
 'Thomas of Erceldoune': 'Cotton',
 'King Humber': 'Additional',
 'Saint Graal': 'Royal',
 'Merlin': 'Harley',
 'Lancelot du Lac': 'Royal',
 'Tristram': 'Royal',
 'Meliadus': 'Additional',
 'Guiron le Courtois': 'Additional',
 'Prophecies de Merlin': 'Harley',
 'Meriadoc and Gawain': 'Cotton',
 'Perceforest': 'Royal',
 'Artus de Bretagne': 'Additional',
 'Cleriadus et Meliadice': 'Royal',
 'Birth of Merlin': 'Arundel',
 'Sir Gawain and the Green Knight': 'Cotton',
 'Iwein': 'Additional',
 'Ywain and Gawain': 'Cotton',
 'Peredur ab Efrawc': 'Additional',
 'Sir Lancelot of Dulake': 'Additional',
 'Wigalois': 'Additional',
 'Lybeaus Desconus': 'Cotton',
 'Gabons saga ok Vigolea': 'Additional',
 'Ereks saga Artuskappa': 'Additional',
 'Boy and Mantle': 'Additional',
 'Morte Arthur': 'Harley',
 "King Arthur's Death": 'Additional',
 'Samsons saga Fagra': 'Additional',
 'Lays of Marie de France': 'Harley',
 'Emare': 'Cotton',
 'Sir Gowghter': 'Royal',
 'Hanes Taliesin': 'Additional',
 'Havelok': 'Royal',
 'King Horn': 'Harley',
 'Pontus and Sidoine': 'Royal',
 'Guy of Warwick': 'Royal',
 'Fulk Fitz-Warin': 'Royal',
 'Tale of Gamelyn': 'Royal',
 'Robyn and Gandelyn': 'Sloane',
 'Robin Hood': 'Additional',
 'Miscellaneous Ballads': 'Additional',
 'Scottish Ballads': 'Additional',
 "Turpin's Chronicle": 'Royal',
 'Karolellus': 'Royal',
 'Philomena': 'Additional',
 'Aspremont': 'Royal',
 'Ogier le Danois': 'Royal',
 'Enfances Ogier': 'Harley',
 'Fierabras': 'Royal',
 'Quatre fils Aimon': 'Royal',
 'Simon de Pouille': 'Royal',
 'Gui de Bourgogne': 'Harley',
 'Battle of Roncevaux': 'Cotton',
 "Guillaume d'Orange": 'Royal',
 'Girard de Roussillon': 'Harley',
 'Doon de la Roche': 'Harley',
 'Reali di Francia': 'Additional',
 'Amys and Amylion': 'Harley',
 'Riccardetto': 'Additional',
 'Romance of the Peers of France': 'Additional',
 'Magus saga Jarls': 'Additional',
 'Mélusine': 'Royal',
 'Partonopeus de Blois': 'Additional',
 'Florence de Rome': 'Lansdowne',
 'The Chaste Duchess': 'Additional',
 'Floire et Blancheflor': 'Additional',
 'Filocolo': 'Harley',
 "Blanchandin et Orgueillose d'Amors": 'Additional',
 'Ipomedon': 'Harley',
 "Les deux Chevaliers, and Le dit de Guillaume d'Angleterre": 'Additional',
 'Sir Isumbras': 'Cotton',
 'Octavian the Emperor': 'Cotton',
 'King Robert of Sicily': 'Harley',
 'Sir Eglamour of Artois': 'Cotton',
 'The Diana of Montemayor': 'Additional',
 'Theseus de Cologne': 'Additional',
 'Petit Jean de Saintré': 'Cotton',
 'Floridam and Elluide': 'Cotton',
 "The Three Kings' Sons": 'Harley',
 'Uberto and Philomena': 'Additional',
 'Amadis de Gaula': 'Lansdowne',
 'Fiammetta': 'Harley',
 'Corbaccio': 'Harley',
 'Theagenes and Stelliana': 'Harley',
 'Aronus and Marina': 'Harley',
 'Tale of Antiochus': 'Harley',
 'Tale of Two Lovers': 'Royal',
 'Cassandra': 'Sloane',
 'Contes et Fabliaux': 'Additional',
 'Romances and Ballads': 'Additional',
 'Tales and Fables': 'Additional',
 'Two Romantic Tales': 'Additional',
 'Roman de la Rose': 'Royal',
 'Le Chemin de Vaillance': 'Royal',
 'Sydrac and Boctus': 'Royal',
 "Livre de l'Ordre de Chevalerie": 'Royal',
 'Titurel': 'Additional',
 'Life of Harold, King of England': 'Harley',
 'Richard Coeur-de-Lion': 'Additional',
 'Tinctoris, Compostella': 'Additional'}

In [28]:
from pyvis.network import Network

#-------------node size---------------
text_freq = df.groupby('title_index')['mss'].nunique()

min_size, max_size = 10, 30

node_sizes = ((text_freq - text_freq.min()) /
             (text_freq.max() - text_freq.min() + 1e-9) *
             (max_size - min_size) + min_size).to_dict()


#-------------node color---------------
from matplotlib import cm, colors

text_theme = df.drop_duplicates('title_index').set_index('title_index')['theme'].to_dict()
text_theme

themes = df['theme'].unique()
cmap = cm.get_cmap('tab20', len(themes))
theme_colors = {
    theme: colors.to_hex(cmap(i))
    for i, theme in enumerate(themes)
}


#-------------text color----------------
text_coll = df.drop_duplicates('title_index').set_index('title_index')['collection'].to_dict()

colls = df['collection'].unique()
cmap = cm.get_cmap('Dark2', len(themes))
coll_colors = {
    colls: colors.to_hex(cmap(i))
    for i, colls in enumerate(colls)
}

#----------------pyvis------------------
# notebook=True 在 jupyter 直接显示
net = Network(height='800px', width='100%', notebook=True)

for text in text_freq.index:
    theme = text_theme[text]
    coll= text_coll[text]
    net.add_node(
        text,
        label=text,
        font={"color":coll_colors[coll]},
        size=node_sizes[text],
        color=theme_colors[theme],
        title=f"{text}, Theme: {theme}",
        # group=coll,   # 👈关键

    )
for _, row in edge_df.iterrows():
    net.add_edge(
        row['source'],
        row['target'],
        value=row['weight']*5,
        color="gray",
        title=f"Shared MSS: {','.join(row['shared_mss'])}"
    )
    
# -------------LAYOUT--------------------
net.force_atlas_2based(
    gravity=-200,          # 整体节点拉开的力度，负值越大，节点分得越开
    central_gravity=0.05,  # 越小，节点越靠中心；越大，节点聚到中心
    spring_length=250,     # 弹簧长度，越大，节点间隔越远
    spring_strength=0.05,  # 弹簧刚度，控制边对节点靠近的作用力
    damping=0.4            # 收敛阻尼
)        
    
#-------------------SHOW---------------------
# 生成 HTML
path_html='../figs/text_in_mss_network.html'
net.show(path_html)

## ----------------add title---------------

# 自动在 body 开始处插入标题
title_text = "Texts Network on Shared Manuscripts colored by Theme"
with open(path_html, 'r', encoding='utf-8') as f:
    html_content = f.read()

# 在 <body> 标签后插入标题
html_content = html_content.replace(
    '<body>',
    f'<body>\n<h2 style="text-align:center">{title_text}</h2>'
)
# 保存回 HTML 文件
with open(path_html, 'w', encoding='utf-8') as f:
    f.write(html_content)

Warning: When  cdn_resources is 'local' jupyter notebook has issues displaying graphics on chrome/safari. Use cdn_resources='in_line' or cdn_resources='remote' if you have issues viewing graphics in a notebook.
../figs/text_in_mss_network.html

C:\Users\yeliu\AppData\Local\Temp\ipykernel_37132\3397188283.py:20: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = cm.get_cmap('tab20', len(themes))
C:\Users\yeliu\AppData\Local\Temp\ipykernel_37132\3397188283.py:31: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = cm.get_cmap('Dark2', len(themes))