In [1]:
import os, sys, importlib
sys.path.append(os.path.abspath(".."))
from utils import combine_tables
from utils.combine_tables import compile_combined_table

import json
import re

## appli:

### index table

In [2]:
## index_table(corrigé manuellement) => index_table_clean

path_index_table=r"../results\vol1\index_table_clean.json"
with open(path_index_table, 'r', encoding='utf-8')as f:
    index_table=json.load(f)
    print(len(index_table))
index_table

9

{'Royal': [{'name': 'Historia Regum Britanniae',
   'page': 227,
   'mss': '4. C. xi. ff. 222-249'},
  {'name': "Turpin's Chronicle",
   'page': 583,
   'mss': '4. C. xi. ff. 280-286 b'},
  {'name': 'Prophecy of Merlin Silvester',
   'page': 313,
   'mss': '5. F. xv. ff. 3 b'},
  {'name': 'Dares Phrygius', 'page': 17, 'mss': '6. C. viii. ff. 123-133 b'},
  {'name': 'Letters between Alexander and Dindimus',
   'page': 138,
   'mss': '6. E. iii. ff. 111 b-112 b'},
  {'name': 'Letters between Alexander and Dindimus',
   'page': 137,
   'mss': '7. A. i. ff. 68 b-69 b'},
  {'name': 'Alexandreis', 'page': 98, 'mss': '8. B. iv. ff. 19-71 b'},
  {'name': 'Prophecies of Merlin',
   'page': 297,
   'mss': '8. D. iii. ff. 160 b-163'},
  {'name': 'Guy of Warwick', 'page': 485, 'mss': '8. F. ix. ff. 105-159'},
  {'name': 'Prophecy on Scotland', 'page': 327, 'mss': '9. B. ix. ff. 2'},
  {'name': 'Dares Phrygius', 'page': 20, 'mss': '10. A. x. ff. 188-192 b'},
  {'name': 'Alexander the Great',
   'page': 112,
   'mss': '12. C. iv. ff. 138-170'},
  {'name': 'Prophecy', 'page': 316, 'mss': '12. C. xii. ff. 14-16 b'},
  {'name': 'Fulk Fitz-Warin', 'page': 501, 'mss': '12. C. xii. ff. 33-60 b'},
  {'name': 'Amya and Amylion', 'page': 674, 'mss': '12. C. xii. ff. 69-76'},
  {'name': 'Tale of Two Lovers', 'page': 801, 'mss': '12. C. xx. ff. 17-46'},
  {'name': 'Historia Trojana', 'page': 49, 'mss': '12. D. iii. ff. 38-143'},
  {'name': 'Story of Troy', 'page': 34, 'mss': '12. D. iii. ff. 152 b-158'},
  {'name': 'Alexander the Great', 'page': 106, 'mss': '13. A. i.'},
  {'name': 'Historia Regum Britanniae',
   'page': 237,
   'mss': '13. A. iii. ff. 1-133'},
  {'name': 'Prophecy of Merlin Silvester',
   'page': 315,
   'mss': '13. A. iii. ff. 135 b, 136'},
  {'name': 'Story of Troy',
   'page': 27,
   'mss': '13. A. iv. ff. 22 b-23 b, 76-81 b'},
  {'name': 'Alexander the Great', 'page': 118, 'mss': '13. A. v. ff. 2-23 b'},
  {'name': 'Dares Phrygius', 'page': 23, 'mss': '13. A. v. ff. 88 b-98 b'},
  {'name': 'Historia Regum Britanniae',
   'page': 237,
   'mss': '13. A. v. ff. 99-161 b'},
  {'name': 'Prophecy of the Tenth Sibyl',
   'page': 194,
   'mss': '13. A. xiv. ff. 244-247'},
  {'name': 'Karolellus', 'page': 594, 'mss': '13. A. xviii. ff. 136-149 b'},
  {'name': 'Roman de Brut', 'page': 264, 'mss': '13. A. xxi. ff. 40 b-113'},
  {'name': 'Havelok', 'page': 423, 'mss': '13. A. xxi. ff. 113-117 b'},
  {'name': 'Havelok', 'page': 940, 'mss': '13. A. xxi. ff. 113-117 b'},
  {'name': 'Historia Trojana', 'page': 50, 'mss': '13. C. xii. ff. 6-32 b'},
  {'name': 'Alexander the Great',
   'page': 122,
   'mss': '13. C. xii. ff. 82-109 b'},
  {'name': 'Historia Regum Britanniae',
   'page': 248,
   'mss': '13. D. i. ff. 175-212 b'},
  {'name': "Turpin's Chronicle",
   'page': 572,
   'mss': '13. D. i. ff. 212 b-222'},
  {'name': 'Historia Regum Britanniae',
   'page': 228,
   'mss': '13. D. ii. ff. 124-173 b'},
  {'name': 'Historia Regum Britanniae',
   'page': 229,
   'mss': '13. D. v. ff. 1-37 b'},
  {'name': 'Vita Merlini', 'page': 289, 'mss': '13. E. i. ff. 143-146'},
  {'name': 'Prophecies of Merlin Silvester',
   'page': 314,
   'mss': '13. E. ix. ff. 27'},
  {'name': 'Historia Regum Britannia',
   'page': 238,
   'mss': '14. C. i. ff. 80-137'},
  {'name': 'Apollonius of Tyre', 'page': 170, 'mss': '14. C. xi. ff. 80-83 b'},
  {'name': 'Le Chemin de Vaillance',
   'page': 895,
   'mss': '14. E. ii. ff. 1-293'},
  {'name': "Livre de l'Ordre de Chevalerie",
   'page': 922,
   'mss': '14. E. ii. ff. 337-353 b'},
  {'name': 'Saint Graal', 'page': 341, 'mss': '14. E. iii. ff. 3-88 b'},
  {'name': 'Lancelot du Lac', 'page': 354, 'mss': '14. E. iii. ff. 89-161 b'},
  {'name': 'Alexandreis', 'page': 94, 'mss': '15. A. x. ff. 2-89'},
  {'name': 'Dares Phrygius', 'page': 13, 'mss': '15. A. xxii. ff. 73-90'},
  {'name': 'Prophecy of the Tenth Sibyl',
   'page': 194,
   'mss': '15. A. xxii. ff. 110-115'},
  {'name': 'Dares Phrygius', 'page': 14, 'mss': '15. B. xi. ff. 57-66 b'},
  {'name': 'Prophecy of the Tenth Sibyl',
   'page': 193,
   'mss': '15. B. xi. ff. 67-69'},
  {'name': 'Alexander the Great',
   'page': 110,
   'mss': '15. C. vi. ff. 102 b-130 b'},
  {'name': 'Historia Trojana', 'page': 44, 'mss': '15. C. xvi. ff. 86-145'},
  {'name': 'Historia Regum Britannia',
   'page': 239,
   'mss': '15. C. xvi. ff. 146-183 b'},
  {'name': 'Prophecies of Merlin Silvester',
   'page': 313,
   'mss': '15. C. xvi. ff. 183 b, 184'},
  {'name': 'Perceforest', 'page': 377, 'mss': '15. E. v.'},
  {'name': 'Alexander the Great',
   'page': 129,
   'mss': '15. E. vi. ff. 4 b-24 b'},
  {'name': 'Simon de Pouille', 'page': 627, 'mss': '15. E. vi. ff. 25-42 b'},
  {'name': 'Aspremont', 'page': 598, 'mss': '15. E. vi. ff. 43-69 b'},
  {'name': 'Fierabras', 'page': 615, 'mss': '15. E. vi. ff. 70-85 b'},
  {'name': 'Ogier le Danois', 'page': 604, 'mss': '15. E. vi. ff. 86-154 b'},
  {'name': 'Quatre fils Aimon', 'page': 622, 'mss': '15. E. vi. ff. 155-206'},
  {'name': 'Pontus and Sidoine',
   'page': 469,
   'mss': '15. E. vi. ff. 207-226 b'},
  {'name': 'Guy of Warwick and Heraud of Ardennes',
   'page': 487,
   'mss': '15. E. vi. ff. 227-272'},
  {'name': 'Knight of the Swan', 'page': 708, 'mss': '15. E. vi. ff. 273-292'},
  {'name': 'Iliaca', 'page': 2, 'mss': '16. C. iv. A. B.'},
  {'name': 'Heroica', 'page': 1, 'mss': '16. C. xxiii. ff. 2-69 b'},
  {'name': 'Iliaca', 'page': 6, 'mss': '16. D. iii. A. B.'},
  {'name': 'Titus and Vespasian',
   'page': 176,
   'mss': '16. E. viii. ff. 73-102 b'},
  {'name': 'Voyage of Charlemagne to Jerusalem and Constantinople',
   'page': 625,
   'mss': '16. E. ff. 131-144 b'},
  {'name': 'Sydrac and Boctus', 'page': 914, 'mss': '16. F. v. ff. 1-113 b'},
  {'name': 'Historia Trojana', 'page': 54, 'mss': '16. F. ix.'},
  {'name': 'Quatre fils Aimon', 'page': 619, 'mss': '16. G. ii.'},
  {'name': 'Sir Gowghter', 'page': 419, 'mss': '17. B. xliii. ff. 116-131 b'},
  {'name': 'Tale of Gamelyn', 'page': 515, 'mss': '17. D. xv. ff. 66 b-79 b'},
  {'name': 'Recueil des Histoires de Troie', 'page': 64, 'mss': '17. E. ii.'},
  {'name': 'Mélusine', 'page': 690, 'mss': '18. B. ii.'},
  {'name': 'Tale of Gamelyn', 'page': 514, 'mss': '18. C. ii. ff. 56 b-67 b'},
  {'name': 'Troy Book', 'page': 81, 'mss': '18. D. ii. ff. 6-146'},
  {'name': 'Romance of Thebes', 'page': 90, 'mss': '18. D. ii. ff. 147 b-162'},
  {'name': 'Troy Book', 'page': 79, 'mss': '18. D. vi.'},
  {'name': 'Roman de la Rose', 'page': 885, 'mss': '19. A. xviii.'},
  {'name': 'Lancelot du Lac', 'page': 349, 'mss': '19. B. vii.'},
  {'name': 'Roman de la Rose', 'page': 888, 'mss': '19. B. xii. ff. 2-147 b'},
  {'name': 'Roman de la Rose', 'page': 874, 'mss': '19. B. xiii.'},
  {'name': 'Saint Graal', 'page': 342, 'mss': '19. C. vii.'},
  {'name': 'Lancelot du Lac', 'page': 345, 'mss': '19. C. viii.'},
  {'name': 'Alexander the Great', 'page': 123, 'mss': '19. D. i. ff. 1-46'},
  {'name': "La Vengeance d'Alexandre",
   'page': 143,
   'mss': '19. D. i. ff. 47-57'},
  {'name': 'Perceforest', 'page': 377, 'mss': '19. E. ii.'},
  {'name': 'Perceforest', 'page': 377, 'mss': '19. E. iii.'},
  {'name': 'Alexander the Great', 'page': 125, 'mss': '20. A. v.'},
  {'name': 'Roman de la Rose', 'page': 880, 'mss': '20. A. xvii.'},
  {'name': 'Lancelot du Lac', 'page': 349, 'mss': '20. B. xix.'},
  {'name': "Guillaume d'Orange", 'page': 654, 'mss': '20. B. xix.'},
  {'name': 'Alexander the Great', 'page': 128, 'mss': '20. B. xx.'},
  {'name': 'Cleriadus et Meliadice',
   'page': 383,
   'mss': '20. C. ii. ff. 1-209 b'},
  {'name': 'Apollonius of Tyre', 'page': 166, 'mss': '20. C. ii. ff. 210-236'},
  {'name': 'Lancelot du Lac', 'page': 350, 'mss': '20. C. vi.'},
  {'name': 'Tristram', 'page': 361, 'mss': '20. D. ii.'},
  {'name': 'Lancelot du Lac', 'page': 353, 'mss': '20. D. iii.'},
  {'name': 'Lancelot du Lac', 'page': 351, 'mss': '20. D. iv.'},
  {'name': 'Roman de la Rose', 'page': 889, 'mss': '20. D. vii.'},
  {'name': "Guillaume d'Orange", 'page': 632, 'mss': '20. D. xi.'}],
 'Cotton': [{'name': 'Prophecies of Merlin',
   'page': 299,
   'mss': 'Julius A. v. ff. 5, 53-57b, 177 b-179, and 180-181 b'},
  {'name': 'Gesta Regum Britannia',
   'page': 274,
   'mss': 'Julius D. xi. ff. 2-60'},
  {'name': 'Vita Merlini',
   'page': 289,
   'mss': 'Julius E. viii. ff. 12 b-17 b'},
  {'name': 'Troy Book', 'page': 75, 'mss': 'Augustus A. iv.'},
  {'name': 'Prophecies of Merlin',
   'page': 295,
   'mss': 'Tiberius A. ix. ff. 2-6'},
  {'name': 'Sir Eglamour of Artois',
   'page': 766,
   'mss': 'Caligula A. ii. ff. 5 b-13'},
  {'name': 'Octavian the Emperor',
   'page': 762,
   'mss': 'Caligula A. ii. ff. 22 b-35'},
  {'name': 'Sir Launfal', 'page': 416, 'mss': 'Caligula A. ii. ff. 35 b-42 b'},
  {'name': 'Lybeaus Desconus',
   'page': 400,
   'mss': 'Caligula A. ii. ff. 42 b-57'},
  {'name': 'Emare', 'page': 418, 'mss': 'Caligula A. ii. ff. 71-76 b'},
  {'name': 'Titus and Vespasian',
   'page': 180,
   'mss': 'Caligula A. ii. ff. 111-125'},
  {'name': 'Knight of the Swan',
   'page': 710,
   'mss': 'Caligula A. ii. ff. 125 b-129 b'},
  {'name': 'Sir Isumbras', 'page': 760, 'mss': 'Caligula A. ii. ff. 130-134'},
  {'name': "Lazamon's Brut",
   'page': 268,
   'mss': 'Caligula A. ix. ff. 3-194 b'},
  {'name': 'Prophecy of the Tenth Sibyl',
   'page': 195,
   'mss': 'Caligula A. x. ff. 200-204'},
  {'name': "Turpin's Chronicle",
   'page': 561,
   'mss': 'Caligula B. vii. ff. 192-203 b'},
  {'name': 'Prophecy of Merlin',
   'page': 303,
   'mss': 'Caligula B. vii. ff. 210-213'},
  {'name': 'Dares Phrygius',
   'page': 22,
   'mss': 'Caligula B. vii. ff. 214-218 b'},
  {'name': 'Prophecy of the Tenth Sibyl',
   'page': 193,
   'mss': 'Caligula B. vii. ff. 219, 220'},
  {'name': 'Prophecies of Merlin',
   'page': 296,
   'mss': 'Caligula B. vii. ff. 220 b-231 b'},
  {'name': 'Prophecies', 'page': 317, 'mss': 'Claudius E. viii. ff. 1 b, 23'},
  {'name': 'Prophecies of Merlin',
   'page': 297,
   'mss': 'Nero A. iv. ff. 63-76 b'},
  {'name': 'Sir Gawain and the Green Knight',
   'page': 387,
   'mss': 'Nero A. x. ff. 90 b-126'},
  {'name': "Turpin's Chronicle", 'page': 546, 'mss': 'Nero A. xi. ff. 8-63'},
  {'name': "Turpin's Chronicle", 'page': 950, 'mss': 'Nero A. xi. ff. 8-63'},
  {'name': 'Historia Regum Britanniae',
   'page': 230,
   'mss': 'Nero D. viii. ff. 3-63'},
  {'name': 'Alexander the Great',
   'page': 113,
   'mss': 'Nero D. viii. ff. 160-174 b'},
  {'name': 'Story of Albina and her Sisters',
   'page': 199,
   'mss': 'Nero D. viii. ff. 186, 187'},
  {'name': 'Petit Jean de Saintré',
   'page': 775,
   'mss': 'Nero D. ix. ff. 1-108'},
  {'name': 'Floridam and Elluide',
   'page': 779,
   'mss': 'Nero D. ix. ff. 109-115'},
  {'name': 'Ywain and Gawain', 'page': 392, 'mss': 'Galba E. ix. ff. 4-25'},
  {'name': "Merlin's Prophecy of the Six Kings",
   'page': 309,
   'mss': 'Galba E. ix. ff. 49, 50'},
  {'name': 'Historia Regum Britanniae',
   'page': 239,
   'mss': 'Galba E. xi. ff. 2-58 b'},
  {'name': 'Letters of Dindimus to Alexander the Great',
   'page': 136,
   'mss': 'Galba E. xi. ff. 98 b-101 b'},
  {'name': 'Alexander the Great',
   'page': 115,
   'mss': 'Galba E. xi. ff. 111-125'},
  {'name': "Lisamon's Brut", 'page': 271, 'mss': 'Otho C. xiii.'},
  {'name': 'Roman de Brut',
   'page': 259,
   'mss': 'Vitellius A. x. ff. 19-114 b'},
  {'name': 'Dares Phrygius', 'page': 15, 'mss': 'Vitellius A. xiii. ff. 90'},
  {'name': 'Marvels of India',
   'page': 134,
   'mss': 'Vitellius A. xv. ff. 109-133 b'},
  {'name': 'Dares Phrygius',
   'page': 18,
   'mss': 'Vitellius C. viii. ff. 5 b-6 b'},
  {'name': 'Floyras and Blanchefleur',
   'page': 716,
   'mss': 'Vitellius D. iii. ff. 6-8 b'},
  {'name': 'Thomas of Erceldoune',
   'page': 330,
   'mss': 'Vitellius E. x. ff. 240 b-243'},
  {'name': 'Ipomodon', 'page': 728, 'mss': 'Vespasian A. vii. ff. 37-104'},
  {'name': 'Brutus', 'page': 277, 'mss': 'Vespasian A. x. ff. 44 b-51'},
  {'name': "Turpin's Chronicle",
   'page': 576,
   'mss': 'Vespasian A. xiii. ff. 94-114 b'},
  {'name': 'Apollonius of Tyre',
   'page': 164,
   'mss': 'Vespasian A. xiii. ff. 132-147 b'},
  {'name': 'Historia Regum Britanniae',
   'page': 241,
   'mss': 'Vespasian A. xxiii. ff. 4-106 b'},
  {'name': 'Lanval', 'page': 415, 'mss': 'Vespasian B. xiv. ff. 1-8 b'},
  {'name': 'Fall of Troy',
   'page': 31,
   'mss': 'Vespasian B. xiv. ff. 18, 18 b'},
  {'name': 'Fall of Troy and Adventures of Æneas',
   'page': 33,
   'mss': 'Vespasian B. xxiii. Part III. ff. 118 b-122 b'},
  {'name': 'Dares Phrygius',
   'page': 12,
   'mss': 'Vespasian B. xxv. ff. 98 b-117'},
  {'name': 'Prophecy of the Tenth Sibyl',
   'page': 192,
   'mss': 'Vespasian B. xxv. ff. 117 b-123'},
  {'name': 'Guy of Warwick',
   'page': 492,
   'mss': 'Vespasian D. ix. ff. 40-43 b'},
  {'name': 'Two Prophecies',
   'page': 325,
   'mss': 'Vespasian D. xviii. ff. 125 b-127* b'},
  {'name': 'Vita Merlini',
   'page': 278,
   'mss': 'Vespasian E. iv. ff. 112 b-138 b'},
  {'name': 'Prophecy of the Tenth Sibyl',
   'page': 194,
   'mss': 'Vespasian E. iv. ff. 143-147'},
  {'name': 'Prophecies of Merlin, etc.',
   'page': 320,
   'mss': 'Vespasian E. vii. ff. 78-126, 129, 130'},
  {'name': 'Whole Prophecy of Scotland',
   'page': 337,
   'mss': 'Vespasian E. viii. ff. 16-29'},
  {'name': 'Historia Regum Britanniae',
   'page': 242,
   'mss': 'Vespasian E. x. ff. 271-368 b'},
  {'name': 'Story of Albina and her Sisters',
   'page': 200,
   'mss': 'Vespasian E. x. ff. 390 b-392'},
  {'name': 'Titus and Vespasian',
   'page': 185,
   'mss': 'Vespasian E. xvi. ff. 70-75 b'},
  {'name': 'Historia Regum Britanniae',
   'page': 243,
   'mss': 'Titus A. xviii. ff. 13-82'},
  {'name': "Turpin's Chronicle",
   'page': 578,
   'mss': 'Titus A. xix. ff. 24-43'},
  {'name': 'Vita Merlini', 'page': 290, 'mss': 'Titus A. xix. ff. 63-73 b'},
  {'name': 'Story of Albina and her Sisters',
   'page': 201,
   'mss': 'Titus A. xix. ff. 103'},
  {'name': 'Battle of Roncevaux',
   'page': 630,
   'mss': 'Titus A. xix. ff. 153-155'},
  {'name': 'Story of Troy and Adventures of Æneas',
   'page': 29,
   'mss': 'Titus A. xx. ff. 99-104'},
  {'name': 'Historia Regum Britanniae',
   'page': 244,
   'mss': 'Titus A. xxv. ff. 105-116 b'},
  {'name': 'Historia Regum Britanniae',
   'page': 231,
   'mss': 'Titus A. xxvii. ff. 1 b-87'},
  {'name': 'Historia Regum Britanniae', 'page': 203, 'mss': 'Titus C. xvii.'},
  {'name': 'Apollonius of Tyre',
   'page': 169,
   'mss': 'Titus D. iii. ff. 127-137 b'},
  {'name': 'Prophecy of the Tenth Sibyl',
   'page': 191,
   'mss': 'Titus D. iii. ff. 143-147 b'},
  {'name': 'Prophecy of Merlin',
   'page': 301,
   'mss': 'Titus D. vii. ff. 26-36'},
  {'name': 'Prophecies', 'page': 319, 'mss': 'Titus D. xix. ff. 118'},
  {'name': 'Prophecy of the Tenth Sibyl',
   'page': 193,
   'mss': 'Domitian xiii. ff. 104-107'},
  {'name': 'Prophecy of the Tenth Sibyl',
   'page': 195,
   'mss': 'Domitian xiii. ff. 132 b-134 b'},
  {'name': 'Fall of Troy', 'page': 30, 'mss': 'Cleopatra A. viii. ff. 56-58'},
  {'name': 'Brut y Brenhinoedd',
   'page': 255,
   'mss': 'Cleopatra B. v. ff. 1-108 b'},
  {'name': 'Dares Phrygius', 'page': 26, 'mss': 'Cleopatra B. v. ff. 222-250'},
  {'name': 'Prophecies of Merlin',
   'page': 310,
   'mss': 'Cleopatra C. iv. ff. 74-122'},
  {'name': 'Prophecy of Merlin',
   'page': 298,
   'mss': 'Cleopatra C. iv. ff. 55 b and 66-68 b'},
  {'name': 'Prophecy of the Lily, the Lion, and the Son of Man',
   'page': 318,
   'mss': 'Cleopatra D. iii. ff. 184'},
  {'name': 'Alexander the Great',
   'page': 114,
   'mss': 'Cleopatra D. v. ff. 165 b-183'},
  {'name': 'Story of Albina and her Sisters',
   'page': 200,
   'mss': 'Cleopatra D. viii. ff. 3 b-5'},
  {'name': 'Historia Regum Britanniae',
   'page': 249,
   'mss': 'Cleopatra D. viii. ff. 8-94'},
  {'name': 'Story of Albina and her Sisters',
   'page': 198,
   'mss': 'Cleopatra D. ix. ff. 67, 68'},
  {'name': 'Prophecies of Merlin',
   'page': 292,
   'mss': 'Faustina A. viii. ff. 109 b-116'},
  {'name': 'Meriadoc and Gawain',
   'page': 374,
   'mss': 'Faustina B. vi. ff. 2-40 b'},
  {'name': 'Prophecies', 'page': 319, 'mss': 'Faustina B. ix. ff. 241 b, 242'},
  {'name': 'Prophecies of Merlin Silvester',
   'page': 315,
   'mss': 'Cotton Appendix iv. ff. 102 b'},
  {'name': 'Romance of Thebes',
   'page': 91,
   'mss': 'Cotton Appendix xxvii. ff. 11-61; formerly ff. 106-130 b, and xxxix. ff. 80-103 b'},
  {'name': 'Four Prophecies', 'page': 324, 'mss': 'Cotton Roll ii. 23'}],
 'Harley': [{'name': 'Tristram', 'page': 358, 'mss': 'Harley 49'},
  {'name': 'Historia Trojana', 'page': 52, 'mss': 'Harley 51. ff. 3-105 b'},
  {'name': "Turpin's Chronicle",
   'page': 574,
   'mss': 'Harley 108. ff. 4 b-31 b'},
  {'name': 'Historia Trojana', 'page': 47, 'mss': 'Harley 176'},
  {'name': 'Historia Regum Britanniae',
   'page': 222,
   'mss': 'Harley 225. ff. 3-78'},
  {'name': "Turpin's Chronicle",
   'page': 587,
   'mss': 'Harley 273. ff. 86-102 b'},
  {'name': "The Three Kings' Sons",
   'page': 782,
   'mss': 'Harley 326. ff. 8-123 b'},
  {'name': 'Romance of Troy', 'page': 84, 'mss': 'Harley 525. ff. 1-34 b'},
  {'name': 'King Robert of Sicily',
   'page': 765,
   'mss': 'Harley 525. ff. 35-43 b'},
  {'name': 'Gui de Bourgogne', 'page': 630, 'mss': 'Harley 527. ff. 1-32'},
  {'name': 'Alexander the Great',
   'page': 113,
   'mss': 'Harley 527. ff. 47-56 b'},
  {'name': 'King Horn', 'page': 468, 'mss': 'Harley 527. ff. 59-73 b'},
  {'name': 'Historia Regum Britanniae',
   'page': 226,
   'mss': 'Harley 536. ff. 58-61'},
  {'name': 'Political Prophecies',
   'page': 326,
   'mss': 'Harley 559. ff. 1-13, 31-35, 39-48'},
  {'name': 'Dares Phrygius', 'page': 20, 'mss': 'Harley 641. ff. 1-8'},
  {'name': 'Vita Merlini', 'page': 288, 'mss': 'Harley 655. ff. 200 b-204 b'},
  {'name': "Merlin's Prophecy of the Six Kings",
   'page': 309,
   'mss': 'Harley 746. ff. 1 b-3'},
  {'name': 'Prophecy of Merlin',
   'page': 302,
   'mss': 'Harley 838. ff. 92-93 b'},
  {'name': 'Story of Albina and her Sisters',
   'page': 201,
   'mss': 'Harley 941. ff. 1-3'},
  {'name': 'Lays of Marie de France',
   'page': 407,
   'mss': 'Harley 978. ff. 118-160'},
  {'name': 'Prophecy of the Lily, the Lion, and the Son of Man',
   'page': 318,
   'mss': 'Harley 1008. ff. 81'},
  {'name': 'Sydrac and Boctus', 'page': 912, 'mss': 'Harley 1121. ff. 1-140'},
  {'name': 'Troilus and Cryseyde',
   'page': 73,
   'mss': 'Harley 1239. ff. 1-62 b'},
  {'name': "Guillaume d'Orange", 'page': 660, 'mss': 'Harley 1321'},
  {'name': 'Chanson de Brut', 'page': 272, 'mss': 'Harley 1605. Art. I.'},
  {'name': 'Prophecies de Merlin', 'page': 373, 'mss': 'Harley 1629'},
  {'name': 'King Robert of Sicily',
   'page': 765,
   'mss': 'Harley 1701. ff. 92-95'},
  {'name': 'Prophecies of Merlin and others',
   'page': 312,
   'mss': 'Harley 1717. ff. 249 b-250 b'},
  {'name': 'Tale of Gamelyn', 'page': 513, 'mss': 'Harley 1758. ff. 48-55'},
  {'name': 'Tale of Two Lovers',
   'page': 799,
   'mss': 'Harley 1883. ff. 119-135 b'},
  {'name': 'Ipomedon', 'page': 755, 'mss': 'Harley 2252. ff. 54-84'},
  {'name': 'Morte Arthur', 'page': 405, 'mss': 'Harley 2252. ff. 86-133 b'},
  {'name': 'Six Fabliaux',
   'page': 813,
   'mss': 'Harley 2253. ff. 67 b, 107 b, 110, 115 b, 118, 122 b'},
  {'name': 'King Horn', 'page': 447, 'mss': 'Harley 2253. ff. 83-92 b'},
  {'name': 'Prophecy of Thomas of Erceldoune',
   'page': 328,
   'mss': 'Harley 2253. ff. 127, col. 2'},
  {'name': 'Troilus and Cryseyde', 'page': 70, 'mss': 'Harley 2280'},
  {'name': "Turpin's Chronicle",
   'page': 582,
   'mss': 'Harley 2361. ff. 138-139 b'},
  {'name': 'Story of Albina and her Sisters',
   'page': 202,
   'mss': 'Harley 2386. ff. 65 b-67'},
  {'name': 'Amys and Amylion', 'page': 677, 'mss': 'Harley 2386. ff. 131-138'},
  {'name': 'Troilus and Cryseyde', 'page': 73, 'mss': 'Harley 2392'},

In [ ]:
   
importlib.reload(combine_tables)
from utils import combine_tables
from utils.combine_tables import complie_index_table

index_table_clean=complie_index_table(index_table)

print(index_table_clean.keys())
with open("../results/vol1/vol1-index_table_clean.json","w", encoding='utf-8')as f:
    json.dump(index_table_clean, f, indent=2, ensure_ascii=False)
index_table_clean

dict_keys(['historia regum britanniae', "turpin's chronicle", 'prophecy of merlin silvester', 'dares phrygius', 'letters between alexander and dindimus', 'alexandreis', 'prophecies of merlin', 'guy of warwick', 'prophecy on scotland', 'alexander the great', 'prophecy', 'fulk fitz-warin', 'amya and amylion', 'tale of two lovers', 'historia trojana', 'story of troy', 'prophecy of the tenth sibyl', 'karolellus', 'roman de brut', 'havelok', 'vita merlini', 'prophecies of merlin silvester', 'historia regum britannia', 'apollonius of tyre', 'le chemin de vaillance', "livre de l'ordre de chevalerie", 'saint graal', 'lancelot du lac', 'perceforest', 'simon de pouille', 'aspremont', 'fierabras', 'ogier le danois', 'quatre fils aimon', 'pontus and sidoine', 'guy of warwick and heraud of ardennes', 'knight of the swan', 'iliaca', 'heroica', 'titus and vespasian', 'voyage of charlemagne to jerusalem and constantinople', 'sydrac and boctus', 'sir gowghter', 'tale of gamelyn', 'recueil des histoires de troie', 'mélusine', 'troy book', 'romance of thebes', 'roman de la rose', "la vengeance d'alexandre", "guillaume d'orange", 'cleriadus et meliadice', 'tristram', 'gesta regum britannia', 'sir eglamour of artois', 'octavian the emperor', 'sir launfal', 'lybeaus desconus', 'emare', 'sir isumbras', "lazamon's brut", 'prophecy of merlin', 'prophecies', 'sir gawain and the green knight', 'story of albina and her sisters', 'petit jean de saintré', 'floridam and elluide', 'ywain and gawain', "merlin's prophecy of the six kings", 'letters of dindimus to alexander the great', "lisamon's brut", 'marvels of india', 'floyras and blanchefleur', 'thomas of erceldoune', 'ipomodon', 'brutus', 'lanval', 'fall of troy', 'fall of troy and adventures of æneas', 'two prophecies', 'prophecies of merlin, etc.', 'whole prophecy of scotland', 'battle of roncevaux', 'story of troy and adventures of æneas', 'brut y brenhinoedd', 'prophecy of the lily, the lion, and the son of man', 'meriadoc and gawain', 'four prophecies', "the three kings' sons", 'romance of troy', 'king robert of sicily', 'gui de bourgogne', 'king horn', 'political prophecies', 'lays of marie de france', 'troilus and cryseyde', 'chanson de brut', 'prophecies de merlin', 'prophecies of merlin and others', 'ipomedon', 'morte arthur', 'six fabliaux', 'prophecy of thomas of erceldoune', 'amys and amylion', 'letter of dindimus to alexander the great', 'aronus and marina', 'filocolo', 'dictys cretensis', 'corbaccio', 'fiammetta', 'life of harold, king of england', 'sir orpheo', 'tale of antiochus', 'florimont', 'voeux du paon', "l'ordène de chevalerie", 'girard de roussillon', 'doon de la roche', 'enfances ogier', 'roman de troie', 'richard cœur-de-lion', 'prophecies taken from geoffrey of monmouth and others', 'merlin', 'theagenes and stelliana', 'kings of britain', 'florence de rome', 'abridgement of historia trojana', 'chanson de roland', 'amadis de gaula', "chanson d'aspremont", 'prophecies of merlin, gildas, and thomas of ercildoune', 'birth of merlin', 'treatise on the brahmins', 'history of troy', 'cassandra', 'life of robin hood', 'collection of prophecies', 'robyn and gandelyn', 'five romantic tales', 'ívents saga', 'eight romantic tales', 'parcevals saga and valvers þáttr', 'ereks saga artuskappa', 'möttuls saga', 'life of virgilius', 'magus saga jarls', 'partalópa saga', 'seven romantic tales', 'samsons saga fagra', 'trójumanna saga', 'two romantic tales', 'three romantic tales', 'saga of ajax frækni', 'merlínus spá', 'juglet', 'romance of jason', 'artus de bretagne', 'fioccolo', 'riccardetto', 'romance of the peers of france', 'rimur of remund', 'rimur from trójumanna saga', 'collection of anecdotes', 'gabons saga ok vigolea', 'valentine and orson and tales', 'ten romantic tales', 'patient griselda', 'argenis', 'merlinus spá', 'alexander saga', 'uberto and philomena', 'tinctoris, compostella', 'meliadus', "roman d'eneas", 'hanes taliesin', 'brut gruffydd ap arthur', 'peredur ab efrawc', 'extracts from brut y brenhinoedd', 'isarles y ffynnawn', 'contes et fabliaux', 'partonopeus de blois', "blanchandin et orgueillose d'amors", 'floire et blancheflor', 'brut tyailio', "les deux chevaliers, and le dit de guillaume d'angleterre", "roman d'athis et profilas", 'voeux du paon and restor du paon', 'theseus de cologne', 'the diana of montemayor', 'amis and amylion', 'wigalois', 'iwein', 'may colvin', 'philomena', 'filostrato', 'the king of tars and the soudan of damas', 'scottish ballads', 'reali di francia', 'guiron le courtois', 'tales and fables', 'nine romantic tales', 'story of sigurgaror', 'fertrams saga', 'the chaste duchess', 'romances and ballads', 'robin hood', 'sir lancelot of dulake', 'miscellaneous ballads', 'the grene knight, turke and gowin, the marriage of sir gawaine', 'sir lambewell', "king arthur's death", 'guye and amarant', 'three ballads of forest life', 'guy and phillis', 'robin hood ballad', 'boy and mantle', 'libius disconius', 'guy and colebrande', 'two ballads relating to adam bell', 'a propecye', 'king humber', "robin hood's garland", 'ballads of scotland', 'titurel', 'two charlemagne romances', 'richard coeur-de-lion', 'ipomedon and prothesilaus'])

{'historia regum britanniae': [{'collection': 'royal',
   'mss_ff': '4. c. xi. ff. 222-249',
   'mss': '4. c. xi.',
   'ff': 'ff. 222-249',
   'page': 227},
  {'collection': 'royal',
   'mss_ff': '13. a. iii. ff. 1-133',
   'mss': '13. a. iii.',
   'ff': 'ff. 1-133',
   'page': 237},
  {'collection': 'royal',
   'mss_ff': '13. a. v. ff. 99-161 b',
   'mss': '13. a. v.',
   'ff': 'ff. 99-161 b',
   'page': 237},
  {'collection': 'royal',
   'mss_ff': '13. d. i. ff. 175-212 b',
   'mss': '13. d. i.',
   'ff': 'ff. 175-212 b',
   'page': 248},
  {'collection': 'royal',
   'mss_ff': '13. d. ii. ff. 124-173 b',
   'mss': '13. d. ii.',
   'ff': 'ff. 124-173 b',
   'page': 228},
  {'collection': 'royal',
   'mss_ff': '13. d. v. ff. 1-37 b',
   'mss': '13. d. v.',
   'ff': 'ff. 1-37 b',
   'page': 229},
  {'collection': 'cotton',
   'mss_ff': 'nero d. viii. ff. 3-63',
   'mss': 'nero d. viii.',
   'ff': 'ff. 3-63',
   'page': 230},
  {'collection': 'cotton',
   'mss_ff': 'galba e. xi. ff. 2-58 b',
   'mss': 'galba e. xi.',
   'ff': 'ff. 2-58 b',
   'page': 239},
  {'collection': 'cotton',
   'mss_ff': 'vespasian a. xxiii. ff. 4-106 b',
   'mss': 'vespasian a. xxiii.',
   'ff': 'ff. 4-106 b',
   'page': 241},
  {'collection': 'cotton',
   'mss_ff': 'vespasian e. x. ff. 271-368 b',
   'mss': 'vespasian e. x.',
   'ff': 'ff. 271-368 b',
   'page': 242},
  {'collection': 'cotton',
   'mss_ff': 'titus a. xviii. ff. 13-82',
   'mss': 'titus a. xviii.',
   'ff': 'ff. 13-82',
   'page': 243},
  {'collection': 'cotton',
   'mss_ff': 'titus a. xxv. ff. 105-116 b',
   'mss': 'titus a. xxv.',
   'ff': 'ff. 105-116 b',
   'page': 244},
  {'collection': 'cotton',
   'mss_ff': 'titus a. xxvii. ff. 1 b-87',
   'mss': 'titus a. xxvii.',
   'ff': 'ff. 1 b-87',
   'page': 231},
  {'collection': 'cotton',
   'mss_ff': 'titus c. xvii.',
   'mss': 'titus c. xvii.',
   'ff': None,
   'page': 203},
  {'collection': 'cotton',
   'mss_ff': 'cleopatra d. viii. ff. 8-94',
   'mss': 'cleopatra d. viii.',
   'ff': 'ff. 8-94',
   'page': 249},
  {'collection': 'harley',
   'mss_ff': 'harley 225. ff. 3-78',
   'mss': 'harley 225.',
   'ff': 'ff. 3-78',
   'page': 222},
  {'collection': 'harley',
   'mss_ff': 'harley 536. ff. 58-61',
   'mss': 'harley 536.',
   'ff': 'ff. 58-61',
   'page': 226},
  {'collection': 'harley',
   'mss_ff': 'harley 3773. ff. 7-57',
   'mss': 'harley 3773.',
   'ff': 'ff. 7-57',
   'page': 223},
  {'collection': 'harley',
   'mss_ff': 'harley 4003. ff. 81-141 b',
   'mss': 'harley 4003.',
   'ff': 'ff. 81-141 b',
   'page': 244},
  {'collection': 'harley',
   'mss_ff': 'harley 4123. ff. 2-49 b',
   'mss': 'harley 4123.',
   'ff': 'ff. 2-49 b',
   'page': 236},
  {'collection': 'harley',
   'mss_ff': 'harley 5115. ff. 87-150',
   'mss': 'harley 5115.',
   'ff': 'ff. 87-150',
   'page': 245},
  {'collection': 'harley',
   'mss_ff': 'harley 6358. ff. 2-58 b',
   'mss': 'harley 6358.',
   'ff': 'ff. 2-58 b',
   'page': 235},
  {'collection': 'lansdowne',
   'mss_ff': 'lansdowne 732. ff. 1-68 b',
   'mss': 'lansdowne 732.',
   'ff': 'ff. 1-68 b',
   'page': 233},
  {'collection': 'arundel',
   'mss_ff': 'arundel 10',
   'mss': 'arundel 10',
   'ff': None,
   'page': 224},
  {'collection': 'arundel',
   'mss_ff': 'arundel 237',
   'mss': 'arundel 237',
   'ff': None,
   'page': 241},
  {'collection': 'arundel',
   'mss_ff': 'arundel 319. ff. 16-97 b',
   'mss': 'arundel 319.',
   'ff': 'ff. 16-97 b',
   'page': 232},
  {'collection': 'arundel',
   'mss_ff': 'arundel 326. ff. 63-122 b',
   'mss': 'arundel 326.',
   'ff': 'ff. 63-122 b',
   'page': 246},
  {'collection': 'arundel',
   'mss_ff': 'arundel 403',
   'mss': 'arundel 403',
   'ff': None,
   'page': 225},
  {'collection': 'arundel',
   'mss_ff': 'arundel 409. ff. 54-77',
   'mss': 'arundel 409.',
   'ff': 'ff. 54-77',
   'page': 233},
  {'collection': 'sloane',
   'mss_ff': 'sloane 289. ff. 120-133',
   'mss': 'sloane 289.',
   'ff': 'ff. 120-133',
   'page': 250},
  {'collection': 'additional',
   'mss_ff': 'add. 11,702. ff. 11-88',
   'mss': 'add. 11,702.',
   'ff': 'ff. 11-88',
   'page': 247},
  {'collection': 'additional',
   'mss_ff': 'add. 15,732',
   'mss': 'add. 15,732',
   'ff': None,
   'page': 234}],
 "turpin's chronicle": [{'collection': 'royal',
   'mss_ff': '4. c. xi. ff. 280-286 b',
   'mss': '4. c. xi.',
   'ff': 'ff. 280-286 b',
   'page': 583},
  {'collection': 'royal',
   'mss_ff': '13. d. i. ff. 212 b-222',
   'mss': '13. d. i.',
   'ff': 'ff. 212 b-222',
   'page': 572},
  {'collection': 'cotton',
   'mss_ff': 'caligula b. vii. ff. 192-203 b',
   'mss': 'caligula b. vii.',
   'ff': 'ff. 192-203 b',
   'page': 561},
  {'collection': 'cotton',
   'mss_ff': 'nero a. xi. ff. 8-63',
   'mss': 'nero a. xi.',
   'ff': 'ff. 8-63',
   'page': 546},
  {'collection': 'cotton',
   'mss_ff': 'nero a. xi. ff. 8-63',
   'mss': 'nero a. xi.',
   'ff': 'ff. 8-63',
   'page': 950},
  {'collection': 'cotton',
   'mss_ff': 'vespasian a. xiii. ff. 94-114 b',
   'mss': 'vespasian a. xiii.',
   'ff': 'ff. 94-114 b',
   'page': 576},
  {'collection': 'cotton',
   'mss_ff': 'titus a. xix. ff. 24-43',
   'mss': 'titus a. xix.',
   'ff': 'ff. 24-43',
   'page': 578},
  {'collection': 'harley',
   'mss_ff': 'harley 108. ff. 4 b-31 b',
   'mss': 'harley 108.',
   'ff': 'ff. 4 b-31 b',
   'page': 574},
  {'collection': 'harley',
   'mss_ff': 'harley 273. ff. 86-102 b',
   'mss': 'harley 273.',
   'ff': 'ff. 86-102 b',
   'page': 587},
  {'collection': 'harley',
   'mss_ff': 'harley 2361. ff. 138-139 b',
   'mss': 'harley 2361.',
   'ff': 'ff. 138-139 b',
   'page': 582},
  {'collection': 'harley',
   'mss_ff': 'harley 2500. ff. 139-155',
   'mss': 'harley 2500.',
   'ff': 'ff. 139-155',
   'page': 581},
  {'collection': 'harley',
   'mss_ff': 'harley 3043. ff. 17-31',
   'mss': 'harley 3043.',
   'ff': 'ff. 17-31',
   'page': 577},
  {'collection': 'harley',
   'mss_ff': 'harley 6358. ff. 60-83',
   'mss': 'harley 6358.',
   'ff': 'ff. 60-83',
   'page': 560},
  {'collection': 'arundel',
   'mss_ff': 'arundel 220. ff. 284-298 b',
   'mss': 'arundel 220.',
   'ff': 'ff. 284-298 b',
   'page': 589},
  {'collection': 'additional',
   'mss_ff': 'add. 6924. ff. 297-303',
   'mss': 'add. 6924.',
   'ff': 'ff. 297-303',
   'page': 583},
  {'collection': 'additional',
   'mss_ff': 'add. 12,213. ff. 1-184 b',
   'mss': 'add. 12,213.',
   'ff': 'ff. 1-184 b',
   'page': 562},
  {'collection': 'additional',
   'mss_ff': 'add. 17,920. ff. 6 b-19 b',
   'mss': 'add. 17,920.',
   'ff': 'ff. 6 b-19 b',
   'page': 592},
  {'collection': 'additional',
   'mss_ff': 'add. 19,513. ff. 141-163',
   'mss': 'add. 19,513.',
   'ff': 'ff. 141-163',
   'page': 573}],
 'prophecy of merlin silvester': [{'collection': 'royal',
   'mss_ff': '5. f. xv. ff. 3 b',
   'mss': '5. f. xv.',
   'ff': 'ff. 3 b',
   'page': 313},
  {'collection': 'royal',
   'mss_ff': '13. a. iii. ff. 135 b, 136',
   'mss': '13. a. iii.',
   'ff': 'ff. 135 b, 136',
   'page': 315}],
 'dares phrygius': [{'collection': 'royal',
   'mss_ff': '6. c. viii. ff. 123-133 b',
   'mss': '6. c. viii.',
   'ff': 'ff. 123-133 b',
   'page': 17},
  {'collection': 'royal',
   'mss_ff': '10. a. x. ff. 188-192 b',
   'mss': '10. a. x.',
   'ff': 'ff. 188-192 b',
   'page': 20},
  {'collection': 'royal',
   'mss_ff': '13. a. v. ff. 88 b-98 b',
   'mss': '13. a. v.',
   'ff': 'ff. 88 b-98 b',
   'page': 23},
  {'collection': 'royal',
   'mss_ff': '15. a. xxii. ff. 73-90',
   'mss': '15. a. xxii.',
   'ff': 'ff. 73-90',
   'page': 13},
  {'collection': 'royal',
   'mss_ff': '15. b. xi. ff. 57-66 b',
   'mss': '15. b. xi.',
   'ff': 'ff. 57-66 b',
   'page': 14},
  {'collection': 'cotton',
   'mss_ff': 'caligula b. vii. ff. 214-218 b',
   'mss': 'caligula b. vii.',
   'ff': 'ff. 214-218 b',
   'page': 22},
  {'collection': 'cotton',
   'mss_ff': 'vitellius a. xiii. ff. 90',
   'mss': 'vitellius a. xiii.',
   'ff': 'ff. 90',
   'page': 15},
  {'collection': 'cotton',
   'mss_ff': 'vitellius c. viii. ff. 5 b-6 b',
   'mss': 'vitellius c. viii.',
   'ff': 'ff. 5 b-6 b',
   'page': 18},
  {'collection': 'cotton',
   'mss_ff': 'vespasian b. xxv. ff. 98 b-117',
   'mss': 'vespasian b. xxv.',
   'ff': 'ff. 98 b-117',
   'page': 12},
  {'collection': 'cotton',
   'mss_ff': 'cleopatra b. v. ff. 222-250',
   'mss': 'cleopatra b. v.',
   'ff': 'ff. 222-250',
   'page': 26},
  {'collection': 'harley',
   'mss_ff': 'harley 641. ff. 1-8',
   'mss': 'harley 641.',
   'ff': 'ff. 1-8',
   'page': 20},
  {'collection': 'burney',
   'mss_ff': 'burney 216. ff. 89-93 b',
   'mss': 'burney 216.',
   'ff': 'ff. 89-93 b',
   'page': 16},
  {'collection': 'burney',
   'mss_ff': 'burney 280. ff. 20 b-38 b',
   'mss': 'burney 280.',
   'ff': 'ff. 20 b-38 b',
   'page': 21},
  {'collection': 'sloane',
   'mss_ff': 'sloane 1619 ff. 29-37 b',
   'mss': 'sloane 1619',
   'ff': 'ff. 29-37 b',
   'page': 19},
  {'collection': 'additional',
   'mss_ff': 'add. 10,094. ff. 1-14 b',
   'mss': 'add. 10,094.',
   'ff': 'ff. 1-14 b',
   'page': 24},
  {'collection': 'additional',
   'mss_ff': 'add. 15,042',
   'mss': 'add. 15,042',
   'ff': None,
   'page': 25},
  {'collection': 'additional',
   'mss_ff': 'add. 19,709. ff. 1-7',
   'mss': 'add. 19,709.',
   'ff': 'ff. 1-7',
   'page': 26}],
 'letters between alexander and dindimus': [{'collection': 'royal',
   'mss_ff': '6. e. iii. ff. 111 b-112 b',
   'mss': '6. e. iii.',
   'ff': 'ff. 111 b-112 b',
   'page': 138},
  {'collection': 'royal',
   'mss_ff': '7. a. i. ff. 68 b-69 b',
   'mss': '7. a. i.',
   'ff': 'ff. 68 b-69 b',
   'page': 137}],
 'alexandreis': [{'collection': 'royal',
   'mss_ff': '8. b. iv. ff. 19-71 b',
   'mss': '8. b. iv.',
   'ff': 'ff. 19-71 b',
   'page': 98},
  {'collection': 'royal',
   'mss_ff': '15. a. x. ff. 2-89',
   'mss': '15. a. x.',
   'ff': 'ff. 2-89',
   'page': 94},
  {'collection': 'harley',
   'mss_ff': 'harley 4745',
   'mss': 'harley 4745',
   'ff': None,
   'page': 103},
  {'collection': 'harley',
   'mss_ff': 'harley 5437',
   'mss': 'harley 5437',
   'ff': None,
   'page': 103},
  {'collection': 'burney',
   'mss_ff': 'burney 312',
   'mss': 'burney 312',
   'ff': None,
   'page': 101},
  {'collection': 'additional',
   'mss_ff': 'add. 17,084',
   'mss': 'add. 17,084',
   'ff': None,
   'page': 141},
  {'collection': 'additional',
   'mss_ff': 'add. 18,217',
   'mss': 'add. 18,217',
   'ff': None,
   'page': 99},
  {'collection': 'additional',
   'mss_ff': 'add. 22,821',
   'mss': 'add. 22,821',
   'ff': None,
   'page': 96}],
 'prophecies of merlin': [{'collection': 'royal',
   'mss_ff': '8. d. iii. ff. 160 b-163',
   'mss': '8. d. iii.',
   'ff': 'ff. 160 b-163',
   'page': 297},
  {'collection': 'cotton',
   'mss_ff': 'julius a. v. ff. 5, 53-57b, 177 b-179, and 180-181 b',
   'mss': 'julius a. v.',
   'ff': 'ff. 5, 53-57b, 177 b-179, and 180-181 b',
   'page': 299},
  {'collection': 'cotton',
   'mss_ff': 'tiberius a. ix. ff. 2-6',
   'mss': 'tiberius a. ix.',
   'ff': 'ff. 2-6',
   'page': 295},
  {'collection': 'cotton',
   'mss_ff': 'caligula b. vii. ff. 220 b-231 b',
   'mss': 'caligula b. vii.',
   'ff': 'ff. 220 b-231 b',
   'page': 296},
  {'collection': 'cotton',
   'mss_ff': 'nero a. iv. ff. 63-76 b',
   'mss': 'nero a. iv.',
   'ff': 'ff. 63-76 b',
   'page': 297},
  {'collection': 'cotton',
   'mss_ff': 'cleopatra c. iv. ff. 74-122',
   'mss': 'cleopatra c. iv.',
   'ff': 'ff. 74-122',
   'page': 310},
  {'collection': 'cotton',
   'mss_ff': 'faustina a. viii. ff. 109 b-116',
   'mss': 'faustina a. viii.',
   'ff': 'ff. 109 b-116',
   'page': 292},
  {'collection': 'arundel',
   'mss_ff': 'arundel 66. ff. 267-268 b and 291 b',
   'mss': 'arundel 66.',
   'ff': 'ff. 267-268 b and 291 b',
   'page': 301},
  {'collection': 'additional',
   'mss_ff': 'add. 6924. ff. 73-124 and 164-',
   'mss': 'add. 6924.',
   'ff': 'ff. 73-124 and 164-',
   'page': 304}],
 'guy of warwick': [{'collection': 'royal',
   'mss_ff': '8. f. ix. ff. 105-159',
   'mss': '8. f. ix.',
   'ff': 'ff. 105-159',
   'page': 485},
  {'collection': 'cotton',
   'mss_ff': 'vespasian d. ix. ff. 40-43 b',
   'mss': 'vespasian d. ix.',
   'ff': 'ff. 40-43 b',
   'page': 492},
  {'collection': 'harley',
   'mss_ff': 'harley 3775. ff. 15-26 b',
   'mss': 'harley 3775.',
   'ff': 'ff. 15-26 b',
   'page': 471},
  {'collection': 'harley',
   'mss_ff': 'harley 5243',
   'mss': 'harley 5243',
   'ff': None,
   'page': 497},
  {'collection': 'harley',
   'mss_ff': 'harley 7333. ff. 33-35 b',
   'mss': 'harley 7333.',
   'ff': 'ff. 33-35 b',
   'page': 494},
  {'collection': 'lansdowne',
   'mss_ff': 'lansdowne 699. ff. 18 b-27 b',
   'mss': 'lansdowne 699.',
   'ff': 'ff. 18 b-27 b',
   'page': 496},
  {'collection': 'sloane',
   'mss_ff': 'sloane 1044. ff. 625',
   'mss': 'sloane 1044.',
   'ff': 'ff. 625',
   'page': 489},
  {'collection': 'additional',
   'mss_ff': 'add. 14,408. ff. 74-77',
   'mss': 'add. 14,408.',
   'ff': 'ff. 74-77',
   'page': 490}],
 'prophecy on scotland': [{'collection': 'royal',
   'mss_ff': '9. b. ix. ff. 2',
   'mss': '9. b. ix.',
   'ff': 'ff. 2',
   'page': 327}],
 'alexander the great': [{'collection': 'royal',
   'mss_ff': '12. c. iv. ff. 138-170',
   'mss': '12. c. iv.',
   'ff': 'ff. 138-170',
   'page': 112},
  {'collection': 'royal',
   'mss_ff': '13. a. i.',
   'mss': '13. a. i.',
   'ff': None,
   'page': 106},
  {'collection': 'royal',
   'mss_ff': '13. a. v. ff. 2-23 b',
   'mss': '13. a. v.',
   'ff': 'ff. 2-23 b',
   'page': 118},
  {'collection': 'royal',
   'mss_ff': '13. c. xii. ff. 82-109 b',
   'mss': '13. c. xii.',
   'ff': 'ff. 82-109 b',
   'page': 122},
  {'collection': 'royal',
   'mss_ff': '15. c. vi. ff. 102 b-130 b',
   'mss': '15. c. vi.',
   'ff': 'ff. 102 b-130 b',
   'page': 110},
  {'collection': 'royal',
   'mss_ff': '15. e. vi. ff. 4 b-24 b',
   'mss': '15. e. vi.',
   'ff': 'ff. 4 b-24 b',
   'page': 129},
  {'collection': 'royal',
   'mss_ff': '19. d. i. ff. 1-46',
   'mss': '19. d. i.',
   'ff': 'ff. 1-46',
   'page': 123},
  {'collection': 'royal',
   'mss_ff': '20. a. v.',
   'mss': '20. a. v.',
   'ff': None,
   'page': 125},
  {'collection': 'royal',
   'mss_ff': '20. b. xx.',
   'mss': '20. b. xx.',
   'ff': None,
   'page': 128},
  {'collection': 'cotton',
   'mss_ff': 'nero d. viii. ff. 160-174 b',
   'mss': 'nero d. viii.',
   'ff': 'ff. 160-174 b',
   'page': 113},
  {'collection': 'cotton',
   'mss_ff': 'galba e. xi. ff. 111-125',
   'mss': 'galba e. xi.',
   'ff': 'ff. 111-125',
   'page': 115},
  {'collection': 'cotton',
   'mss_ff': 'cleopatra d. v. ff. 165 b-183',
   'mss': 'cleopatra d. v.',
   'ff': 'ff. 165 b-183',
   'page': 114},
  {'collection': 'harley',
   'mss_ff': 'harley 527. ff. 47-56 b',
   'mss': 'harley 527.',
   'ff': 'ff. 47-56 b',
   'page': 113},
  {'collection': 'harley',
   'mss_ff': 'harley 2682. ff. 180-192',
   'mss': 'harley 2682.',
   'ff': 'ff. 180-192',
   'page': 109},
  {'collection': 'harley',
   'mss_ff': 'harley 4979',
   'mss': 'harley 4979',
   'ff': None,
   'page': 127},
  {'collection': 'harley',
   'mss_ff': 'harley 5054. ff. 124 b-181',
   'mss': 'harley 5054.',
   'ff': 'ff. 124 b-181',
   'page': 119},
  {'collection': 'arundel',
   'mss_ff': 'arundel 123. ff. 43-71',
   'mss': 'arundel 123.',
   'ff': 'ff. 43-71',
   'page': 120},
  {'collection': 'burney',
   'mss_ff': 'burney 280. ff. 1-20 b',
   'mss': 'burney 280.',
   'ff': 'ff. 1-20 b',
   'page': 118},
  {'collection': 'sloane',
   'mss_ff': 'sloane 1619. ff. 3-17 b',
   'mss': 'sloane 1619.',
   'ff': 'ff. 3-17 b',
   'page': 112},
  {'collection': 'sloane',
   'mss_ff': 'sloane 1785. ff. 2-13',
   'mss': 'sloane 1785.',
   'ff': 'ff. 2-13',
   'page': 131}],
 'prophecy': [{'collection': 'royal',
   'mss_ff': '12. c. xii. ff. 14-16 b',
   'mss': '12. c. xii.',
   'ff': 'ff. 14-16 b',
   'page': 316}],
 'fulk fitz-warin': [{'collection': 'royal',
   'mss_ff': '12. c. xii. ff. 33-60 b',
   'mss': '12. c. xii.',
   'ff': 'ff. 33-60 b',
   'page': 501}],
 'amya and amylion': [{'collection': 'royal',
   'mss_ff': '12. c. xii. ff. 69-76',
   'mss': '12. c. xii.',
   'ff': 'ff. 69-76',
   'page': 674}],
 'tale of two lovers': [{'collection': 'royal',
   'mss_ff': '12. c. xx. ff. 17-46',
   'mss': '12. c. xx.',
   'ff': 'ff. 17-46',
   'page': 801},
  {'collection': 'harley',
   'mss_ff': 'harley 1883. ff. 119-135 b',
   'mss': 'harley 1883.',
   'ff': 'ff. 119-135 b',
   'page': 799},
  {'collection': 'harley',
   'mss_ff': 'harley 2492. ff. 154 b-169 b',
   'mss': 'harley 2492.',
   'ff': 'ff. 154 b-169 b',
   'page': 802}],
 'historia trojana': [{'collection': 'royal',
   'mss_ff': '12. d. iii. ff. 38-143',
   'mss': '12. d. iii.',
   'ff': 'ff. 38-143',
   'page': 49},
  {'collection': 'royal',
   'mss_ff': '13. c. xii. ff. 6-32 b',
   'mss': '13. c. xii.',
   'ff': 'ff. 6-32 b',
   'page': 50},
  {'collection': 'royal',
   'mss_ff': '15. c. xvi. ff. 86-145',
   'mss': '15. c. xvi.',
   'ff': 'ff. 86-145',
   'page': 44},
  {'collection': 'royal',
   'mss_ff': '16. f. ix.',
   'mss': '16. f. ix.',
   'ff': None,
   'page': 54},
  {'collection': 'harley',
   'mss_ff': 'harley 51. ff. 3-105 b',
   'mss': 'harley 51.',
   'ff': 'ff. 3-105 b',
   'page': 52},
  {'collection': 'harley',
   'mss_ff': 'harley 176',
   'mss': 'harley 176',
   'ff': None,
   'page': 47},
  {'collection': 'harley',
   'mss_ff': 'harley 3637',
   'mss': 'harley 3637',
   'ff': None,
   'page': 48},
  {'collection': 'harley',
   'mss_ff': 'harley 3681',
   'mss': 'harley 3681',
   'ff': None,
   'page': 54},
  {'collection': 'harley',
   'mss_ff': 'harley 4123. ff. 50-126',
   'mss': 'harley 4123.',
   'ff': 'ff. 50-126',
   'page': 40},
  {'collection': 'harley',
   'mss_ff': 'harley 4387',
   'mss': 'harley 4387',
   'ff': None,
   'page': 53},
  {'collection': 'lansdowne',
   'mss_ff': 'lansdowne 229. ff. 164',
   'mss': 'lansdowne 229.',
   'ff': 'ff. 164',
   'page': 61},
  {'collection': 'arundel',
   'mss_ff': 'arundel 6 ff. 242-342 b',
   'mss': 'arundel 6',
   'ff': 'ff. 242-342 b',
   'page': 60},
  {'collection': 'arundel',
   'mss_ff': 'arundel 174',
   'mss': 'arundel 174',
   'ff': None,
   'page': 51},
  {'collection': 'additional',
   'mss_ff': 'add. 9785',
   'mss': 'add. 9785',
   'ff': None,
   'page': 57},
  {'collection': 'additional',
   'mss_ff': 'add. 15,477',
   'mss': 'add. 15,477',
   'ff': None,
   'page': 43},
  {'collection': 'additional',
   'mss_ff': 'add. 22,155',
   'mss': 'add. 22,155',
   'ff': None,
   'page': 46}],
 'story of troy': [{'collection': 'royal',
   'mss_ff': '12. d. iii. ff. 152 b-158',
   'mss': '12. d. iii.',
   'ff': 'ff. 152 b-158',
   'page': 34},
  {'collection': 'royal',
   'mss_ff': '13. a. iv. ff. 22 b-23 b, 76-81 b',
   'mss': '13. a. iv.',
   'ff': 'ff. 22 b-23 b, 76-81 b',
   'page': 27}],
 'prophecy of the tenth sibyl': [{'collection': 'royal',
   'mss_ff': '13. a. xiv. ff. 244-247',
   'mss': '13. a. xiv.',
   'ff': 'ff. 244-247',
   'page': 194},
  {'collection': 'royal',
   'mss_ff': '15. a. xxii. ff. 110-115',
   'mss': '15. a. xxii.',
   'ff': 'ff. 110-115',
   'page': 194},
  {'collection': 'royal',
   'mss_ff': '15. b. xi. ff. 67-69',
   'mss': '15. b. xi.',
   'ff': 'ff. 67-69',
   'page': 193},
  {'collection': 'cotton',
   'mss_ff': 'caligula a. x. ff. 200-204',
   'mss': 'caligula a. x.',
   'ff': 'ff. 200-204',
   'page': 195},
  {'collection': 'cotton',
   'mss_ff': 'caligula b. vii. ff. 219, 220',
   'mss': 'caligula b. vii.',
   'ff': 'ff. 219, 220',
   'page': 193},
  {'collection': 'cotton',
   'mss_ff': 'vespasian b. xxv. ff. 117 b-123',
   'mss': 'vespasian b. xxv.',
   'ff': 'ff. 117 b-123',
   'page': 192},
  {'collection': 'cotton',
   'mss_ff': 'vespasian e. iv. ff. 143-147',
   'mss': 'vespasian e. iv.',
   'ff': 'ff. 143-147',
   'page': 194},
  {'collection': 'cotton',
   'mss_ff': 'titus d. iii. ff. 143-147 b',
   'mss': 'titus d. iii.',
   'ff': 'ff. 143-147 b',
   'page': 191},

### index+theme

In [34]:
import json
path_index_table_clean="../results/vol1/vol1-index_table_clean.json"
with open(path_index_table_clean,'r', encoding='utf-8') as f:
    index_table_clean=json.load(f)

path_theme_table_clean=r"../results/vol1/theme_table_clean.json"
with open(path_theme_table_clean,'r', encoding='utf-8') as f:
    theme_table_clean=json.load(f)

In [36]:
importlib.reload(combine_tables)
from utils.combine_tables import compile_combined_table
df_table=compile_combined_table(index_table_clean=index_table_clean, 
                                      theme_table=theme_table_clean)

[No match] title theme'latin poems' not found in table index!
[No match] title theme'recueil' not found in table index!
[No match] title theme'adam bell, and other ballads of forest life' not found in table index!
[No match] title theme'voyage de charlemagne' not found in table index!
[No match] title theme'chevalier au cygne' not found in table index!
[No match] title theme'diana' not found in table index!
[No match] title theme'siege of milan and sir otuel' not found in table index!
no match title index: dict_keys(['historia regum britanniae', 'prophecy of merlin silvester', 'letters between alexander and dindimus', 'prophecies of merlin', 'prophecy on scotland', 'alexander the great', 'prophecy', 'amya and amylion', 'story of troy', 'prophecies of merlin silvester', 'guy of warwick and heraud of ardennes', 'knight of the swan', 'voyage of charlemagne to jerusalem and constantinople', 'recueil des histoires de troie', 'sir launfal', 'prophecy of merlin', 'prophecies', "merlin's prophecy of the six kings", "lisamon's brut", 'floyras and blanchefleur', 'ipomodon', 'lanval', 'fall of troy', 'fall of troy and adventures of æneas', 'two prophecies', 'prophecies of merlin, etc.', 'whole prophecy of scotland', 'story of troy and adventures of æneas', 'brut y brenhinoedd', 'prophecy of the lily, the lion, and the son of man', 'four prophecies', 'political prophecies', 'six fabliaux', 'prophecy of thomas of erceldoune', 'letter of dindimus to alexander the great', "l'ordène de chevalerie", 'richard cœur-de-lion', 'prophecies taken from geoffrey of monmouth and others', 'kings of britain', 'abridgement of historia trojana', 'chanson de roland', "chanson d'aspremont", 'prophecies of merlin, gildas, and thomas of ercildoune', 'life of robin hood', 'collection of prophecies', 'five romantic tales', 'ívents saga', 'eight romantic tales', 'parcevals saga and valvers þáttr', 'möttuls saga', 'partalópa saga', 'seven romantic tales', 'three romantic tales', 'saga of ajax frækni', 'merlínus spá', 'juglet', 'fioccolo', 'rimur of remund', 'collection of anecdotes', 'valentine and orson and tales', 'ten romantic tales', 'patient griselda', 'argenis', 'merlinus spá', 'brut gruffydd ap arthur', 'extracts from brut y brenhinoedd', 'isarles y ffynnawn', 'brut tyailio', 'voeux du paon and restor du paon', 'amis and amylion', 'may colvin', 'the king of tars and the soudan of damas', 'nine romantic tales', 'story of sigurgaror', 'fertrams saga', 'the grene knight, turke and gowin, the marriage of sir gawaine', 'sir lambewell', 'guye and amarant', 'three ballads of forest life', 'guy and phillis', 'robin hood ballad', 'libius disconius', 'guy and colebrande', 'two ballads relating to adam bell', 'a propecye', "robin hood's garland", 'ballads of scotland', 'two charlemagne romances', 'ipomedon and prothesilaus'])

In [ ]:
df_table
# df_table[df_table['mss'].isna()]
# df_table[["mss"]].value_counts(dropna=False)

,title_theme,title_index,author,theme,cycle,collection,mss_ff,mss,ff,page,mss_index
24,latin poems,None,"simon chèvre d'or, etc",classical romances,cycle of troy,None,None,None,None,27,None
45,recueil,None,raoul le fèvre,classical romances,cycle of troy,None,None,None,None,64,None
255,"adam bell, and other ballads of forest life",None,None,british and english traditions,None,None,None,None,None,522,None
286,voyage de charlemagne,None,None,french traditions,cycle of charlemagne,None,None,None,None,625,None
306,chevalier au cygne,None,None,miscellaneous romance,None,None,None,None,None,708,None
329,diana,None,jorge de montemayor (english translation),miscellaneous romance,None,None,None,None,None,789,None
409,siege of milan and sir otuel,None,None,appendix,None,None,None,None,None,953,None

In [38]:
df_table.to_csv("../results/vol1/vol1-combined_table.csv", index=False)

### index + theme + notices

In [39]:
path_notices_clean=r"../results\vol1\vol1-notices_clean.json"
with open(path_notices_clean,'r', encoding='utf-8') as f:
    notices=json.load(f)
    print(notices)
notices

[{'notice': 'Vellxun; xvth cent. Small Qnarto; ff. 68, with 21 lines to a page. Headings, glosses, and initials, in red. Formerly belonged to Sir Bobert', 'mss': 'royal 16. c. zxiii. ff. 2-69 b.', 'material': 'vellxun', 'cent': 'xvth', 'size': 'small qnarto', 'mss_index': 'royal 16. c. xxiii. ff. 2-69 b', 'material_class': 'vellum', 'size_class': 'quarto', 'cent_i': 15}, {'notice': 'Paper ; t wo vols., a.d. 1560 and 1565. Small Quarto ; f f. 4 6, and ff. 98 ; t he full pages of Vol. i. h aving 35 to 36 and those of Vol. n. 24 to 27 lines of verse.', 'mss': 'royal 16* c. iv. a. b.', 'material': 'paper', 'cent': 't wo vols ad 1560 and 1565', 'size': 'small quarto', 'mss_index': 'royal 16. c. iv. a. b.', 'material_class': 'paper', 'size_class': 'quarto', 'cent_i': 16}, {'notice': 'Paper; zvith cent. ; t wo vol& Folio; ff. 160, and ff. 39; each full pago of Vol. I. ( A) having 21 to 25 lines of Greek, and 23 to 26 lines of Latin, and', 'mss': 'royal 16. d. iii. a. b.', 'material': 'paper', 'cent': 'zvith', 'size': '', 'mss_index': 'royal 16. d. iii. a. b.', 'material_class': 'paper', 'size_class': None, 'cent_i': 6}, {'notice': 'Paper; xvth cent Quarto; ff. 56, with 15 lines to a full page. The rest of the yolume containfi :', 'mss': 'harley 6662. «. i-56.', 'material': 'paper', 'cent': 'xvth', 'size': 'quarto', 'mss_index': 'harley 5662. ff. 1-56', 'material_class': 'paper', 'size_class': 'quarto', 'cent_i': 15}, {'notice': 'Paper; xvth cent. Octavo ; f L 72, each page containing 22 lines. With four spaces left for initials to the introductory epistle and the first three', 'mss': 'additional 15,429.', 'material': 'paper', 'cent': 'xvth', 'size': 'octavo', 'mss_index': 'additional add. 15,429', 'material_class': 'paper', 'size_class': 'octavo', 'cent_i': 15}, {'notice': 'Vellum; xvth cent. Octavo; ff. 102, having 23 lines to a page. With seven illuminated initials, and a space left for one which is not filled in ;', 'mss': 'harley 3514.', 'material': 'vellum', 'cent': 'xvth', 'size': 'octavo', 'mss_index': 'harley 3514', 'material_class': 'vellum', 'size_class': 'octavo', 'cent_i': 15}, {'notice': 'Vellum; xnth cent. Quarto; ff. 19, haying 27 lines to a page. With 31 initials in red, green, and purple. The volume has the ancient press-', 'mss': 'cotton^ vespasian b. zzv. ff. 98b-ii7.', 'material': 'vellum', 'cent': 'xnth', 'size': 'quarto', 'mss_index': 'cotton vespasian b. xxv. ff. 98 b-117', 'material_class': 'vellum', 'size_class': 'quarto', 'cent_i': None}, {'notice': 'Vellum; xiith cent. Small Quarto; ff. 18, containing 30 lines to the page. With initials in red and green; and a few headings in red. The', 'mss': 'royal 15. a. xxii^ ff. 73-90.', 'material': 'vellum', 'cent': 'xiith', 'size': 'small quarto', 'mss_index': 'royal 15. a. xxii. ff. 73-90', 'material_class': 'vellum', 'size_class': 'quarto', 'cent_i': 12}, {'notice': 'Yellmn; xnth cent. Quarto; ff. 10, containing 30 lines to a page. With 28 initials in red, green, and yellow. The volmue formerly belonged to the', 'mss': 'royal 15. b. zi. ff. 57-66 b.', 'material': 'yellmn', 'cent': 'xnth', 'size': 'quarto', 'mss_index': 'royal 15. b. xi. ff. 57-66 b', 'material_class': 'vellum', 'size_class': 'quarto', 'cent_i': None}, {'notice': 'Vellum; early xiiith cent Folio; ffi 11, in double columns, haying 37 lines to a colunm. With initials in blue, green, and red. The volume', 'mss': 'royal 6. c. viii. flf. 123-133 b.', 'material': 'vellum', 'cent': 'early xiiith', 'size': 'folio', 'mss_index': 'royal 6. c. viii. ff. 123-133 b', 'material_class': 'vellum', 'size_class': 'folio', 'cent_i': 13}, {'notice': 'Yelluin; early zmth cent. Folio; double columns, each fall column haymg 37 lines. With initials in red and green.', 'mss': 'cotton, vitellins c. viii. ff. 5b-«b.', 'material': 'yelluin', 'cent': 'early zmth', 'size': 'folio', 'mss_index': 'cotton vitellius c. viii. ff. 5 b-6 b', 'material_class': 'vellum', 'size_class': 'folio', 'cent_i': None}, {'notice': 'Yellum; early xmth cent. Octavo; ff. 9, having 38 lines to a page. With 40 coloured initials ; 3 9 in bine and red, and one in green.', 'mss': 'sloane 1619. ff. 29-37 b.', 'material': 'yellum', 'cent': 'early xmth', 'size': 'octavo', 'mss_index': 'sloane 1619 ff. 29-37 b', 'material_class': 'vellum', 'size_class': 'octavo', 'cent_i': None}, {'notice': 'Vellmn ; xinth cent. Quarto ; f f. 5, in doable colnmns, having 53 lines to a column. With 8 initials in red and green, and spaces left for 26 more*', 'mss': 'royal 10. a. z. ff 1 88-1 92 b.', 'material': 'vellmn', 'cent': 'xinth', 'size': 'quarto', 'mss_index': 'royal 10. a. x. ff. 188-192 b', 'material_class': 'vellum', 'size_class': 'quarto', 'cent_i': None}, {'notice': 'Vellum ; early xrvth cent. Folio ; f f. 8, h aving 49 lines to a page. With one ornamental initial (f. 3 ), of later insertion, and spaces left for 30 more.', 'mss': 'harley 641. flf. 1-8.', 'material': 'vellum', 'cent': 'early xrvth', 'size': 'folio', 'mss_index': 'harley 641. ff. 1-8', 'material_class': 'vellum', 'size_class': 'folio', 'cent_i': 5}, {'notice': 'Vellmn; late xmth cent. Small Quarto; fll 11, in double columns, each full coliunn containing 33 lines.', 'mss': 'royal 13. a. v. ff. 88 b-98 b.', 'material': 'vellmn', 'cent': 'late xmth', 'size': 'small quarto', 'mss_index': 'royal 13. a. v. ff. 88 b-98 b', 'material_class': 'vellum', 'size_class': 'quarto', 'cent_i': None}, {'notice': 'Vellum; xvth cent. Quarto; fL 14, having 31 to 32 lines to a page. With 15 initials in red.', 'mss': 'additional 10,094. ff. i-i4b.', 'material': 'vellum', 'cent': 'xvth', 'size': 'quarto', 'mss_index': 'additional add. 10,094. ff. 1-14 b', 'material_class': 'vellum', 'size_class': 'quarto', 'cent_i': 15}, {'notice': 'Paper; aj). 1801. Small Quarto; ff. 58, haying 15 lines to a paga The writer has used the Greek d to represent the Welsh dd,', 'mss': 'additional 15,042.', 'material': 'paper', 'cent': 'aj 1801', 'size': 'small quarto', 'mss_index': 'additional add. 15,042', 'material_class': 'paper', 'size_class': 'quarto', 'cent_i': 19}, {'notice': 'Vellmn; xvth cent Small Quarto; fL I, haying 28 lines to a page. Much discoloured.', 'mss': 'additional 19,709. ff. 1-7.', 'material': 'vellmn', 'cent': 'xvth', 'size': 'small quarto', 'mss_index': 'additional add. 19,709. ff. 1-7', 'material_class': 'vellum', 'size_class': 'quarto', 'cent_i': 15}, {'notice': 'Yellum; xvth cent Small Quarto; fiL 28, in double columns, having 28 lines to a page, with three coloured initials.', 'mss': 'cotton, cleopatra b. v. ff. 223-250.', 'material': 'yellum', 'cent': 'xvth', 'size': 'small quarto', 'mss_index': 'cotton cleopatra b. v. ff. 222-250', 'material_class': 'vellum', 'size_class': 'quarto', 'cent_i': 15}, {'notice': 'Vellum; xinth cent. Small Octavo; ff. 2, each page having 37 to 38 lines ; and ff. 6, e ach fall page having 40 lines. Initials in red and green.', 'mss': 'royal 13. a. iv. ff. 22 b-23 b ; and ff. 76--81 b.', 'material': 'vellum', 'cent': 'xinth', 'size': 'small octavo', 'mss_index': 'royal 13. a. iv. ff. 22 b-23 b, 76-81 b', 'material_class': 'vellum', 'size_class': 'octavo', 'cent_i': None}, {'notice': 'Harley 3202. ff. ii4b-ii5b. Vellum ; xmth cent Small Quarto ; f f. 2 , e ach fall page having 26 lines.', 'mss': 'cotton ms. cleopatra a. viii. at f. 57.', 'material': 'harley 3202. ff. ii4b-ii5b. vellum', 'cent': 'xmth', 'size': 'small quarto', 'mss_index': 'cotton cleopatra a. viii. ff. 56-58', 'material_class': 'vellum', 'size_class': 'quarto', 'cent_i': None}, {'notice': 'Vellum ; xmth cent Small Quarto ; f f. 2 , e ach fall page having 26 lines. The whole yolume contains the following, in Latin :', 'mss': 'harley 3202. ff. ii4b-ii5b.', 'material': 'vellum', 'cent': 'xmth', 'size': 'small quarto', 'mss_index': 'harley 3202. ff. 114 b-115 b', 'material_class': 'vellum', 'size_class': 'quarto', 'cent_i': None}, {'notice': 'YeUmn ; xvth oeni Long Quarto ; f if. 4 , each page having 48 to 53 lines. With initials in blue.', 'mss': 'cotton, vespasian b. zxiii. part iii. ff. ii8b-i22b.', 'material': 'yeumn', 'cent': 'xvth oeni', 'size': 'long quarto', 'mss_index': 'cotton vespasian b. xxiii. part iii. ff. 118 b-122 b', 'material_class': 'vellum', 'size_class': 'quarto', 'cent_i': 15}, {'notice': 'YellTim ; xvih cent. Quarto; fL 6, having 82 to 83 lines to a page. With two ooloored initials, one in blue and the other in red.', 'mss': 'royal 12. d. iii. fil i52b-i58.', 'material': 'yelltim', 'cent': 'xvih', 'size': 'quarto', 'mss_index': 'royal 12. d. iii. ff. 152 b-158', 'material_class': 'vellum', 'size_class': 'quarto', 'cent_i': None}, {'notice': 'Vellum ; about A.D. 1800. Oblong Octayo ; f t IBS, in double columns, haying 40 lines to a column. With initials in red and blue ; and 15 illu-', 'mss': 'harley 4482.', 'material': 'vellum', 'cent': 'about', 'size': 'ad 1800 oblong octayo', 'mss_index': 'harley 4482', 'material_class': 'vellum', 'size_class': None, 'cent_i': None}, {'notice': 'Yelltun ; about a.d. 1350. Folio ; £ f. 77» in double columns, each column containing 46 lines. With initials and rubrics in red. Although the', 'mss': 'harley 4123. ff. 6o-126.', 'material': 'yelltun', 'cent': 'about ad 1350', 'size': 'folio', 'mss_index': 'harley 4123. ff. 50-126', 'material_class': 'vellum', 'size_class': 'folio', 'cent_i': 14}, {'notice': 'Velltiin; about a.i>. 1B50: Large Folio; ff. 58, in double columnB, each column containing 58 lines. With initials in red and blue, and nine illu-', 'mss': 'additional 15,477.', 'material': 'velltiin', 'cent': 'about ai 1', 'size': 'b50 large folio', 'mss_index': 'additional add. 15,477', 'material_class': 'vellum', 'size_class': 'folio', 'cent_i': None}, {'notice': 'Yellum; xivth cent Folio; ff. 70, in double columns, each full column haying 52 lines. With initials in blue, flourished with red. The volume at', 'mss': 'royal 15. c. zvi. ff. 86-145.', 'material': 'yellum', 'cent': 'xivth', 'size': 'folio', 'mss_index': 'royal 15. c. xvi. ff. 86-145', 'material_class': 'vellum', 'size_class': 'folio', 'cent_i': 14}, {'notice': 'Vellum ; x irth cent. Folio; ff. 61, in doable columns, having 52 lines to ! a column. Written in an Italian hand ; with two illuminated initials (the', 'mss': 'additional 22,155.', 'material': 'vellum', 'cent': 'x irth', 'size': 'folio', 'mss_index': 'additional add. 22,155', 'material_class': 'vellum', 'size_class': 'folio', 'cent_i': None}, {'notice': 'YeUTun ; xvth cent. Bnodeciino ; f if. 1 80^ each page having from 28 to 39 lines. Written in England ; with initials in blue, flooiished with xed, and', 'mss': 'harley 176.', 'material': 'yeutun', 'cent': 'xvth', 'size': 'bnodeciino', 'mss_index': 'harley 176', 'material_class': None, 'size_class': None, 'cent_i': 15}, {'notice': 'Vellum; xvth cent. Folio; flf. 88, in double columns, each column having 43 lines. Written in Italy; with initials in blue and red, and an', 'mss': 'harley 3637.', 'material': 'vellum', 'cent': 'xvth', 'size': 'folio', 'mss_index': 'harley 3637', 'material_class': 'vellum', 'size_class': 'folio', 'cent_i': 15}, {'notice': 'Vellum; xvthcent. Quarto; ff. 106,haYing firom d0to36 lines to a page. Written in England ; with initials in blue and red.', 'mss': 'royal 12. d. iii. & 38-143.', 'material': 'vellum', 'cent': 'xvth', 'size': 'quarto', 'mss_index': 'royal 12. d. iii. ff. 38-143', 'material_class': 'vellum', 'size_class': 'quarto', 'cent_i': 15}, {'notice': 'Vellum; xvth cent Folio; ffl 77, hATing 41 to 48 lines to a page. Written in England; with initials in red.', 'mss': 'royal 13. c. zii. ff. 6-82 b.', 'material': 'vellum', 'cent': 'xvth', 'size': 'folio', 'mss_index': 'royal 13. c. xii. ff. 6-32 b', 'material_class': 'vellum', 'size_class': 'folio', 'cent_i': 15}, {'notice': 'Yellom; xvth cent. Octayo; £f. 145^ each page having from 25 to S7 lines. Written in England. At the beginning is the signature of "William', 'mss': 'arundel 174.', 'material': 'yellom', 'cent': 'xvth', 'size': 'octayo', 'mss_index': 'arundel 174', 'material_class': 'vellum', 'size_class': 'octavo', 'cent_i': 15}, {'notice': 'Paper and yellum, every eight leaves of paper being enclosed between two of yellum; late xvth cent Quarto; ff. 175, each page having 28 to 35', 'mss': 'harley 4387.', 'material': 'paper and yellum, every eight leaves of paper being enclosed between two of yellum', 'cent': 'late xvth', 'size': 'quarto', 'mss_index': 'harley 4387', 'material_class': 'paper', 'size_class': 'quarto', 'cent_i': 15}, {'notice': 'Paper; late xvth cent. Folio; ff. 140, haying SO to 36 lines to a full page. With initials in red. In a foreign hand.', 'mss': 'harley 3681.', 'material': 'paper', 'cent': 'late xvth', 'size': 'folio', 'mss_index': 'harley 3681', 'material_class': 'paper', 'size_class': 'folio', 'cent_i': 15}, {'notice': 'Vellum; late xvth cent Folio; ft 100, in double oolumns. Written in two different French hands, a full column of the one (ft 18-24 b) containing', 'mss': 'royal 16. f. iz.', 'material': 'vellum', 'cent': 'late xvth', 'size': 'folio', 'mss_index': 'royal 16. f. ix.', 'material_class': 'vellum', 'size_class': 'folio', 'cent_i': 15}, {'notice': 'Paper; about aj>. 1500. Quarto; ff. 243, baying from 28 to 31 lines to a fall page. Written by a French hand ; with initials in bine and red.', 'mss': 'additional 9785.', 'material': 'paper', 'cent': 'about aj 1500', 'size': 'quarto', 'mss_index': 'additional add. 9785', 'material_class': 'paper', 'size_class': 'quarto', 'cent_i': 15}, {'notice': 'Paper ; xYith oeni Octayo ; f f. 4, each full page having 28 to 80 Imes. With the first initial of the rubric in bine, and the first initial of the yerses', 'mss': 'lansdowne 380. ff. 36-39 b.', 'material': 'paper', 'cent': 'x', 'size': 'yith oeni octayo', 'mss_index': 'lansdowne 380. ff. 36-39 b', 'material_class': 'paper', 'size_class': None, 'cent_i': None}, {'notice': 'Paper; xTth cent Folio; ft 101, in double colnznns, each oolmnn having 40 lines. With initialB in red.', 'mss': 'arundel 6. ff. 242-^42 b.', 'material': 'paper', 'cent': 'xtth', 'size': 'folio', 'mss_index': 'arundel 6 ff. 242-342 b', 'material_class': 'paper', 'size_class': 'folio', 'cent_i': None}, {'notice': 'Vellum; znrth cent. Folio; one leaf in double columns, each column having 42 lines. With initials in red and blue.', 'mss': 'lansdowne 229. f. 164.', 'material': 'vellum', 'cent': 'znrth', 'size': 'folio', 'mss_index': 'lansdowne 229. ff. 164', 'material_class': 'vellum', 'size_class': 'folio', 'cent_i': None}, {'notice': 'Paper; ajd. 1679. Folio ; f f. 65, haying 37 to 89 lines to a page. With initials in red and green. Forming the first of five sagas, written by J6n', 'mss': 'additional 4869. «. 2-66.', 'material': 'paper', 'cent': 'ajd 1679', 'size': 'folio', 'mss_index': 'additional add. 4869. ff. 2-66', 'material_class': 'paper', 'size_class': 'folio', 'cent_i': 17}, {'notice': 'Paper; xvnith cent. Folio; fif. Ill, each page haying from 17 to 21 lines, in which the yerses are written like prose.', 'mss': 'additional 11,113. ff. i7i-28i.', 'material': 'paper', 'cent': 'xvnith', 'size': 'folio', 'mss_index': 'additional add. 11,113. ff. 171-281', 'material_class': 'paper', 'size_class': 'folio', 'cent_i': 1}, {'notice': 'Vellmn; xrth cent Folio; ff. 368, in doable columns, each column haying 30 lines. With illuminated initials, and with 65 miniatures, three', 'mss': 'royal 17. e. ii.', 'material': 'vellmn', 'cent': 'xrth', 'size': 'folio', 'mss_index': 'royal 17. e. ii.', 'material_class': 'vellum', 'size_class': 'folio', 'cent_i': None}, {'notice': 'Yellmn ; early xrth cent. The date 1374 in the colophon seems to be copied from an earlier MS. Folio ; f f. 90 of verse, having four stanzas', 'mss': 'additional 21,240.', 'material': 'yellmn', 'cent': 'early xrth', 'size': 'the date 1374 in the colophon seems to be copied from an earlier ms folio', 'mss_index': 'additional add. 21,246', 'material_class': 'vellum', 'size_class': 'folio', 'cent_i': None}, {'notice': 'Vellum; early xvth cent. Small Folio; with the top margin clipped close; ff. 98, each full page having six scTen-line stanzas. With illtuninated', 'mss': 'harley 2280.', 'material': 'vellum', 'cent': 'early xvth', 'size': 'small folio', 'mss_index': 'harley 2280', 'material_class': 'vellum', 'size_class': 'folio', 'cent_i': 15}, {'notice': 'Vellmn; xvth cent. Quarto; fif. 118, each page, except f. 112, having five seven-line stanzas. With initials in blue and red. At the beginning of', 'mss': 'additional 12,044.', 'material': 'vellmn', 'cent': 'xvth', 'size': 'quarto', 'mss_index': 'additional add. 12,044', 'material_class': 'vellum', 'size_class': 'quarto', 'cent_i': 15}, {'notice': 'Paper and yeUnm, four leaves of paper being endoeed between each pair of velltun leaves; xvth cent. Small Quarto; ff. 145, each fall page liaving', 'mss': 'harley 2392.', 'material': 'paper and yeunm, four leaves of paper being endoeed between each pair of velltun leaves', 'cent': 'xvth', 'size': 'small quarto', 'mss_index': 'harley 2392', 'material_class': 'paper', 'size_class': 'quarto', 'cent_i': 15}, {'notice': 'Vellmn; xvth cent Oblong Folio; ff. 62, each fnll page having nine seven-line stanzas. With initials in red and bine; and an illuminated', 'mss': 'harley 1239. ff. i-62 b.', 'material': 'vellmn', 'cent': 'xvth', 'size': 'oblong folio', 'mss_index': 'harley 1239. ff. 1-62 b', 'material_class': 'vellum', 'size_class': 'folio', 'cent_i': 15}, {'notice': 'Vellum; xvth cent Folio; ff. 75, each full page having five Beven-Une stanzas. On the fly-leaf at the banning are the names, Anno Norree, Anne', 'mss': 'harley 4912.', 'material': 'vellum', 'cent': 'xvth', 'size': 'folio', 'mss_index': 'harley 4912', 'material_class': 'vellum', 'size_class': 'folio', 'cent_i': 15}, {'notice': "' Y elliun; late xvth cent Folio; ff. 189, in doable coliunns, each fall colTmuD hATing 52 lines. With illuminated initials, and with an illuminated", 'mss': 'royal 18. d. vi.', 'material': "' y elliun", 'cent': 'late xvth', 'size': 'folio', 'mss_index': 'royal 18. d. vi.', 'material_class': 'vellum', 'size_class': 'folio', 'cent_i': 15}, {'notice': 'Yellnm; about a.d. 1460. Folio; ff. 141, in double columns, each fall colunm having 40 to 52 lines. With illuminated initials, and one border,', 'mss': 'royal 18. d. ii. ff. 6-146.', 'material': 'yellnm', 'cent': 'about ad 1460', 'size': 'folio', 'mss_index': 'royal 18. d. ii. ff. 6-146', 'material_class': 'vellum', 'size_class': 'folio', 'cent_i': 15}, {'notice': 'Vellum; luvth cent. FoUo; ff. 78, in doable columns, each column having M lines, except in the case of the first column, where (owing to the', 'mss': 'additional 14,100.', 'material': 'vellum', 'cent': 'luvth', 'size': 'fouo', 'mss_index': 'additional add. 14,100', 'material_class': 'vellum', 'size_class': 'folio', 'cent_i': 5}, {'notice': 'Vellum; xrth cent Slmall Quarto; ff. 84, each page haying 26 to 33 lines. With initials in blue, flourished with red. At the beginning of the', 'mss': 'harley 525. ff. 1-34 b.', 'material': 'vellum', 'cent': 'xrth', 'size': 'slmall quarto', 'mss_index': 'harley 525. ff. 1-34 b', 'material_class': 'vellum', 'size_class': 'quarto', 'cent_i': None}, {'notice': 'Velltun; about a.d. 1430. Small Folio; ff. 79, each full page having 82 lines from £ 1 to 9, 3 1 lines from ff. 9 b to 24 b, and 30 lines from f. 2 5 to', 'mss': 'arundel 119.', 'material': 'velltun', 'cent': 'about ad 1430', 'size': 'small folio', 'mss_index': 'arundel 119', 'material_class': 'vellum', 'size_class': 'folio', 'cent_i': 15}, {'notice': 'Yellnm ; about a.d. 1440. Folio ; f f. 29, in double colmnns, each column oontaining 42 lines. With illuminated initials and three borders.', 'mss': 'additional 18^632. ff. 5-38.', 'material': 'yellnm', 'cent': 'about ad 1440', 'size': 'folio', 'mss_index': 'additional add. 18,632. ff. 5-33', 'material_class': 'vellum', 'size_class': 'folio', 'cent_i': 15}, {'notice': 'Vellum; about a.d. 1460. Folio; ff. 16, in double columns, eac

[{'notice': 'Vellxun; xvth cent. Small Qnarto; ff. 68, with 21 lines to a page. Headings, glosses, and initials, in red. Formerly belonged to Sir Bobert',
  'mss': 'royal 16. c. zxiii. ff. 2-69 b.',
  'material': 'vellxun',
  'cent': 'xvth',
  'size': 'small qnarto',
  'mss_index': 'royal 16. c. xxiii. ff. 2-69 b',
  'material_class': 'vellum',
  'size_class': 'quarto',
  'cent_i': 15},
 {'notice': 'Paper ; t wo vols., a.d. 1560 and 1565. Small Quarto ; f f. 4 6, and ff. 98 ; t he full pages of Vol. i. h aving 35 to 36 and those of Vol. n. 24 to 27 lines of verse.',
  'mss': 'royal 16* c. iv. a. b.',
  'material': 'paper',
  'cent': 't wo vols ad 1560 and 1565',
  'size': 'small quarto',
  'mss_index': 'royal 16. c. iv. a. b.',
  'material_class': 'paper',
  'size_class': 'quarto',
  'cent_i': 16},
 {'notice': 'Paper; zvith cent. ; t wo vol& Folio; ff. 160, and ff. 39; each full pago of Vol. I. ( A) having 21 to 25 lines of Greek, and 23 to 26 lines of Latin, and',
  'mss': 'royal 16. d. iii. a. b.',
  'material': 'paper',
  'cent': 'zvith',
  'size': '',
  'mss_index': 'royal 16. d. iii. a. b.',
  'material_class': 'paper',
  'size_class': None,
  'cent_i': 6},
 {'notice': 'Paper; xvth cent Quarto; ff. 56, with 15 lines to a full page. The rest of the yolume containfi :',
  'mss': 'harley 6662. «. i-56.',
  'material': 'paper',
  'cent': 'xvth',
  'size': 'quarto',
  'mss_index': 'harley 5662. ff. 1-56',
  'material_class': 'paper',
  'size_class': 'quarto',
  'cent_i': 15},
 {'notice': 'Paper; xvth cent. Octavo ; f L 72, each page containing 22 lines. With four spaces left for initials to the introductory epistle and the first three',
  'mss': 'additional 15,429.',
  'material': 'paper',
  'cent': 'xvth',
  'size': 'octavo',
  'mss_index': 'additional add. 15,429',
  'material_class': 'paper',
  'size_class': 'octavo',
  'cent_i': 15},
 {'notice': 'Vellum; xvth cent. Octavo; ff. 102, having 23 lines to a page. With seven illuminated initials, and a space left for one which is not filled in ;',
  'mss': 'harley 3514.',
  'material': 'vellum',
  'cent': 'xvth',
  'size': 'octavo',
  'mss_index': 'harley 3514',
  'material_class': 'vellum',
  'size_class': 'octavo',
  'cent_i': 15},
 {'notice': 'Vellum; xnth cent. Quarto; ff. 19, haying 27 lines to a page. With 31 initials in red, green, and purple. The volume has the ancient press-',
  'mss': 'cotton^ vespasian b. zzv. ff. 98b-ii7.',
  'material': 'vellum',
  'cent': 'xnth',
  'size': 'quarto',
  'mss_index': 'cotton vespasian b. xxv. ff. 98 b-117',
  'material_class': 'vellum',
  'size_class': 'quarto',
  'cent_i': None},
 {'notice': 'Vellum; xiith cent. Small Quarto; ff. 18, containing 30 lines to the page. With initials in red and green; and a few headings in red. The',
  'mss': 'royal 15. a. xxii^ ff. 73-90.',
  'material': 'vellum',
  'cent': 'xiith',
  'size': 'small quarto',
  'mss_index': 'royal 15. a. xxii. ff. 73-90',
  'material_class': 'vellum',
  'size_class': 'quarto',
  'cent_i': 12},
 {'notice': 'Yellmn; xnth cent. Quarto; ff. 10, containing 30 lines to a page. With 28 initials in red, green, and yellow. The volmue formerly belonged to the',
  'mss': 'royal 15. b. zi. ff. 57-66 b.',
  'material': 'yellmn',
  'cent': 'xnth',
  'size': 'quarto',
  'mss_index': 'royal 15. b. xi. ff. 57-66 b',
  'material_class': 'vellum',
  'size_class': 'quarto',
  'cent_i': None},
 {'notice': 'Vellum; early xiiith cent Folio; ffi 11, in double columns, haying 37 lines to a colunm. With initials in blue, green, and red. The volume',
  'mss': 'royal 6. c. viii. flf. 123-133 b.',
  'material': 'vellum',
  'cent': 'early xiiith',
  'size': 'folio',
  'mss_index': 'royal 6. c. viii. ff. 123-133 b',
  'material_class': 'vellum',
  'size_class': 'folio',
  'cent_i': 13},
 {'notice': 'Yelluin; early zmth cent. Folio; double columns, each fall column haymg 37 lines. With initials in red and green.',
  'mss': 'cotton, vitellins c. viii. ff. 5b-«b.',
  'material': 'yelluin',
  'cent': 'early zmth',
  'size': 'folio',
  'mss_index': 'cotton vitellius c. viii. ff. 5 b-6 b',
  'material_class': 'vellum',
  'size_class': 'folio',
  'cent_i': None},
 {'notice': 'Yellum; early xmth cent. Octavo; ff. 9, having 38 lines to a page. With 40 coloured initials ; 3 9 in bine and red, and one in green.',
  'mss': 'sloane 1619. ff. 29-37 b.',
  'material': 'yellum',
  'cent': 'early xmth',
  'size': 'octavo',
  'mss_index': 'sloane 1619 ff. 29-37 b',
  'material_class': 'vellum',
  'size_class': 'octavo',
  'cent_i': None},
 {'notice': 'Vellmn ; xinth cent. Quarto ; f f. 5, in doable colnmns, having 53 lines to a column. With 8 initials in red and green, and spaces left for 26 more*',
  'mss': 'royal 10. a. z. ff 1 88-1 92 b.',
  'material': 'vellmn',
  'cent': 'xinth',
  'size': 'quarto',
  'mss_index': 'royal 10. a. x. ff. 188-192 b',
  'material_class': 'vellum',
  'size_class': 'quarto',
  'cent_i': None},
 {'notice': 'Vellum ; early xrvth cent. Folio ; f f. 8, h aving 49 lines to a page. With one ornamental initial (f. 3 ), of later insertion, and spaces left for 30 more.',
  'mss': 'harley 641. flf. 1-8.',
  'material': 'vellum',
  'cent': 'early xrvth',
  'size': 'folio',
  'mss_index': 'harley 641. ff. 1-8',
  'material_class': 'vellum',
  'size_class': 'folio',
  'cent_i': 5},
 {'notice': 'Vellmn; late xmth cent. Small Quarto; fll 11, in double columns, each full coliunn containing 33 lines.',
  'mss': 'royal 13. a. v. ff. 88 b-98 b.',
  'material': 'vellmn',
  'cent': 'late xmth',
  'size': 'small quarto',
  'mss_index': 'royal 13. a. v. ff. 88 b-98 b',
  'material_class': 'vellum',
  'size_class': 'quarto',
  'cent_i': None},
 {'notice': 'Vellum; xvth cent. Quarto; fL 14, having 31 to 32 lines to a page. With 15 initials in red.',
  'mss': 'additional 10,094. ff. i-i4b.',
  'material': 'vellum',
  'cent': 'xvth',
  'size': 'quarto',
  'mss_index': 'additional add. 10,094. ff. 1-14 b',
  'material_class': 'vellum',
  'size_class': 'quarto',
  'cent_i': 15},
 {'notice': 'Paper; aj). 1801. Small Quarto; ff. 58, haying 15 lines to a paga The writer has used the Greek d to represent the Welsh dd,',
  'mss': 'additional 15,042.',
  'material': 'paper',
  'cent': 'aj 1801',
  'size': 'small quarto',
  'mss_index': 'additional add. 15,042',
  'material_class': 'paper',
  'size_class': 'quarto',
  'cent_i': 19},
 {'notice': 'Vellmn; xvth cent Small Quarto; fL I, haying 28 lines to a page. Much discoloured.',
  'mss': 'additional 19,709. ff. 1-7.',
  'material': 'vellmn',
  'cent': 'xvth',
  'size': 'small quarto',
  'mss_index': 'additional add. 19,709. ff. 1-7',
  'material_class': 'vellum',
  'size_class': 'quarto',
  'cent_i': 15},
 {'notice': 'Yellum; xvth cent Small Quarto; fiL 28, in double columns, having 28 lines to a page, with three coloured initials.',
  'mss': 'cotton, cleopatra b. v. ff. 223-250.',
  'material': 'yellum',
  'cent': 'xvth',
  'size': 'small quarto',
  'mss_index': 'cotton cleopatra b. v. ff. 222-250',
  'material_class': 'vellum',
  'size_class': 'quarto',
  'cent_i': 15},
 {'notice': 'Vellum; xinth cent. Small Octavo; ff. 2, each page having 37 to 38 lines ; and ff. 6, e ach fall page having 40 lines. Initials in red and green.',
  'mss': 'royal 13. a. iv. ff. 22 b-23 b ; and ff. 76--81 b.',
  'material': 'vellum',
  'cent': 'xinth',
  'size': 'small octavo',
  'mss_index': 'royal 13. a. iv. ff. 22 b-23 b, 76-81 b',
  'material_class': 'vellum',
  'size_class': 'octavo',
  'cent_i': None},
 {'notice': 'Harley 3202. ff. ii4b-ii5b. Vellum ; xmth cent Small Quarto ; f f. 2 , e ach fall page having 26 lines.',
  'mss': 'cotton ms. cleopatra a. viii. at f. 57.',
  'material': 'harley 3202. ff. ii4b-ii5b. vellum',
  'cent': 'xmth',
  'size': 'small quarto',
  'mss_index': 'cotton cleopatra a. viii. ff. 56-58',
  'material_class': 'vellum',
  'size_class': 'quarto',
  'cent_i': None},
 {'notice': 'Vellum ; xmth cent Small Quarto ; f f. 2 , e ach fall page having 26 lines. The whole yolume contains the following, in Latin :',
  'mss': 'harley 3202. ff. ii4b-ii5b.',
  'material': 'vellum',
  'cent': 'xmth',
  'size': 'small quarto',
  'mss_index': 'harley 3202. ff. 114 b-115 b',
  'material_class': 'vellum',
  'size_class': 'quarto',
  'cent_i': None},
 {'notice': 'YeUmn ; xvth oeni Long Quarto ; f if. 4 , each page having 48 to 53 lines. With initials in blue.',
  'mss': 'cotton, vespasian b. zxiii. part iii. ff. ii8b-i22b.',
  'material': 'yeumn',
  'cent': 'xvth oeni',
  'size': 'long quarto',
  'mss_index': 'cotton vespasian b. xxiii. part iii. ff. 118 b-122 b',
  'material_class': 'vellum',
  'size_class': 'quarto',
  'cent_i': 15},
 {'notice': 'YellTim ; xvih cent. Quarto; fL 6, having 82 to 83 lines to a page. With two ooloored initials, one in blue and the other in red.',
  'mss': 'royal 12. d. iii. fil i52b-i58.',
  'material': 'yelltim',
  'cent': 'xvih',
  'size': 'quarto',
  'mss_index': 'royal 12. d. iii. ff. 152 b-158',
  'material_class': 'vellum',
  'size_class': 'quarto',
  'cent_i': None},
 {'notice': 'Vellum ; about A.D. 1800. Oblong Octayo ; f t IBS, in double columns, haying 40 lines to a column. With initials in red and blue ; and 15 illu-',
  'mss': 'harley 4482.',
  'material': 'vellum',
  'cent': 'about',
  'size': 'ad 1800 oblong octayo',
  'mss_index': 'harley 4482',
  'material_class': 'vellum',
  'size_class': None,
  'cent_i': None},
 {'notice': 'Yelltun ; about a.d. 1350. Folio ; £ f. 77» in double columns, each column containing 46 lines. With initials and rubrics in red. Although the',
  'mss': 'harley 4123. ff. 6o-126.',
  'material': 'yelltun',
  'cent': 'about ad 1350',
  'size': 'folio',
  'mss_index': 'harley 4123. ff. 50-126',
  'material_class': 'vellum',
  'size_class': 'folio',
  'cent_i': 14},
 {'notice': 'Velltiin; about a.i>. 1B50: Large Folio; ff. 58, in double columnB, each column containing 58 lines. With initials in red and blue, and nine illu-',
  'mss': 'additional 15,477.',
  'material': 'velltiin',
  'cent': 'about ai 1',
  'size': 'b50 large folio',
  'mss_index': 'additional add. 15,477',
  'material_class': 'vellum',
  'size_class': 'folio',
  'cent_i': None},
 {'notice': 'Yellum; xivth cent Folio; ff. 70, in double columns, each full column haying 52 lines. With initials in blue, flourished with red. The volume at',
  'mss': 'royal 15. c. zvi. ff. 86-145.',
  'material': 'yellum',
  'cent': 'xivth',
  'size': 'folio',
  'mss_index': 'royal 15. c. xvi. ff. 86-145',
  'material_class': 'vellum',
  'size_class': 'folio',
  'cent_i': 14},
 {'notice': 'Vellum ; x irth cent. Folio; ff. 61, in doable columns, having 52 lines to ! a column. Written in an Italian hand ; with two illuminated initials (the',
  'mss': 'additional 22,155.',
  'material': 'vellum',
  'cent': 'x irth',
  'size': 'folio',
  'mss_index': 'additional add. 22,155',
  'material_class': 'vellum',
  'size_class': 'folio',
  'cent_i': None},
 {'notice': 'YeUTun ; xvth cent. Bnodeciino ; f if. 1 80^ each page having from 28 to 39 lines. Written in England ; with initials in blue, flooiished with xed, and',
  'mss': 'harley 176.',
  'material': 'yeutun',
  'cent': 'xvth',
  'size': 'bnodeciino',
  'mss_index': 'harley 176',
  'material_class': None,
  'size_class': None,
  'cent_i': 15},
 {'notice': 'Vellum; xvth cent. Folio; flf. 88, in double columns, each column having 43 lines. Written in Italy; with initials in blue and red, and an',
  'mss': 'harley 3637.',
  'material': 'vellum',
  'cent': 'xvth',
  'size': 'folio',
  'mss_index': 'harley 3637',
  'material_class': 'vellum',
  'size_class': 'folio',
  'cent_i': 15},
 {'notice': 'Vellum; xvthcent. Quarto; ff. 106,haYing firom d0to36 lines to a page. Written in England ; with initials in blue and red.',
  'mss': 'royal 12. d. iii. & 38-143.',
  'material': 'vellum',
  'cent': 'xvth',
  'size': 'quarto',
  'mss_index': 'royal 12. d. iii. ff. 38-143',
  'material_class': 'vellum',
  'size_class': 'quarto',
  'cent_i': 15},
 {'notice': 'Vellum; xvth cent Folio; ffl 77, hATing 41 to 48 lines to a page. Written in England; with initials in red.',
  'mss': 'royal 13. c. zii. ff. 6-82 b.',
  'material': 'vellum',
  'cent': 'xvth',
  'size': 'folio',
  'mss_index': 'royal 13. c. xii. ff. 6-32 b',
  'material_class': 'vellum',
  'size_class': 'folio',
  'cent_i': 15},
 {'notice': 'Yellom; xvth cent. Octayo; £f. 145^ each page having from 25 to S7 lines. Written in England. At the beginning is the signature of "William',
  'mss': 'arundel 174.',
  'material': 'yellom',
  'cent': 'xvth',
  'size': 'octayo',
  'mss_index': 'arundel 174',
  'material_class': 'vellum',
  'size_class': 'octavo',
  'cent_i': 15},
 {'notice': 'Paper and yellum, every eight leaves of paper being enclosed between two of yellum; late xvth cent Quarto; ff. 175, each page having 28 to 35',
  'mss': 'harley 4387.',
  'material': 'paper and yellum, every eight leaves of paper being enclosed between two of yellum',
  'cent': 'late xvth',
  'size': 'quarto',
  'mss_index': 'harley 4387',
  'material_class': 'paper',
  'size_class': 'quarto',
  'cent_i': 15},
 {'notice': 'Paper; late xvth cent. Folio; ff. 140, haying SO to 36 lines to a full page. With initials in red. In a foreign hand.',
  'mss': 'harley 3681.',
  'material': 'paper',
  'cent': 'late xvth',
  'size': 'folio',
  'mss_index': 'harley 3681',
  'material_class': 'paper',
  'size_class': 'folio',
  'cent_i': 15},
 {'notice': 'Vellum; late xvth cent Folio; ft 100, in double oolumns. Written in two different French hands, a full column of the one (ft 18-24 b) containing',
  'mss': 'royal 16. f. iz.',
  'material': 'vellum',
  'cent': 'late xvth',
  'size': 'folio',
  'mss_index': 'royal 16. f. ix.',
  'material_class': 'vellum',
  'size_class': 'folio',
  'cent_i': 15},
 {'notice': 'Paper; about aj>. 1500. Quarto; ff. 243, baying from 28 to 31 lines to a fall page. Written by a French hand ; with initials in bine and red.',
  'mss': 'additional 9785.',
  'material': 'paper',
  'cent': 'about aj 1500',
  'size': 'quarto',
  'mss_index': 'additional add. 9785',
  'material_class': 'paper',
  'size_class': 'quarto',
  'cent_i': 15},
 {'notice': 'Paper ; xYith oeni Octayo ; f f. 4, each full page having 28 to 80 Imes. With the first initial of the rubric in bine, and the first initial of the yerses',
  'mss': 'lansdowne 380. ff. 36-39 b.',
  'material': 'paper',
  'cent': 'x',
  'size': 'yith oeni octayo',
  'mss_index': 'lansdowne 380. ff. 36-39 b',
  'material_class': 'paper',
  'size_class': None,
  'cent_i': None},
 {'notice': 'Paper; xTth cent Folio; ft 101, in double colnznns, each oolmnn having 40 lines. With initialB in red.',
  'mss': 'arundel 6. ff. 242-^42 b.',
  'material': 'paper',
  'cent': 'xtth',
  'size': 'folio',
  'mss_index': 'arundel 6 ff. 242-342 b',
  'material_class': 'paper',
  'size_class': 'folio',
  'cent_i': None},
 {'notice': 'Vellum; znrth cent. Folio; one leaf in double columns, each column having 42 lines. With initials in red and blue.',
  'mss': 'lansdowne 229. f. 164.',
  'material': 'vellum',
  'cent': 'znrth',
  'size': 'folio',
  'mss_index': 'lansdowne 229. ff. 164',
  'material_class': 'vellum',
  'size_class': 'folio',
  'cent_i': None},
 {'notice': 'Paper; ajd. 1679. Folio ; f f. 65, haying 37 to 89 lines to a page. With initials in red and green. Forming the first of five sagas, written by J6n',
  'mss': 'additional 4869. «. 2-66.',
  'material': 'paper',
  'cent': 'ajd 1679',
  'size': 'folio',
  'mss_index': 'additional add. 4869. ff. 2-66',
  'material_class': 'paper',
  'size_class': 'folio',
  'cent_i': 17},
 {'notice': 'Paper; xvnith cent. Folio; fif. Ill, each page haying from 17 to 21 lines, in which the yerses are written like prose.',
  'mss': 'additional 11,113. ff. i7i-28i.',
  'material': 'paper',
  'cent': 'xvnith',
  'size': 'folio',
  'mss_index': 'additional add. 11,113. ff. 171-281',
  'material_class': 'paper',
  'size_class': 'folio',
  'cent_i': 1},
 {'notice': 'Vellmn; xrth cent Folio; ff. 368, in doable columns, each column haying 30 lines. With illuminated initials, and with 65 miniatures, three',
  'mss': 'royal 17. e. ii.',
  'material': 'vellmn',
  'cent': 'xrth',
  'size': 'folio',
  'mss_index': 'royal 17. e. ii.',
  'material_class': 'vellum',
  'size_class': 'folio',
  'cent_i': None},
 {'notice': 'Yellmn ; early xrth cent. The date 1374 in the colophon seems to be copied from an earlier MS. Folio ; f f. 90 of verse, having four stanzas',
  'mss': 'additional 21,240.',
  'material': 'yellmn',
  'cent': 'early xrth',
  'size': 'the date 1374 in the colophon seems to be copied from an earlier ms folio',
  'mss_index': 'additional add. 21,246',
  'material_class': 'vellum',
  'size_class': 'folio',
  'cent_i': None},
 {'notice': 'Vellum; early xvth cent. Small Folio; with the top margin clipped close; ff. 98, each full page having six scTen-line stanzas. With illtuninated',
  'mss': 'harley 2280.',
  'material': 'vellum',
  'cent': 'early xvth',
  'size': 'small folio',
  'mss_index': 'harley 2280',
  'material_class': 'vellum',
  'size_class': 'folio',
  'cent_i': 15},
 {'notice': 'Vellmn; xvth cent. Quarto; fif. 118, each page, except f. 112, having five seven-line stanzas. With initials in blue and red. At the beginning of',
  'mss': 'additional 12,044.',
  'material': 'vellmn',
  'cent': 'xvth',
  'size': 'quarto',
  'mss_index': 'additional add. 12,044',
  'material_class': 'vellum',
  'size_class': 'quarto',
  'cent_i': 15},
 {'notice': 'Paper and yeUnm, four leaves of paper being endoeed between each pair of velltun leaves; xvth cent. Small Quarto; ff. 145, each fall page liaving',
  'mss': 'harley 2392.',
  'material': 'paper and yeunm, four leaves of paper being endoeed between each pair of velltun leaves',
  'cent': 'xvth',
  'size': 'small quarto',
  'mss_index': 'harley 2392',
  'material_class': 'paper',
  'size_class': 'quarto',
  'cent_i': 15},
 {'notice': 'Vellmn; xvth cent Oblong Folio; ff. 62, each fnll page having nine seven-line stanzas. With initials in red and bine; and an illuminated',
  'mss': 'harley 1239. ff. i-62 b.',
  'material': 'vellmn',
  'cent': 'xvth',
  'size': 'oblong folio',
  'mss_index': 'harley 1239. ff. 1-62 b',
  'material_class': 'vellum',
  'size_class': 'folio',
  'cent_i': 15},
 {'notice': 'Vellum; xvth cent Folio; ff. 75, each full page having five Beven-Une stanzas. On the fly-leaf at the banning are the names, Anno Norree, Anne',
  'mss': 'harley 4912.',
  'material': 'vellum',
  'cent': 'xvth',
  'size': 'folio',
  'mss_index': 'harley 4912',
  'material_class': 'vellum',
  'size_class': 'folio',
  'cent_i': 15},
 {'notice': "' Y elliun; late xvth cent Folio; ff. 189, in doable coliunns, each fall colTmuD hATing 52 lines. With illuminated initials, and with an illuminated",
  'mss': 'royal 18. d. vi.',
  'material': "' y elliun",
  'cent': 'late xvth',
  'size': 'folio',
  'mss_index': 'royal 18. d. vi.',
  'material_class': 'vellum',
  'size_class': 'folio',
  'cent_i': 15},
 {'notice': 'Yellnm; about a.d. 1460. Folio; ff. 141, in double columns, each fall colunm having 40 to 52 lines. With illuminated initials, and one border,',
  'mss': 'royal 18. d. ii. ff. 6-146.',
  'material': 'yellnm',
  'cent': 'about ad 1460',
  'size': 'folio',
  'mss_index': 'royal 18. d. ii. ff. 6-146',
  'material_class': 'vellum',
  'size_class': 'folio',
  'cent_i': 15},
 {'notice': 'Vellum; luvth cent. FoUo; ff. 78, in doable columns, each column having M lines, except in the case of the first column, where (owing to the',
  'mss': 'additional 14,100.',
  'material': 'vellum',
  'cent': 'luvth',
  'size': 'fouo',
  'mss_index': 'additional add. 14,100',
  'material_class': 'vellum',
  'size_class': 'folio',
  'cent_i': 5},
 {'notice': 'Vellum; xrth cent Slmall Quarto; ff. 84, each page haying 26 to 33 lines. With initials in blue, flourished with red. At the beginning of the',
  'mss': 'harley 525. ff. 1-34 b.',
  'material': 'vellum',
  'cent': 'xrth',
  'size': 'slmall quarto',

In [40]:
import pandas as pd
notices_df=pd.DataFrame(notices)
display(notices_df[['mss_index',"material_class","size_class", 'cent_i']])

                              mss_index material_class size_class  cent_i
0        royal 16. c. xxiii. ff. 2-69 b         vellum     quarto    15.0
1                royal 16. c. iv. a. b.          paper     quarto    16.0
2               royal 16. d. iii. a. b.          paper       None     6.0
3                 harley 5662. ff. 1-56          paper     quarto    15.0
4                additional add. 15,429          paper     octavo    15.0
..                                  ...            ...        ...     ...
400               additional add. 30864         vellum     quarto     5.0
401      additional add. 31042 ff 50-66          paper     quarto     NaN
402               additional add. 30864          paper     quarto     NaN
403  additional add. 31042 ff 125-163 b          paper     quarto    15.0
404            harley 4690. ff. 106-115         vellum      folio    15.0

[405 rows x 4 columns]

In [41]:
df_all=df_table.merge(notices_df, on="mss_index", how='left')
display(df_all)

,title_theme,title_index,author,theme,cycle,collection,mss_ff,mss_x,ff,page,mss_index,notice,mss_y,material,cent,size,material_class,size_class,cent_i
0,heroica,heroica,flavius philostratus,classical romances,cycle of troy,royal,16. c. xxiii. ff. 2-69 b,16. c. xxiii.,ff. 2-69 b,1,royal 16. c. xxiii. ff. 2-69 b,"Vellxun; xvth cent. Small Qnarto; ff. 68, with...",royal 16. c. zxiii. ff. 2-69 b.,vellxun,xvth,small qnarto,vellum,quarto,15.0
1,iliaca,iliaca,joannes tzetzes,classical romances,cycle of troy,royal,16. c. iv. a. b.,16. c. iv. a. b.,None,2,royal 16. c. iv. a. b.,"Paper ; t wo vols., a.d. 1560 and 1565. Small ...",royal 16* c. iv. a. b.,paper,t wo vols ad 1560 and 1565,small quarto,paper,quarto,16.0
2,iliaca,iliaca,joannes tzetzes,classical romances,cycle of troy,royal,16. d. iii. a. b.,16. d. iii. a. b.,None,2,royal 16. d. iii. a. b.,"Paper; zvith cent. ; t wo vol& Folio; ff. 160,...",royal 16. d. iii. a. b.,paper,zvith,,paper,None,6.0
3,iliaca,iliaca,joannes tzetzes,classical romances,cycle of troy,harley,harley 5662. ff. 1-56,harley 5662.,ff. 1-56,2,harley 5662. ff. 1-56,"Paper; xvth cent Quarto; ff. 56, with 15 lines...",harley 6662. «. i-56.,paper,xvth,quarto,paper,quarto,15.0
4,dictys cretensis,dictys cretensis,None,classical romances,cycle of troy,harley,harley 3514,harley 3514,None,9,harley 3514,"Vellum; xvth cent. Octavo; ff. 102, having 23 ...",harley 3514.,vellum,xvth,octavo,vellum,octavo,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
617,None,a propecye,None,None,None,additional,add. 27879 f 239 b,add. 27879 f 239 b,None,327,additional add. 27879 f 239 b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
618,None,robin hood's garland,None,None,None,additional,add. 28638,add. 28638,None,520,additional add. 28638,"Paper ; about 1735. Quarto ; f f. 21, having f...","additional 28,638.",paper,about 1735,quarto,paper,quarto,18.0
619,None,ballads of scotland,None,None,None,additional,"add. 29408, 29409","add. 29408, 29409",None,537,"additional add. 29408, 29409",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
620,None,two charlemagne romances,None,None,None,additional,"add. 31042 ff 66 b-79 b, 82-94",add. 31042,"ff66 b-79 b, 82-94",953,"additional add. 31042 ff 66 b-79 b, 82-94",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
621,None,ipomedon and prothesilaus,None,None,None,egerton,egerton 2515 ff. 3-141,egerton 2515,ff. 3-141,746,egerton 2515 ff. 3-141,"Vellnm ; e arly xiy th cent. Folio ; S . 139, ...",egerton 2516. ff. 3-i4i.,vellnm,e arly xiy th,folio,vellum,folio,NaN

## test:

In [3]:
index_table = {
  "Royal": [
    {"name": "Historia Regum Britanniae", "page": 227, "mss": "4. C. xi. ff. 222-249"},
    {"name": "Turpin's Chronicle", "page": 583, "mss": "4. C. xi. ff. 280-286 b"},
    {"name": "Prophecy of Merlin Silvester", "page": 313, "mss": "5. F. xv. ff. 3 b"},
    {"name": "Dares Phrygius", "page": 17, "mss": "6. C. viii. ff. 123-133 b"},
    {"name": "Letters between Alexander and Dindimus", "page": 138, "mss": "6. E. iii. ff. 111 b-112 b"},
    {"name": "Letters between Alexander and Dindimus", "page": 137, "mss": "7. A. i. ff. 68 b-69 b"},
    {"name": "Alexandreis", "page": 98, "mss": "8. B. iv. ff. 19-71 b"},
    {"name": "Prophecies of Merlin", "page": 297, "mss": "8. D. iii. ff. 160 b-163"},
    {"name": "Guy of Warwick", "page": 485, "mss": "8. F. ix. ff. 105-159"},
    {"name": "Prophecy on Scotland", "page": 327, "mss": "9. B. ix. ff. 2"},
    {"name": "Dares Phrygius", "page": 20, "mss": "10. A. x. ff. 188-192 b"},
    {"name": "Alexander the Great", "page": 112, "mss": "12. C. iv. ff. 138-170"},
    {"name": "Prophecy", "page": 316, "mss": "12. C. xii. ff. 14-16 b"},
    {"name": "Fulk Fitz-Warin", "page": 501, "mss": "12. C. xii. ff. 33-60 b"},
    {"name": "Amya and Amylion", "page": 674, "mss": "12. C. xii. ff. 69-76"},
    {"name": "Tale of Two Lovers", "page": 801, "mss": "12. C. xx. ff. 17-46"},
    {"name": "Historia Trojana", "page": 49, "mss": "12. D. iii. ff. 38-143"},
    {"name": "Story of Troy", "page": 34, "mss": "12. D. iii. ff. 152 b-158"},
    {"name": "Alexander the Great", "page": 106, "mss": "13. A. i."},
    {"name": "Historia Regum Britanniae", "page": 237, "mss": "13. A. iii. ff. 1-133"},
    {"name": "Prophecy of Merlin Silvester", "page": 315, "mss": "13. A. iii. ff. 135 b, 136"},
    {"name": "Story of Troy", "page": 27, "mss": "13. A. iv. ff. 22 b-23 b, 76-81 b"},
    {"name": "Alexander the Great", "page": 118, "mss": "13. A. v. ff. 2-23 b"},
    {"name": "Dares Phrygius", "page": 23, "mss": "13. A. v. ff. 88 b-98 b"},
    {"name": "Historia Regum Britanniae", "page": 237, "mss": "13. A. v. ff. 99-161 b"},
    {"name": "Prophecy of the Tenth Sibyl", "page": 194, "mss": "13. A. xiv. ff. 244-247"},
    {"name": "Karolellus", "page": 594, "mss": "13. A. xviii. ff. 136-149 b"},
    {"name": "Roman de Brut", "page": 264, "mss": "13. A. xxi. ff. 40 b-113"},
    {"name": "Havelok", "page": 423, "mss": "13. A. xxi. ff. 113-117 b"},
    {"name": "Havelok", "page": 940, "mss": "13. A. xxi. ff. 113-117 b"},
    {"name": "Historia Trojana", "page": 50, "mss": "13. C. xii. ff. 6-32 b"},
    {"name": "Alexander the Great", "page": 122, "mss": "13. C. xii. ff. 82-109 b"},
    {"name": "Historia Regum Britanniae", "page": 248, "mss": "13. D. i. ff. 175-212 b"},
    {"name": "Turpin's Chronicle", "page": 572, "mss": "13. D. i. ff. 212 b-222"},
    {"name": "Historia Regum Britanniae", "page": 228, "mss": "13. D. ii. ff. 124-173 b"},
    {"name": "Historia Regum Britanniae", "page": 229, "mss": "13. D. v. ff. 1-37 b"},
    {"name": "Vita Merlini", "page": 289, "mss": "13. E. i. ff. 143-146"},
    {"name": "Prophecies of Merlin Silvester", "page": 314, "mss": "13. E. ix. ff. 27"},
    {"name": "Historia Regum Britannia", "page": 238, "mss": "14. C. i. ff. 80-137"},
    {"name": "Apollonius of Tyre", "page": 170, "mss": "14. C. xi. ff. 80-83 b"},
    {"name": "Le Chemin de Vaillance", "page": 895, "mss": "14. E. ii. ff. 1-293"},
    {"name": "Livre de l'Ordre de Chevalerie", "page": 922, "mss": "14. E. ii. ff. 337-353 b"},
    {"name": "Saint Graal", "page": 341, "mss": "14. E. iii. ff. 3-88 b"},
    {"name": "Lancelot du Lac", "page": 354, "mss": "14. E. iii. ff. 89-161 b"},
    {"name": "Alexandreis", "page": 94, "mss": "15. A. x. ff. 2-89"},
    {"name": "Dares Phrygius", "page": 13, "mss": "15. A. xxii. ff. 73-90"},
    {"name": "Prophecy of the Tenth Sibyl", "page": 194, "mss": "15. A. xxii. ff. 110-115"},
    {"name": "Dares Phrygius", "page": 14, "mss": "15. B. xi. ff. 57-66 b"},
    {"name": "Prophecy of the Tenth Sibyl", "page": 193, "mss": "15. B. xi. ff. 67-69"},
    {"name": "Alexander the Great", "page": 110, "mss": "15. C. vi. ff. 102 b-130 b"},
    {"name": "Historia Trojana", "page": 44, "mss": "15. C. xvi. ff. 86-145"},
    {"name": "Historia Regum Britannia", "page": 239, "mss": "15. C. xvi. ff. 146-183 b"},
    {"name": "Prophecies of Merlin Silvester", "page": 313, "mss": "15. C. xvi. ff. 183 b, 184"},
    {"name": "Perceforest", "page": 377, "mss": "15. E. v."},
    {"name": "Alexander the Great", "page": 129, "mss": "15. E. vi. ff. 4 b-24 b"},
    {"name": "Simon de Pouille", "page": 627, "mss": "15. E. vi. ff. 25-42 b"},
    {"name": "Aspremont", "page": 598, "mss": "15. E. vi. ff. 43-69 b"},
    {"name": "Fierabras", "page": 615, "mss": "15. E. vi. ff. 70-85 b"},
    {"name": "Ogier le Danois", "page": 604, "mss": "15. E. vi. ff. 86-154 b"},
    {"name": "Quatre fils Aimon", "page": 622, "mss": "15. E. vi. ff. 155-206"},
    {"name": "Pontus and Sidoine", "page": 469, "mss": "15. E. vi. ff. 207-226 b"},
    {"name": "Guy of Warwick and Heraud of Ardennes", "page": 487, "mss": "15. E. vi. ff. 227-272"},
    {"name": "Knight of the Swan", "page": 708, "mss": "15. E. vi. ff. 273-292"},
    {"name": "Iliaca", "page": 2, "mss": "16. C. iv. A. B."},
    {"name": "Heroica", "page": 1, "mss": "16. C. xxiii. ff. 2-69 b"},
    {"name": "Iliaca", "page": 6, "mss": "16. D. iii. A. B."},
    {"name": "Titus and Vespasian", "page": 176, "mss": "16. E. viii. ff. 73-102 b"},
    {"name": "Voyage of Charlemagne to Jerusalem and Constantinople", "page": 625, "mss": "16. E. ff. 131-144 b"},
    {"name": "Sydrac and Boctus", "page": 914, "mss": "16. F. v. ff. 1-113 b"},
    {"name": "Historia Trojana", "page": 54, "mss": "16. F. ix."},
    {"name": "Quatre fils Aimon", "page": 619, "mss": "16. G. ii."},
    {"name": "Sir Gowghter", "page": 419, "mss": "17. B. xliii. ff. 116-131 b"},
    {"name": "Tale of Gamelyn", "page": 515, "mss": "17. D. xv. ff. 66 b-79 b"},
    {"name": "Recueil des Histoires de Troie", "page": 64, "mss": "17. E. ii."},
    {"name": "Mélusine", "page": 690, "mss": "18. B. ii."},
    {"name": "Tale of Gamelyn", "page": 514, "mss": "18. C. ii. ff. 56 b-67 b"},
    {"name": "Troy Book", "page": 81, "mss": "18. D. ii. ff. 6-146"},
    {"name": "Romance of Thebes", "page": 90, "mss": "18. D. ii. ff. 147 b-162"},
    {"name": "Troy Book", "page": 79, "mss": "18. D. vi."},
    {"name": "Roman de la Rose", "page": 885, "mss": "19. A. xviii."},
    {"name": "Lancelot du Lac", "page": 349, "mss": "19. B. vii."},
    {"name": "Roman de la Rose", "page": 888, "mss": "19. B. xii. ff. 2-147 b"},
    {"name": "Roman de la Rose", "page": 874, "mss": "19. B. xiii."},
    #{"name": "Lancelot du Lac", "page": 350, "mss": "19. D. i."},
    #{"name": "Morte Arthur", "page": 366, "mss": "19. D. ii."},
    #{"name": "Saint Graal", "page": 340, "mss": "19. D. iii."},
    #{"name": "Quest del Saint Graal", "page": 345, "mss": "19. D. iv."},
    #{"name": "Morte Arthur", "page": 363, "mss": "19. D. v."},
    #{"name": "Lancelot du Lac", "page": 351, "mss": "19. D. vi."},
    {"name": "Saint Graal", "page": 342, "mss": "19. C. vii."}, # pb un C. et pas un D.
    {"name": "Lancelot du Lac", "page": 345, "mss": "19. C. viii."},
    #{"name": "Morte Arthur", "page": 364, "mss": "19. D. ix."},
    #{"name": "Merlin", "page": 384, "mss": "19. D. x."},
#     {"name": "Roman de la Rose", "page": 886, "mss": "19. E. i."},
#     {"name": "Roman de la Rose", "page": 887, "mss": "19. E. ii."},
#     {"name": "Roman de la Rose", "page": 889, "mss": "19. E. iii."},
#     {"name": "Alexander the Great", "page": 108, "mss": "20. A. ii."},
#     {"name": "Letters between Alexander and Dindimus", "page": 188, "mss": "20. A. v. ff. 30-31 b"},
#     {"name": "Iliaca", "page": 3, "mss": "20. A. vi."},
#     {"name": "Iliaca", "page": 4, "mss": "20. A. x."},
#     {"name": "Iliaca", "page": 5, "mss": "20. A. xi."},
#     {"name": "Roman de la Rose", "page": 873, "mss": "20. B. i."},
#     {"name": "Roman de la Rose", "page": 876, "mss": "20. B. xi."},
#     {"name": "Roman de la Rose", "page": 874, "mss": "20. B. xii."}
#ajouts
    {"name": "Alexander the Great", "page": 123, "mss": "19. D. i. ff. 1-46"},
    {"name": "La Vengeance d'Alexandre", "page": 143, "mss": "19. D. i. ff. 47-57"},
    {"name": "Perceforest", "page": 377, "mss": "19. E. ii."},
    {"name": "Perceforest", "page": 377, "mss": "19. E. iii."},
    {"name": "Alexander the Great", "page": 125, "mss": "20. A. v."},
    {"name": "Roman de la Rose", "page": 880, "mss": "20. A. xvii."},
    {"name": "Lancelot du Lac", "page": 349, "mss": "20. B. xix."},
    {"name": "Guillaume d'Orange", "page": 654, "mss": "20. B. xix."},
    {"name": "Alexander the Great", "page": 128, "mss": "20. B. xx."},
    {"name": "Cleriadus et Meliadice", "page": 383, "mss": "20. C. ii. ff. 1-209 b"},
    {"name": "Apollonius of Tyre", "page": 166, "mss": "20. C. ii. ff. 210-236"},
    {"name": "Lancelot du Lac", "page": 350, "mss": "20. C. vi."},
    {"name": "Tristram", "page": 361, "mss": "20. D. ii."},
    {"name": "Lancelot du Lac", "page": 353, "mss": "20. D. iii."},
    {"name": "Lancelot du Lac", "page": 351, "mss": "20. D. iv."},
    {"name": "Roman de la Rose", "page": 889, "mss": "20. D. vii."},
    {"name": "Guillaume d'Orange", "page": 632, "mss": "20. D. xi."},
  ],
  "Cotton": [
    # il en manque une demi page
    {"name": "Prophecies of Merlin", "page": 299, "mss": "Julius A. v. ff. 5, 53-57b, 177 b-179, and 180-181 b"},  # faut-il rapprocher Prophecy of Merlin de Prophecies of Merlin?
    {"name": "Gesta Regum Britannia", "page": 274, "mss": "Julius D. xi. ff. 2-60"},  # pb le ae qui est mangé
    {"name": "Vita Merlini", "page": 289, "mss": "Julius E. viii. ff. 12 b-17 b"}, 
    {"name": "Troy Book", "page": 75, "mss": "Augustus A. iv."}, 
    {"name": "Prophecies of Merlin", "page": 295, "mss": "Tiberius A. ix. ff. 2-6"},
    {"name": "Sir Eglamour of Artois", "page": 766, "mss": "Caligula A. ii. ff. 5 b-13"}, 
    {"name": "Octavian the Emperor", "page": 762, "mss": "Caligula A. ii. ff. 22 b-35"}, 
    {"name": "Sir Launfal", "page": 416, "mss": "Caligula A. ii. ff. 35 b-42 b"}, 
    {"name": "Lybeaus Desconus", "page": 400, "mss": "Caligula A. ii. ff. 42 b-57"}, 
    {"name": "Emare", "page": 418, "mss": "Caligula A. ii. ff. 71-76 b"}, 
    {"name": "Titus and Vespasian", "page": 180, "mss": "Caligula A. ii. ff. 111-125"}, 
    {"name": "Knight of the Swan", "page": 710, "mss": "Caligula A. ii. ff. 125 b-129 b"}, 
    {"name": "Sir Isumbras", "page": 760, "mss": "Caligula A. ii. ff. 130-134"}, 
    {"name": "Lazamon's Brut", "page": 268, "mss": "Caligula A. ix. ff. 3-194 b"}, 
    {"name": "Prophecy of the Tenth Sibyl", "page": 195, "mss": "Caligula A. x. ff. 200-204"}, 
    {"name": "Turpin's Chronicle", "page": 561, "mss": "Caligula B. vii. ff. 192-203 b"}, 
    {"name": "Prophecy of Merlin", "page": 303, "mss": "Caligula B. vii. ff. 210-213"},
    {"name": "Dares Phrygius", "page": 22, "mss": "Caligula B. vii. ff. 214-218 b"}, 
    {"name": "Prophecy of the Tenth Sibyl", "page": 193, "mss": "Caligula B. vii. ff. 219, 220"},
    {"name": "Prophecies of Merlin", "page": 296, "mss": "Caligula B. vii. ff. 220 b-231 b"},
    {"name": "Prophecies", "page": 317, "mss": "Claudius E. viii. ff. 1 b, 23"},
    {"name": "Prophecies of Merlin", "page": 297, "mss": "Nero A. iv. ff. 63-76 b"},
    {"name": "Sir Gawain and the Green Knight", "page": 387, "mss": "Nero A. x. ff. 90 b-126"}, 
    {"name": "Turpin's Chronicle", "page": 546, "mss": "Nero A. xi. ff. 8-63"},
    {"name": "Turpin's Chronicle", "page": 950, "mss": "Nero A. xi. ff. 8-63"},


    {"name": "Historia Regum Britanniae", "page": 230, "mss": "Nero D. viii. ff. 3-63"},
    {"name": "Alexander the Great", "page": 113, "mss": "Nero D. viii. ff. 160-174 b"},
    {"name": "Story of Albina and her Sisters", "page": 199, "mss": "Nero D. viii. ff. 186, 187"},
    {"name": "Petit Jean de Saintré", "page": 775, "mss": "Nero D. ix. ff. 1-108"},
    {"name": "Floridam and Elluide", "page": 779, "mss": "Nero D. ix. ff. 109-115"},
    {"name": "Ywain and Gawain", "page": 392, "mss": "Galba E. ix. ff. 4-25"},
    {"name": "Merlin's Prophecy of the Six Kings", "page": 309, "mss": "Galba E. ix. ff. 49, 50"},
    {"name": "Historia Regum Britanniae", "page": 239, "mss": "Galba E. xi. ff. 2-58 b"},
    {"name": "Letters of Dindimus to Alexander the Great", "page": 136, "mss": "Galba E. xi. ff. 98 b-101 b"},
    {"name": "Alexander the Great", "page": 115, "mss": "Galba E. xi. ff. 111-125"},
    {"name": "Lisamon's Brut", "page": 271, "mss": "Otho C. xiii."},
    {"name": "Roman de Brut", "page": 259, "mss": "Vitellius A. x. ff. 19-114 b"},
    {"name": "Dares Phrygius", "page": 15, "mss": "Vitellius A. xiii. ff. 90"},
    {"name": "Marvels of India", "page": 134, "mss": "Vitellius A. xv. ff. 109-133 b"},
    {"name": "Dares Phrygius", "page": 18, "mss": "Vitellius C. viii. ff. 5 b-6 b"},
    {"name": "Floyras and Blanchefleur", "page": 716, "mss": "Vitellius D. iii. ff. 6-8 b"},
    {"name": "Thomas of Erceldoune", "page": 330, "mss": "Vitellius E. x. ff. 240 b-243"},
    {"name": "Ipomodon", "page": 728, "mss": "Vespasian A. vii. ff. 37-104"},
    {"name": "Brutus", "page": 277, "mss": "Vespasian A. x. ff. 44 b-51"},
    {"name": "Turpin's Chronicle", "page": 576, "mss": "Vespasian A. xiii. ff. 94-114 b"},
    {"name": "Apollonius of Tyre", "page": 164, "mss": "Vespasian A. xiii. ff. 132-147 b"},
    {"name": "Historia Regum Britanniae", "page": 241, "mss": "Vespasian A. xxiii. ff. 4-106 b"},
    {"name": "Lanval", "page": 415, "mss": "Vespasian B. xiv. ff. 1-8 b"},
    {"name": "Fall of Troy", "page": 31, "mss": "Vespasian B. xiv. ff. 18, 18 b"},
    {"name": "Fall of Troy and Adventures of Æneas", "page": 33, "mss": "Vespasian B. xxiii. Part III. ff. 118 b-122 b"},
    {"name": "Dares Phrygius", "page": 12, "mss": "Vespasian B. xxv. ff. 98 b-117"},
    {"name": "Prophecy of the Tenth Sibyl", "page": 192, "mss": "Vespasian B. xxv. ff. 117 b-123"},
    {"name": "Guy of Warwick", "page": 492, "mss": "Vespasian D. ix. ff. 40-43 b"},
    {"name": "Two Prophecies", "page": 325, "mss": "Vespasian D. xviii. ff. 125 b-127* b"},
    {"name": "Vita Merlini", "page": 278, "mss": "Vespasian E. iv. ff. 112 b-138 b"},
    {"name": "Prophecy of the Tenth Sibyl", "page": 194, "mss": "Vespasian E. iv. ff. 143-147"},
    {"name": "Prophecies of Merlin, etc.", "page": 320, "mss": "Vespasian E. vii. ff. 78-126, 129, 130"},
    {"name": "Whole Prophecy of Scotland", "page": 337, "mss": "Vespasian E. viii. ff. 16-29"},
    {"name": "Historia Regum Britanniae", "page": 242, "mss": "Vespasian E. x. ff. 271-368 b"},
    {"name": "Story of Albina and her Sisters", "page": 200, "mss": "Vespasian E. x. ff. 390 b-392"},
    {"name": "Titus and Vespasian", "page": 185, "mss": "Vespasian E. xvi. ff. 70-75 b"},
    {"name": "Historia Regum Britanniae", "page": 243, "mss": "Titus A. xviii. ff. 13-82"},
    {"name": "Turpin's Chronicle", "page": 578, "mss": "Titus A. xix. ff. 24-43"},
    {"name": "Vita Merlini", "page": 290, "mss": "Titus A. xix. ff. 63-73 b"},
    {"name": "Story of Albina and her Sisters", "page": 201, "mss": "Titus A. xix. ff. 103"},
    {"name": "Battle of Roncevaux", "page": 630, "mss": "Titus A. xix. ff. 153-155"},
    {"name": "Story of Troy and Adventures of Æneas", "page": 29, "mss": "Titus A. xx. ff. 99-104"},
    {"name": "Historia Regum Britanniae", "page": 244, "mss": "Titus A. xxv. ff. 105-116 b"},
    {"name": "Historia Regum Britanniae", "page": 231, "mss": "Titus A. xxvii. ff. 1 b-87"},
    {"name": "Historia Regum Britanniae", "page": 203, "mss": "Titus C. xvii."},
    {"name": "Apollonius of Tyre", "page": 169, "mss": "Titus D. iii. ff. 127-137 b"},
    {"name": "Prophecy of the Tenth Sibyl", "page": 191, "mss": "Titus D. iii. ff. 143-147 b"},
    {"name": "Prophecy of Merlin", "page": 301, "mss": "Titus D. vii. ff. 26-36"},
    {"name": "Prophecies", "page": 319, "mss": "Titus D. xix. ff. 118"},
    {"name": "Prophecy of the Tenth Sibyl", "page": 193, "mss": "Domitian xiii. ff. 104-107"},
    {"name": "Prophecy of the Tenth Sibyl", "page": 195, "mss": "Domitian xiii. ff. 132 b-134 b"},

    {"name": "Fall of Troy", "page": 30, "mss": "Cleopatra A. viii. ff. 56-58"},
    {"name": "Brut y Brenhinoedd", "page": 255, "mss": "Cleopatra B. v. ff. 1-108 b"},
    {"name": "Dares Phrygius", "page": 26, "mss": "Cleopatra B. v. ff. 222-250"},
    {"name": "Prophecies of Merlin", "page": 310, "mss": "Cleopatra C. iv. ff. 74-122"},
    
    # aie.... plein de changements ici
    
    {"name": "Prophecy of Merlin", "page": 298, "mss": "Cleopatra C. iv. ff. 55 b and 66-68 b"},
    #{"name": "Prophecy of the Lily, the Lion, and the Son of Man", "page": 318, "mss": "Cleopatra D. iii. f. 184"},
    {"name": "Prophecy of the Lily, the Lion, and the Son of Man", "page": 318, "mss": "Cleopatra D. iii. ff. 184"},
    {"name": "Alexander the Great", "page": 114, "mss": "Cleopatra D. v. ff. 165 b-183"},
    {"name": "Story of Albina and her Sisters", "page": 200, "mss": "Cleopatra D. viii. ff. 3 b-5"},
    {"name": "Historia Regum Britanniae", "page": 249, "mss": "Cleopatra D. viii. ff. 8-94"},
    {"name": "Story of Albina and her Sisters", "page": 198, "mss": "Cleopatra D. ix. ff. 67, 68"},
    {"name": "Prophecies of Merlin", "page": 292, "mss": "Faustina A. viii. ff. 109 b-116"},
    {"name": "Meriadoc and Gawain", "page": 374, "mss": "Faustina B. vi. ff. 2-40 b"},
    {"name": "Prophecies", "page": 319, "mss": "Faustina B. ix. ff. 241 b, 242"},
    {"name": "Prophecies of Merlin Silvester", "page": 315, "mss": "Cotton Appendix iv. ff. 102 b"},
    {"name": "Romance of Thebes", "page": 91, "mss": "Cotton Appendix xxvii. ff. 11-61; formerly ff. 106-130 b, and xxxix. ff. 80-103 b"},
    {"name": "Four Prophecies", "page": 324, "mss": "Cotton Roll ii. 23"}
  ],
  "Harley": [
    {"name": "Tristram", "page": 358, "mss": "Harley 49"},
    {"name": "Historia Trojana", "page": 52, "mss": "Harley 51. ff. 3-105 b"},
    {"name": "Turpin's Chronicle", "page": 574, "mss": "Harley 108. ff. 4 b-31 b"},
    {"name": "Historia Trojana", "page": 47, "mss": "Harley 176"},
    {"name": "Historia Regum Britanniae", "page": 222, "mss": "Harley 225. ff. 3-78"},
    {"name": "Turpin's Chronicle", "page": 587, "mss": "Harley 273. ff. 86-102 b"},
    {"name": "The Three Kings' Sons", "page": 782, "mss": "Harley 326. ff. 8-123 b"},
    {"name": "Romance of Troy", "page": 84, "mss": "Harley 525. ff. 1-34 b"},
    {"name": "King Robert of Sicily", "page": 765, "mss": "Harley 525. ff. 35-43 b"},
    {"name": "Gui de Bourgogne", "page": 630, "mss": "Harley 527. ff. 1-32"},
    {"name": "Alexander the Great", "page": 113, "mss": "Harley 527. ff. 47-56 b"},
    {"name": "King Horn", "page": 468, "mss": "Harley 527. ff. 59-73 b"},
    {"name": "Historia Regum Britanniae", "page": 226, "mss": "Harley 536. ff. 58-61"},
    {"name": "Political Prophecies", "page": 326, "mss": "Harley 559. ff. 1-13, 31-35, 39-48"},
    {"name": "Dares Phrygius", "page": 20, "mss": "Harley 641. ff. 1-8"},
    {"name": "Vita Merlini", "page": 288, "mss": "Harley 655. ff. 200 b-204 b"},
    {"name": "Merlin's Prophecy of the Six Kings", "page": 309, "mss": "Harley 746. ff. 1 b-3"},
    
    {"name": "Prophecy of Merlin", "page": 302, "mss": "Harley 838. ff. 92-93 b"},
    {"name": "Story of Albina and her Sisters", "page": 201, "mss": "Harley 941. ff. 1-3"},
    {"name": "Lays of Marie de France", "page": 407, "mss": "Harley 978. ff. 118-160"},
    {"name": "Prophecy of the Lily, the Lion, and the Son of Man", "page": 318, "mss": "Harley 1008. ff. 81"},
    {"name": "Sydrac and Boctus", "page": 912, "mss": "Harley 1121. ff. 1-140"},
    {"name": "Troilus and Cryseyde", "page": 73, "mss": "Harley 1239. ff. 1-62 b"},
    {"name": "Guillaume d'Orange", "page": 660, "mss": "Harley 1321"},
    {"name": "Chanson de Brut", "page": 272, "mss": "Harley 1605. Art. I."},
    {"name": "Prophecies de Merlin", "page": 373, "mss": "Harley 1629"},
    {"name": "King Robert of Sicily", "page": 765, "mss": "Harley 1701. ff. 92-95"},
    {"name": "Prophecies of Merlin and others", "page": 312, "mss": "Harley 1717. ff. 249 b-250 b"},
    {"name": "Tale of Gamelyn", "page": 513, "mss": "Harley 1758. ff. 48-55"},
    {"name": "Tale of Two Lovers", "page": 799, "mss": "Harley 1883. ff. 119-135 b"},
    {"name": "Ipomedon", "page": 755, "mss": "Harley 2252. ff. 54-84"},
    {"name": "Morte Arthur", "page": 405, "mss": "Harley 2252. ff. 86-133 b"},
    {"name": "Six Fabliaux", "page": 813, "mss": "Harley 2253. ff. 67 b, 107 b, 110, 115 b, 118, 122 b"},
    {"name": "King Horn", "page": 447, "mss": "Harley 2253. ff. 83-92 b"},
    {"name": "Prophecy of Thomas of Erceldoune", "page": 328, "mss": "Harley 2253. ff. 127, col. 2"},
    {"name": "Troilus and Cryseyde", "page": 70, "mss": "Harley 2280"},
    {"name": "Turpin's Chronicle", "page": 582, "mss": "Harley 2361. ff. 138-139 b"},
    {"name": "Story of Albina and her Sisters", "page": 202, "mss": "Harley 2386. ff. 65 b-67"},
    {"name": "Amys and Amylion", "page": 677, "mss": "Harley 2386. ff. 131-138"},
    {"name": "Troilus and Cryseyde", "page": 73, "mss": "Harley 2392"},
    {"name": "Letter of Dindimus to Alexander the Great", "page": 139, "mss": "Harley 2488. ff. 114-117 b"},
    {"name": "Tale of Two Lovers", "page": 802, "mss": "Harley 2492. ff. 154 b-169 b"},
    {"name": "Turpin's Chronicle", "page": 581, "mss": "Harley 2500. ff. 139-155"},
    {"name": "Aronus and Marina", "page": 797, "mss": "Harley 2678. ff. 93-96 b"},
    {"name": "Alexander the Great", "page": 109, "mss": "Harley 2682. ff. 180-192"},
    {"name": "Turpin's Chronicle", "page": 577, "mss": "Harley 3043. ff. 17-31"},
    {"name": "Fall of Troy", "page": 32, "mss": "Harley 3202. ff. 114 b-115 b"},
    {"name": "Filocolo", "page": 725, "mss": "Harley 3314"},
    {"name": "Dictys Cretensis", "page": 11, "mss": "Harley 3514"},
    {"name": "Corbaccio", "page": 794, "mss": "Harley 3581"},
    {"name": "Fiammetta", "page": 793, "mss": "Harley 3573"},
    {"name": "Historia Trojana", "page": 48, "mss": "Harley 3637"},
    {"name": "Historia Trojana", "page": 54, "mss": "Harley 3681"},
    {"name": "Historia Regum Britanniae", "page": 223, "mss": "Harley 3773. ff. 7-57"},
    {"name": "Guy of Warwick", "page": 471, "mss": "Harley 3775. ff. 15-26 b"},
    {"name": "Life of Harold, King of England", "page": 941, "mss": "Harley 3776. ff. 1-24 b"},
    {"name": "Sir Orpheo", "page": 171, "mss": "Harley 3810. Part I. ff. 1-10"},
    {"name": "Tale of Antiochus", "page": 798, "mss": "Harley 3830. ff. 11 b-17 b"},
    {"name": "Troilus and Cryseyde", "page": 72, "mss": "Harley 3943"},
    {"name": "Florimont", "page": 159, "mss": "Harley 3983. ff. 2-82 b"},
    {"name": "Voeux du Paon", "page": 154, "mss": "Harley 3992"},
    {"name": "Historia Regum Britanniae", "page": 244, "mss": "Harley 4003. ff. 81-141 b"},
    {"name": "Historia Regum Britanniae", "page": 236, "mss": "Harley 4123. ff. 2-49 b"},
    {"name": "Historia Trojana", "page": 40, "mss": "Harley 4123. ff. 50-126"},
    {"name": "Sydrac and Boctus", "page": 918, "mss": "Harley 4294. ff. 1-79 b"},
    {"name": "L'Ordène de Chevalerie", "page": 810, "mss": "Harley 4333. ff. 115-117 b"},
    {"name": "Girard de Roussillon", "page": 663, "mss": "Harley 4334"},
    {"name": "Sydrac and Boctus", "page": 911, "mss": "Harley 4361"},
    {"name": "Historia Trojana", "page": 53, "mss": "Harley 4387"},
    {"name": "Tristram", "page": 356, "mss": "Harley 4389"},
    {"name": "Doon de la Roche", "page": 671, "mss": "Harley 4404. ff. 1-98"},
    {"name": "Enfances Ogier", "page": 610, "mss": "Harley 4404. ff. 102-251 b"},
    {"name": "Sydrac and Boctus", "page": 908, "mss": "Harley 4417. ff. 1-141 b"},
    {"name": "Mélusine", "page": 687, "mss": "Harley 4418"},
    {"name": "Lancelot du Lac", "page": 353, "mss": "Harley 4419"},
    {"name": "Roman de la Rose", "page": 892, "mss": "Harley 4425"},
    {"name": "Roman de Troie", "page": 35, "mss": "Harley 4482"},
    {"name": "Sydrac and Boctus", "page": 913, "mss": "Harley 4486. ff. 69-146"},
    {"name": "Florimont", "page": 156, "mss": "Harley 4487. ff. 3-96"},
    {"name": "Richard Cœur-de-Lion", "page": 949, "mss": "Harley 4690. ff. 106-115"},
    {"name": "Alexandreis", "page": 103, "mss": "Harley 4745"},
    {"name": "Troilus and Cryseyde", "page": 74, "mss": "Harley 4912"},
    {"name": "Alexander the Great", "page": 127, "mss": "Harley 4979"},
    {"name": "Alexander the Great", "page": 119, "mss": "Harley 5054. ff. 124 b-181"},
    {"name": "Historia Regum Britanniae", "page": 245, "mss": "Harley 5115. ff. 87-150"},
    {"name": "Guy of Warwick", "page": 497, "mss": "Harley 5243"},
    {"name": "Fiammetta", "page": 792, "mss": "Harley 5427"},
    {"name": "Alexandreis", "page": 103, "mss": "Harley 5437"},
    {"name": "Iliaca", "page": 8, "mss": "Harley 5662. ff. 1-56"},
    {"name": "Prophecies taken from Geoffrey of Monmouth and others", "page": 311, "mss": "Harley 6148. ff. 86-98 b"},
    {"name": "Merlin", "page": 385, "mss": "Harley 6223. Art. I."},
    {"name": "Merlin", "page": 344, "mss": "Harley 6340"},
    {"name": "Lancelot du Lac", "page": 355, "mss": "Harley 6341"},
    {"name": "Historia Regum Britanniae", "page": 235, "mss": "Harley 6358. ff. 2-58 b"},
    {"name": "Turpin's Chronicle", "page": 560, "mss": "Harley 6358. ff. 60-83"},
    {"name": "Roman de Brut", "page": 263, "mss": "Harley 6508"},
    {"name": "Theagenes and Stelliana", "page": 795, "mss": "Harley 6758"},
    {"name": "Guy of Warwick", "page": 494, "mss": "Harley 7333. ff. 33-35 b"},
    {"name": "Tale of Gamelyn", "page": 508, "mss": "Harley 7334. ff. 59-70 b"}
  ],
  "Lansdowne": [
    {"name": "Kings of Britain", "page": 251, "mss": "Lansdowne 214. ff. 85-193"}, 
    {"name": "Historia Trojana", "page": 61, "mss": "Lansdowne 229. ff. 164"}, 
    {"name": "Florence de Rome", "page": 711, "mss": "Lansdowne 362. ff. 75*, 75**, 76, 77"}, 
    {"name": "Abridgement of Historia Trojana", "page": 59, "mss": "Lansdowne 380. ff. 36-39 b"}, 
    {"name": "Chanson de Roland", "page": 631, "mss": "Lansdowne 388. ff. 381-395 b"}, 
    {"name": "Guy of Warwick", "page": 496, "mss": "Lansdowne 699. ff. 18 b-27 b"}, 

    #{"name": "Historia Regum Britanniae", "page": 233, "mss": "214. ff. 85-193"},
    #{"name": "Lancelot du Lac", "page": 347, "mss": "229. f. 164"},
    #{"name": "Historia Trojana", "page": 61, "mss": "362. ff. 75*, 75**"},
    #{"name": "Florence de Rome", "page": 711, "mss": "76, 77"},
    #{"name": "Abridgement of Historia Trojana", "page": 59, "mss": "380. ff. 36-39 b"},
    #{"name": "Chanson de Roland", "page": 631, "mss": "388. ff. 381-395 b"},
    #{"name": "Guy of Warwick", "page": 496, "mss": "699. ff. 18 b-27 b"},
    {"name": "Historia Regum Britanniae", "page": 233, "mss": "Lansdowne 732. ff. 1-68 b"},
    {"name": "Lancelot du Lac", "page": 347, "mss": "Lansdowne 757"},
    {"name": "Thomas of Erceldoune", "page": 331, "mss": "Lansdowne 762. ff. 24-31, 48-58 b, 61 b-71, 75-88"},
    {"name": "Amadis de Gaula", "page": 787, "mss": "Lansdowne 766. ff. 1-18 b"},
    {"name": "Chanson d'Aspremont", "page": 600, "mss": "Lansdowne 782"},
    {"name": "Sydrac and Boctus", "page": 915, "mss": "Lansdowne 793"},
    {"name": "Tale of Gamelyn", "page": 512, "mss": "Lansdowne 851. ff. 54 b-65"}
  ],
  "Arundel": [
    {"name": "Historia Trojana", "page": 60, "mss": "Arundel 6 ff. 242-342 b"},
    {"name": "Historia Regum Britanniae", "page": 224, "mss": "Arundel 10"},
    {"name": "Prophecies of Merlin, Gildas, and Thomas of Ercildoune", "page": 307, "mss": "Arundel 57. ff. 4 b-11"},
    {"name": "Prophecies of Merlin", "page": 301, "mss": "Arundel 66. ff. 267-268 b and 291 b"},
    {"name": "Troy Book", "page": 80, "mss": "Arundel 99"},
    {"name": "Romance of Thebes", "page": 87, "mss": "Arundel 119"},
    {"name": "Apollonius of Tyre", "page": 164, "mss": "Arundel 123. ff. 33-42 b"},
    {"name": "Alexander the Great", "page": 120, "mss": "Arundel 123. ff. 43-71"},
    {"name": "Letter of Dindimus to Alexander the Great", "page": 140, "mss": "Arundel 138. ff. 126, 126 b"},
    {"name": "Historia Trojana", "page": 51, "mss": "Arundel 174"},
    {"name": "Birth of Merlin", "page": 384, "mss": "Arundel 220. Art. L"},
    {"name": "Turpin's Chronicle", "page": 589, "mss": "Arundel 220. ff. 284-298 b"},
    {"name": "Voeux du Paon", "page": 155, "mss": "Arundel 230 ff. 181 b"},
    {"name": "Historia Regum Britanniae", "page": 241, "mss": "Arundel 237"},
    {"name": "Marvels of India", "page": 133, "mss": "Arundel 242. ff. 160-182"},
    {"name": "Apollonius of Tyre", "page": 163, "mss": "Arundel 292. ff. 41-61"},
    {"name": "Historia Regum Britanniae", "page": 232, "mss": "Arundel 319. ff. 16-97 b"},
    {"name": "Historia Regum Britanniae", "page": 246, "mss": "Arundel 326. ff. 63-122 b"},
    {"name": "Historia Regum Britanniae", "page": 225, "mss": "Arundel 403"},
    {"name": "Historia Regum Britanniae", "page": 233, "mss": "Arundel 409. ff. 54-77"},
    {"name": "Treatise on the Brahmins", "page": 134, "mss": "Arundel 546. ff. 265 b-280 b"}
  ],
  "Burney": [
    {"name": "Dictys Cretensis", "page": 9, "mss": "Burney 170"},
    {"name": "History of Troy", "page": 66, "mss": "Burney 186. ff. 116-128"},
    {"name": "Dares Phrygius", "page": 16, "mss": "Burney 216. ff. 89-93 b"},
    {"name": "Alexander the Great", "page": 118, "mss": "Burney 280. ff. 1-20 b"},
    {"name": "Dares Phrygius", "page": 21, "mss": "Burney 280. ff. 20 b-38 b"},
    {"name": "Alexandreis", "page": 101, "mss": "Burney 312"}
  ],
  "Sloane": [
    {"name": "Historia Regum Britanniae", "page": 250, "mss": "Sloane 289. ff. 120-133"},
    {"name": "Cassandra", "page": 803, "mss": "Sloane 457"},
    {"name": "Life of Robin Hood", "page": 517, "mss": "Sloane 780. ff. 46-48 b"},
    {"name": "Quatre fils Aimon", "page": 624, "mss": "Sloane 960"},
    {"name": "Guy of Warwick", "page": 489, "mss": "Sloane 1044. ff. 625"},
    {"name": "Alexander the Great", "page": 112, "mss": "Sloane 1619. ff. 3-17 b"},
    {"name": "Apollonius of Tyre", "page": 161, "mss": "Sloane 1619 ff. 18-29"},
    {"name": "Dares Phrygius", "page": 19, "mss": "Sloane 1619 ff. 29-37 b"},
    {"name": "Tale of Gamelyn", "page": 514, "mss": "Sloane 1685. ff. 51 b-62 b"},
    {"name": "Tale of Gamelyn", "page": 515, "mss": "Sloane 1686. ff. 71-86 b"},
    {"name": "Alexander the Great", "page": 131, "mss": "Sloane 1785. ff. 2-13"},
    {"name": "Whole Prophecy of Scotland", "page": 334, "mss": "Sloane 1802"},
    {"name": "Sydrac and Boctus", "page": 919, "mss": "Sloane 2232"},
    {"name": "Apollonius of Tyre", "page": 165, "mss": "Sloane 2233"},
    {"name": "Collection of Prophecies", "page": 333, "mss": "Sloane 2578"},
    {"name": "Robyn and Gandelyn", "page": 516, "mss": "Sloane 2593. ff. 14 b-15 b"},
    {"name": "Letter of Dindimus to Alexander the Great", "page": 140, "mss": "Sloane 3991. ff. 95-97"}
  ],
  "Additional": [
    {"name": "Apollonius of Tyre", "page": 167, "mss": "Add. 4857. ff. 28-56 b"},
    {"name": "Five Romantic Tales", "page": 841, "mss": "Add. 4857. ff. 89, 97 b, 110, 134, 139 b"},
    {"name": "Ívents saga", "page": 393, "mss": "Add. 4857. ff. 113 b-133 b"},
    {"name": "Eight Romantic Tales", "page": 843, "mss": "Add. 4859. ff. 10, 15, 142 b, 240, 313, 314, 344 b, 367"},
    {"name": "Ívents saga", "page": 393, "mss": "Add. 4857. ff. 32-45 b"},
    
    {"name": "Eight Romantic Tales", "page": 843, "mss": "Add. 4859. ff. 10, 15, 142 b, 240, 813, 314, 344 b, 367"},
    {"name": "Ívents saga", "page": 394, "mss": "Add. 4859. ff. 32-45 b"},

    {"name": "Parcevals saga and Valvers þáttr", "page": 395, "mss": "Add. 4859. ff. 46-65 b"},
    {"name": "Ereks saga Artuskappa", "page": 403, "mss": "Add. 4859. ff. 66-74 b"},
    {"name": "Möttuls saga", "page": 405, "mss": "Add. 4859. ff. 75-81"},
    {"name": "Life of Virgilius", "page": 196, "mss": "Add. 4859. ff. 81 b-91"},
    {"name": "Eight Romantic Tales", "page": 846, "mss": "Add. 4860. ff. 1, 17, 29, 95, 273, 285, 293, 329"},
    {"name": "Magus saga Jarls", "page": 686, "mss": "Add. 4860. ff. 157-188 b"},
    {"name": "Partalópa saga", "page": 707, "mss": "Add. 4860. ff. 189-206"},
    {"name": "Seven Romantic Tales", "page": 847, "mss": "Add. 4863. ff. 25, 69, 119, 153, 181, 189, 229"},
    {"name": "Samsons saga Fagra", "page": 407, "mss": "Add. 4863. ff. 47-68 b"},
    {"name": "Apollonius of Tyre", "page": 168, "mss": "Add. 4864. ff. 88-114 b"},
    {"name": "Trójumanna saga", "page": 62, "mss": "Add. 4869. ff. 2-66"},
    {"name": "Magus saga Jarls", "page": 684, "mss": "Add. 4869. ff. 67-101 b"},
    {"name": "Two Romantic Tales", "page": 850, "mss": "Add. 4869. ff. 161, 206"},
    {"name": "Three Romantic Tales", "page": 851, "mss": "Add. 4870. ff. 62, 69, 83 b"},
    {"name": "Magus saga Jarls", "page": 688, "mss": "Add. 4874. ff. 1-66"},
    {"name": "Three Romantic Tales", "page": 852, "mss": "Add. 4874. ff. 98 b, 110, 138"},
    {"name": "Three Romantic Tales", "page": 854, "mss": "Add. 4875. ff. 1, 25 b, 54 b"},
    {"name": "Saga of Ajax Frækni", "page": 854, "mss": "Add. 4884. ff. 167-178"},
    {"name": "Tristram", "page": 359, "mss": "Add. 5474"},
    {"name": "Merlínus Spá", "page": 304, "mss": "Add. 6121. ff. 55-71"},
    # jusque là c'est ok fin page 9

    # mange la page 10
    {"name": "Mélusine", "page": 692, "mss": "Add. 6796"},
    {"name": "Prophecies of Merlin", "page": 304, "mss": "Add. 6924. ff. 73-124 and 164-"},
    {"name": "Turpin's Chronicle", "page": 583, "mss": "Add. 6924. ff. 297-303"},
    {"name": "Historia Trojana", "page": 57, "mss": "Add. 9785"},
    {"name": "Titus and Vespasian", "page": 187, "mss": "Add. 10,038. ff. 2-81 b"},
    {"name": "Dares Phrygius", "page": 24, "mss": "Add. 10,094. ff. 1-14 b"},
    {"name": "Sydrac and Boctus", "page": 921, "mss": "Add. 10,286. ff. 2-114"},
    {"name": "Titus and Vespasian", "page": 179, "mss": "Add. 10,289. ff. 82-121"},
    {"name": "Juglet", "page": 812, "mss": "Add. 10,289. ff. 175 b-178 b"},
    {"name": "Romance of Jason", "page": 92, "mss": "Add. 10,290. ff. 2-161"},
    {"name": "Saint Graal", "page": 340, "mss": "Add. 10,292. ff. 1-76"},
    {"name": "Merlin", "page": 343, "mss": "Add. 10,292. ff. 76-216 b"},
    {"name": "Lancelot du Lac", "page": 352, "mss": "Add. 10,293"},
    {"name": "Lancelot du Lac", "page": 352, "mss": "Add. 10,294"},
    {"name": "Artus de Bretagne", "page": 382, "mss": "Add. 10,295"},
    {"name": "Fioccolo", "page": 724, "mss": "Add. 10,296"},
    {"name": "Riccardetto", "page": 680, "mss": "Add. 10,321"},
    {"name": "Aspremont", "page": 602, "mss": "Add. 10,508. ff. 1-63 b"},
    {"name": "Romance of the Peers of France", "page": 682, "mss": "Add. 10,508. ff. 64-96 b"},
    {"name": "Rimur of Remund", "page": 855, "mss": "Add. 11,110. ff. 101-144"},
    {"name": "Rimur from Trójumanna saga", "page": 63, "mss": "Add. 11,113. ff. 171-281"},
    {"name": "Life of Virgilius", "page": 197, "mss": "Add. 11,141. ff. 132-147"},
    {"name": "Collection of Anecdotes", "page": 865, "mss": "Add. 11,153. ff. 182-263"},
    {"name": "Gabons saga ok Vigolea", "page": 402, "mss": "Add. 11,157. ff. 1-46 b"},
    {"name": "Valentine and Orson and Tales", "page": 857, "mss": "Add. 11,157. ff. 90, 176, 188"},
    {"name": "Ten Romantic Tales", "page": 858, "mss": "Add. 11,158. ff. 1, 24, 83, 71, 123, 201, 233, 251, 261 b, 268, 289"},
    {"name": "Patient Griselda", "page": 865, "mss": "Add. 11,163. ff. 120 b-136 b"},
    {"name": "Argenis", "page": 866, "mss": "Add. 11,164"},
    {"name": "Merlinus Spá", "page": 307, "mss": "Add. 11,174. ff. 85-98"},
    {"name": "Alexander saga", "page": 104, "mss": "Add. 11,238. ff. 507-692 b"},
    {"name": "Two Romantic Tales", "page": 867, "mss": "Add. 11,241. ff. 95, 140"},
    {"name": "Petit Jean de Saintré", "page": 778, "mss": "Add. 11,614"},
    {"name": "Historia Regum Britanniae", "page": 247, "mss": "Add. 11,702. ff. 11-88"},
    {"name": "Roman de la Rose", "page": 887, "mss": "Add. 12,042"},
    {"name": "Troilus and Cryseyde", "page": 71, "mss": "Add. 12,044"},
    {"name": "Uberto and Philomena", "page": 784, "mss": "Add. 12,196. ff. 1-48 b"},
    {"name": "Turpin's Chronicle", "page": 562, "mss": "Add. 12,213. ff. 1-184 b"},
    {"name": "Tinctoris, Compostella", "page": 951, "mss": "Add. 12,213. ff. 160 b-181 b"},
    {"name": "Meliadus", "page": 364, "mss": "Add. 12,228"},
    {"name": "Roman d'Eneas", "page": 82, "mss": "Add. 14,100"},
    {"name": "Guy of Warwick", "page": 490, "mss": "Add. 14,408. ff. 74-77"},
    {"name": "Filocolo", "page": 716, "mss": "Add. 14,682"},
    {"name": "Hanes Taliesin", "page": 421, "mss": "Add. 14,697. ff. 205-208 b"},
    {"name": "Brut Gruffydd ap Arthur", "page": 258, "mss": "Add. 14,903. ff. 20-177"},
    {"name": "Peredur ab Efrawc", "page": 395, "mss": "Add. 14,907. ff. 149-167"},


    # page 11
    {"name": "Hanes Taliesin", "page": 422, "mss": "Add. 15,002. ff. 144 b-147 b"},
    {"name": "Extracts from Brut y Brenhinoedd", "page": 259, "mss": "Add. 15,003. ff. 1-13"},
    {"name": "Isarles y Ffynnawn", "page": 393, "mss": "Add. 15,035. ff. 57-61"},
    {"name": "Dares Phrygius", "page": 25, "mss": "Add. 15,042"},
    {"name": "Contes et Fabliaux", "page": 804, "mss": "Add. 15,210-15,213"},
    {"name": "Partonopeus de Blois", "page": 698, "mss": "Add. 15,212. ff. 14 b-196 b"},
    {"name": "Blanchandin et Orgueillose d'Amors", "page": 727, "mss": "Add. 15,212. ff. 197-266 b"},
    {"name": "Floire et Blancheflor", "page": 714, "mss": "Add. 15,213"},
    {"name": "Dictys Cretensis", "page": 10, "mss": "Add. 15,429"},
    {"name": "Historia Trojana", "page": 43, "mss": "Add. 15,477"},
    {"name": "Brut Tyailio", "page": 254, "mss": "Add. 15,566. ff. 6-140"},
    {"name": "Les deux Chevaliers, and Le dit de Guillaume d'Angleterre", "page": 757, "mss": "Add. 15,606. ff. 110, col. 2,-113, col. 2; and 140 b-152"},
    {"name": "Historia Regum Britanniae", "page": 234, "mss": "Add. 15,732"},
    {"name": "Roman de la Rose", "page": 894, "mss": "Add. 16,169. ff. 1, 477"},
    {"name": "Roman d'Athis et Profilas", "page": 173, "mss": "Add. 16,441"},
    {"name": "Roman d'Athis et Profilas", "page": 929, "mss": "Add. 16,441"},

    {"name": "Sydrac and Boctus", "page": 903, "mss": "Add. 16,563"},
    {"name": "Voeux du Paon and Restor du Paon", "page": 150, "mss": "Add. 16,888"},
    {"name": "Theseus de Cologne", "page": 769, "mss": "Add. 16,955"},
    {"name": "Voeux du Paon", "page": 146, "mss": "Add. 16,956"},
    {"name": "Alexandreis", "page": 141, "mss": "Add. 17,084"},
    {"name": "Lancelot du Lac", "page": 348, "mss": "Add. 17,443"},
    {"name": "Sydrac and Boctus", "page": 909, "mss": "Add. 17,914"},
    {"name": "Turpin's Chronicle", "page": 592, "mss": "Add. 17,920. ff. 6 b-19 b"},
    {"name": "Alexandreis", "page": 99, "mss": "Add. 18,217"},
    {"name": "Romance of Thebes", "page": 89, "mss": "Add. 18,632. ff. 5-33"},
    {"name": "The Diana of Montemayor", "page": 789, "mss": "Add. 18,688"},
    {"name": "Amis and Amylion", "page": 678, "mss": "Add. 18,922. ff. 204-221 b"},
    {"name": "Turpin's Chronicle", "page": 573, "mss": "Add. 19,513. ff. 141-163"},
    {"name": "Wigalois", "page": 398, "mss": "Add. 19,554. ff. 2-56 b"},
    {"name": "Iwein", "page": 390, "mss": "Add. 19,554. ff. 57-100 b"},
    {"name": "Dares Phrygius", "page": 26, "mss": "Add. 19,709. ff. 1-7"},
    {"name": "Brut Gruffydd ap Arthur", "page": 257, "mss": "Add. 19,709. ff. 8-84"},
    {"name": "May Colvin", "page": 544, "mss": "Add. 20,094. ff. 21-26, 30-32 b"},
    {"name": "Philomena", "page": 596, "mss": "Add. 21,218"},
    {"name": "Filostrato", "page": 67, "mss": "Add. 21,246"},
    {"name": "Historia Trojana", "page": 46, "mss": "Add. 22,155"},
    {"name": "King Robert of Sicily", "page": 763, "mss": "Add. 22,283. ff. 90 b-91 b"},
    {"name": "The King of Tars and the Soudan of Damas", "page": 767, "mss": "Add. 22,283. ff. 126-128 b"},
    {"name": "Scottish Ballads", "page": 531, "mss": "Add. 22,311"},
    {"name": "Reali di Francia", "page": 672, "mss": "Add. 22,312"},
    {"name": "Alexandreis", "page": 96, "mss": "Add. 22,821"},
    {"name": "Tristram", "page": 357, "mss": "Add. 23,829"},
    {"name": "Guiron le Courtois", "page": 369, "mss": "Add. 23,930. ff. 1-87 b"},
    {"name": "Tales and Fables", "page": 826, "mss": "Add. 24,946"},
    #manque le haut de la pagge 12


    {"name": "Nine Romantic Tales", "page": 867, "mss": "Add. 24,969. ff. 25, 62, 69 b, 74, 78 b, 83, 94, 209, 270"},
    {"name": "Alexander saga", "page": 105, "mss": "Add. 24,969. ff. 128 b-151 b"},
    {"name": "Story of Sigurgaror", "page": 871, "mss": "Add. 24,970"},
    {"name": "Fertrams saga", "page": 872, "mss": "Add. 24,972. ff. 58-72 b"},
    {"name": "Two Romantic Tales", "page": 872, "mss": "Add. 24,973. ff. 2-69 b"},
    {"name": "Prophecy of Merlin", "page": 292, "mss": "Add. 25,014. ff. 119 b, col. 2"},
    {"name": "Prophecies de Merlin", "page": 371, "mss": "Add. 25,434"},
    {"name": "The Chaste Duchess", "page": 713, "mss": "Add. 25,569. ff. 15 b-21"},
    {"name": "Romances and Ballads", "page": 817, "mss": "Add. 27,979"},
    {"name": "Robin Hood", "page": 519, "mss": "Add. 27879 ff. 2-10"},
    {"name": "Sir Lancelot of Dulake", "page": 397, "mss": "Add. 27879 ff. 10-14, 16, 17"},
    {"name": "Miscellaneous Ballads", "page": 525, "mss": "Add. 27879 ff. 14 b-24"},
    {"name": "The Grene Knight, Turke and Gowin, The Marriage of Sir Gawaine", "page": 389, "mss": "Add. 27879. ff. 17 b-24 b, 101 b-105, 223 b-226 b"},
    {"name": "Sir Lambewell", "page": 417, "mss": "Add. 27879. ff. 29 b-33 b"},
    {"name": "Merlin", "page": 386, "mss": "Add. 27879 ff. 72 b-89"},
    {"name": "King Arthur's Death", "page": 406, "mss": "Add. 27879 ff. 89, 91"},
    {"name": "Guye and Amarant", "page": 499, "mss": "Add. 27879 ff. 110-117"},
    {"name": "Three Ballads of Forest Life", "page": 523, "mss": "Add. 27879 ff. 117 b-210"},
    {"name": "Guy and Phillis", "page": 500, "mss": "Add. 27879 ff. 126"},
    {"name": "Robin Hood Ballad", "page": 520, "mss": "Add. 27879 ff. 129-180 b"},


    # après ça c'est ok.
    {"name": "Boy and Mantle", "page": 404, "mss": "Add. 27879 ff 140, 141"},
    {"name": "Libius Disconius", "page": 401, "mss": "Add. 27879 ff 156 b-171"},
    {"name": "Guy and Colebrande", "page": 500, "mss": "Add. 27879 ff 172 b-176b"},
    {"name": "Two Ballads relating to Adam Bell", "page": 522, "mss": "Add. 27879 ff 194-201"},
    {"name": "A Propecye", "page": 327, "mss": "Add. 27879 f 239 b"},
    {"name": "King Humber", "page": 339, "mss": "Add. 27879 f 248"},
    {"name": "Robin Hood's Garland", "page": 520, "mss": "Add. 28638"},
    {"name": "Ballads of Scotland", "page": 537, "mss": "Add. 29408, 29409"},
    {"name": "Roman de Troie", "page": 924, "mss": "Add. 30863"},
    {"name": "Voeux du Paon", "page": 926, "mss": "Add. 30864"},
    {"name": "Titurel", "page": 932, "mss": "Add. 30984"},
    {"name": "Titus and Vespasian", "page": 928, "mss": "Add. 31042 ff 50-66"},
    {"name": "Two Charlemagne Romances", "page": 953, "mss": "Add. 31042 ff 66 b-79 b, 82-94"},
    {"name": "Richard Coeur-de-Lion", "page": 944, "mss": "Add. 31042 ff 125-163 b"},
    {"name": "Roman de la Rose", "page": 884, "mss": "Add. 31,840"}
    # page 12 en bas
  ],"Egerton": [
    {"name": "Prophecy of the Tenth Sibyl", "page": 190, "mss": "Egerton 810 ff. 106-109 b"}, 
    {"name": "Roman de la Rose", "page": 879, "mss": "Egerton 881"}, 
    {"name": "Tristram", "page": 362, "mss": "Egerton 989"}, 
    {"name": "Roman de la Rose", "page": 890, "mss": "Egerton 1069"},
    {"name": "Roman de la Rose", "page": 891, "mss": "Egerton 2022"},
    {"name": "Ipomedon and Prothesilaus", "page": 746, "mss": "Egerton 2515 ff. 3-141"} 
    ]
}
# print(index_table.keys())
# with open("../results/index_table.json","w", encoding='utf-8')as f:
#     json.dump(index_table, f, indent=2, ensure_ascii=False)

In [ ]:
## index_table(corrigé manuellement) => index_table_clean
def split_by_ff(s: str):
    if "ff" in s:
        left, right = s.split("ff", 1)
        return left.strip(), "ff" + right.strip()
    return s.strip(), None

index_table_clean={}
for mss_cat, works in index_table.items():
    for work in works:
        title = work['name']
        page = work['page']
        mss_ff = work["mss"]

        mss, ff = split_by_ff(mss_ff)

        if title not in index_table_clean:
            index_table_clean[title] = []# one title=> plu mss!

        index_table_clean[title].append({
            'collection':mss_cat,
            'mss':mss,
            'ff': ff,
            'page': page
        })
    
print(index_table_clean.keys())
with open("../results/index_table_clean1.json","w", encoding='utf-8')as f:
    json.dump(index_table_clean, f, indent=2, ensure_ascii=False)
index_table_clean

dict_keys(['Historia Regum Britanniae', "Turpin's Chronicle", 'Prophecy of Merlin Silvester', 'Dares Phrygius', 'Letters between Alexander and Dindimus', 'Alexandreis', 'Prophecies of Merlin', 'Guy of Warwick', 'Prophecy on Scotland', 'Alexander the Great', 'Prophecy', 'Fulk Fitz-Warin', 'Amya and Amylion', 'Tale of Two Lovers', 'Historia Trojana', 'Story of Troy', 'Prophecy of the Tenth Sibyl', 'Karolellus', 'Roman de Brut', 'Havelok', 'Vita Merlini', 'Prophecies of Merlin Silvester', 'Historia Regum Britannia', 'Apollonius of Tyre', 'Le Chemin de Vaillance', "Livre de l'Ordre de Chevalerie", 'Saint Graal', 'Lancelot du Lac', 'Perceforest', 'Simon de Pouille', 'Aspremont', 'Fierabras', 'Ogier le Danois', 'Quatre fils Aimon', 'Pontus and Sidoine', 'Guy of Warwick and Heraud of Ardennes', 'Knight of the Swan', 'Iliaca', 'Heroica', 'Titus and Vespasian', 'Voyage of Charlemagne to Jerusalem and Constantinople', 'Sydrac and Boctus', 'Sir Gowghter', 'Tale of Gamelyn', 'Recueil des Histoires de Troie', 'Mélusine', 'Troy Book', 'Romance of Thebes', 'Roman de la Rose', "La Vengeance d'Alexandre", "Guillaume d'Orange", 'Cleriadus et Meliadice', 'Tristram', 'Gesta Regum Britannia', 'Sir Eglamour of Artois', 'Octavian the Emperor', 'Sir Launfal', 'Lybeaus Desconus', 'Emare', 'Sir Isumbras', "Lazamon's Brut", 'Prophecy of Merlin', 'Prophecies', 'Sir Gawain and the Green Knight', 'Story of Albina and her Sisters', 'Petit Jean de Saintré', 'Floridam and Elluide', 'Ywain and Gawain', "Merlin's Prophecy of the Six Kings", 'Letters of Dindimus to Alexander the Great', "Lisamon's Brut", 'Marvels of India', 'Floyras and Blanchefleur', 'Thomas of Erceldoune', 'Ipomodon', 'Brutus', 'Lanval', 'Fall of Troy', 'Fall of Troy and Adventures of Æneas', 'Two Prophecies', 'Prophecies of Merlin, etc.', 'Whole Prophecy of Scotland', 'Battle of Roncevaux', 'Story of Troy and Adventures of Æneas', 'Brut y Brenhinoedd', 'Prophecy of the Lily, the Lion, and the Son of Man', 'Meriadoc and Gawain', 'Four Prophecies', "The Three Kings' Sons", 'Romance of Troy', 'King Robert of Sicily', 'Gui de Bourgogne', 'King Horn', 'Political Prophecies', 'Lays of Marie de France', 'Troilus and Cryseyde', 'Chanson de Brut', 'Prophecies de Merlin', 'Prophecies of Merlin and others', 'Ipomedon', 'Morte Arthur', 'Six Fabliaux', 'Prophecy of Thomas of Erceldoune', 'Amys and Amylion', 'Letter of Dindimus to Alexander the Great', 'Aronus and Marina', 'Filocolo', 'Dictys Cretensis', 'Corbaccio', 'Fiammetta', 'Life of Harold, King of England', 'Sir Orpheo', 'Tale of Antiochus', 'Florimont', 'Voeux du Paon', "L'Ordène de Chevalerie", 'Girard de Roussillon', 'Doon de la Roche', 'Enfances Ogier', 'Roman de Troie', 'Richard Cœur-de-Lion', 'Prophecies taken from Geoffrey of Monmouth and others', 'Merlin', 'Theagenes and Stelliana', 'Kings of Britain', 'Florence de Rome', 'Abridgement of Historia Trojana', 'Chanson de Roland', 'Amadis de Gaula', "Chanson d'Aspremont", 'Prophecies of Merlin, Gildas, and Thomas of Ercildoune', 'Birth of Merlin', 'Treatise on the Brahmins', 'History of Troy', 'Cassandra', 'Life of Robin Hood', 'Collection of Prophecies', 'Robyn and Gandelyn', 'Five Romantic Tales', 'Ívents saga', 'Eight Romantic Tales', 'Parcevals saga and Valvers þáttr', 'Ereks saga Artuskappa', 'Möttuls saga', 'Life of Virgilius', 'Magus saga Jarls', 'Partalópa saga', 'Seven Romantic Tales', 'Samsons saga Fagra', 'Trójumanna saga', 'Two Romantic Tales', 'Three Romantic Tales', 'Saga of Ajax Frækni', 'Merlínus Spá', 'Juglet', 'Romance of Jason', 'Artus de Bretagne', 'Fioccolo', 'Riccardetto', 'Romance of the Peers of France', 'Rimur of Remund', 'Rimur from Trójumanna saga', 'Collection of Anecdotes', 'Gabons saga ok Vigolea', 'Valentine and Orson and Tales', 'Ten Romantic Tales', 'Patient Griselda', 'Argenis', 'Merlinus Spá', 'Alexander saga', 'Uberto and Philomena', 'Tinctoris, Compostella', 'Meliadus', "Roman d'Eneas", 'Hanes Taliesin', 'Brut Gruffydd ap Arthur', 'Peredur ab Efrawc', 'Extracts from Brut y Brenhinoedd', 'Isarles y Ffynnawn', 'Contes et Fabliaux', 'Partonopeus de Blois', "Blanchandin et Orgueillose d'Amors", 'Floire et Blancheflor', 'Brut Tyailio', "Les deux Chevaliers, and Le dit de Guillaume d'Angleterre", "Roman d'Athis et Profilas", 'Voeux du Paon and Restor du Paon', 'Theseus de Cologne', 'The Diana of Montemayor', 'Amis and Amylion', 'Wigalois', 'Iwein', 'May Colvin', 'Philomena', 'Filostrato', 'The King of Tars and the Soudan of Damas', 'Scottish Ballads', 'Reali di Francia', 'Guiron le Courtois', 'Tales and Fables', 'Nine Romantic Tales', 'Story of Sigurgaror', 'Fertrams saga', 'The Chaste Duchess', 'Romances and Ballads', 'Robin Hood', 'Sir Lancelot of Dulake', 'Miscellaneous Ballads', 'The Grene Knight, Turke and Gowin, The Marriage of Sir Gawaine', 'Sir Lambewell', "King Arthur's Death", 'Guye and Amarant', 'Three Ballads of Forest Life', 'Guy and Phillis', 'Robin Hood Ballad', 'Boy and Mantle', 'Libius Disconius', 'Guy and Colebrande', 'Two Ballads relating to Adam Bell', 'A Propecye', 'King Humber', "Robin Hood's Garland", 'Ballads of Scotland', 'Titurel', 'Two Charlemagne Romances', 'Richard Coeur-de-Lion', 'Ipomedon and Prothesilaus'])

{'Historia Regum Britanniae': [{'collection': 'Royal',
   'mss': '4. C. xi.',
   'ff': 'ff. 222-249',
   'page': 227},
  {'collection': 'Royal',
   'mss': '13. A. iii.',
   'ff': 'ff. 1-133',
   'page': 237},
  {'collection': 'Royal',
   'mss': '13. A. v.',
   'ff': 'ff. 99-161 b',
   'page': 237},
  {'collection': 'Royal',
   'mss': '13. D. i.',
   'ff': 'ff. 175-212 b',
   'page': 248},
  {'collection': 'Royal',
   'mss': '13. D. ii.',
   'ff': 'ff. 124-173 b',
   'page': 228},
  {'collection': 'Royal', 'mss': '13. D. v.', 'ff': 'ff. 1-37 b', 'page': 229},
  {'collection': 'Cotton',
   'mss': 'Nero D. viii.',
   'ff': 'ff. 3-63',
   'page': 230},
  {'collection': 'Cotton',
   'mss': 'Galba E. xi.',
   'ff': 'ff. 2-58 b',
   'page': 239},
  {'collection': 'Cotton',
   'mss': 'Vespasian A. xxiii.',
   'ff': 'ff. 4-106 b',
   'page': 241},
  {'collection': 'Cotton',
   'mss': 'Vespasian E. x.',
   'ff': 'ff. 271-368 b',
   'page': 242},
  {'collection': 'Cotton',
   'mss': 'Titus A. xviii.',
   'ff': 'ff. 13-82',
   'page': 243},
  {'collection': 'Cotton',
   'mss': 'Titus A. xxv.',
   'ff': 'ff. 105-116 b',
   'page': 244},
  {'collection': 'Cotton',
   'mss': 'Titus A. xxvii.',
   'ff': 'ff. 1 b-87',
   'page': 231},
  {'collection': 'Cotton', 'mss': 'Titus C. xvii.', 'ff': None, 'page': 203},
  {'collection': 'Cotton',
   'mss': 'Cleopatra D. viii.',
   'ff': 'ff. 8-94',
   'page': 249},
  {'collection': 'Harley',
   'mss': 'Harley 225.',
   'ff': 'ff. 3-78',
   'page': 222},
  {'collection': 'Harley',
   'mss': 'Harley 536.',
   'ff': 'ff. 58-61',
   'page': 226},
  {'collection': 'Harley',
   'mss': 'Harley 3773.',
   'ff': 'ff. 7-57',
   'page': 223},
  {'collection': 'Harley',
   'mss': 'Harley 4003.',
   'ff': 'ff. 81-141 b',
   'page': 244},
  {'collection': 'Harley',
   'mss': 'Harley 4123.',
   'ff': 'ff. 2-49 b',
   'page': 236},
  {'collection': 'Harley',
   'mss': 'Harley 5115.',
   'ff': 'ff. 87-150',
   'page': 245},
  {'collection': 'Harley',
   'mss': 'Harley 6358.',
   'ff': 'ff. 2-58 b',
   'page': 235},
  {'collection': 'Lansdowne',
   'mss': 'Lansdowne 732.',
   'ff': 'ff. 1-68 b',
   'page': 233},
  {'collection': 'Arundel', 'mss': 'Arundel 10', 'ff': None, 'page': 224},
  {'collection': 'Arundel', 'mss': 'Arundel 237', 'ff': None, 'page': 241},
  {'collection': 'Arundel',
   'mss': 'Arundel 319.',
   'ff': 'ff. 16-97 b',
   'page': 232},
  {'collection': 'Arundel',
   'mss': 'Arundel 326.',
   'ff': 'ff. 63-122 b',
   'page': 246},
  {'collection': 'Arundel', 'mss': 'Arundel 403', 'ff': None, 'page': 225},
  {'collection': 'Arundel',
   'mss': 'Arundel 409.',
   'ff': 'ff. 54-77',
   'page': 233},
  {'collection': 'Sloane',
   'mss': 'Sloane 289.',
   'ff': 'ff. 120-133',
   'page': 250},
  {'collection': 'Additional',
   'mss': 'Add. 11,702.',
   'ff': 'ff. 11-88',
   'page': 247},
  {'collection': 'Additional', 'mss': 'Add. 15,732', 'ff': None, 'page': 234}],
 "Turpin's Chronicle": [{'collection': 'Royal',
   'mss': '4. C. xi.',
   'ff': 'ff. 280-286 b',
   'page': 583},
  {'collection': 'Royal',
   'mss': '13. D. i.',
   'ff': 'ff. 212 b-222',
   'page': 572},
  {'collection': 'Cotton',
   'mss': 'Caligula B. vii.',
   'ff': 'ff. 192-203 b',
   'page': 561},
  {'collection': 'Cotton',
   'mss': 'Nero A. xi.',
   'ff': 'ff. 8-63',
   'page': 546},
  {'collection': 'Cotton',
   'mss': 'Nero A. xi.',
   'ff': 'ff. 8-63',
   'page': 950},
  {'collection': 'Cotton',
   'mss': 'Vespasian A. xiii.',
   'ff': 'ff. 94-114 b',
   'page': 576},
  {'collection': 'Cotton',
   'mss': 'Titus A. xix.',
   'ff': 'ff. 24-43',
   'page': 578},
  {'collection': 'Harley',
   'mss': 'Harley 108.',
   'ff': 'ff. 4 b-31 b',
   'page': 574},
  {'collection': 'Harley',
   'mss': 'Harley 273.',
   'ff': 'ff. 86-102 b',
   'page': 587},
  {'collection': 'Harley',
   'mss': 'Harley 2361.',
   'ff': 'ff. 138-139 b',
   'page': 582},
  {'collection': 'Harley',
   'mss': 'Harley 2500.',
   'ff': 'ff. 139-155',
   'page': 581},
  {'collection': 'Harley',
   'mss': 'Harley 3043.',
   'ff': 'ff. 17-31',
   'page': 577},
  {'collection': 'Harley',
   'mss': 'Harley 6358.',
   'ff': 'ff. 60-83',
   'page': 560},
  {'collection': 'Arundel',
   'mss': 'Arundel 220.',
   'ff': 'ff. 284-298 b',
   'page': 589},
  {'collection': 'Additional',
   'mss': 'Add. 6924.',
   'ff': 'ff. 297-303',
   'page': 583},
  {'collection': 'Additional',
   'mss': 'Add. 12,213.',
   'ff': 'ff. 1-184 b',
   'page': 562},
  {'collection': 'Additional',
   'mss': 'Add. 17,920.',
   'ff': 'ff. 6 b-19 b',
   'page': 592},
  {'collection': 'Additional',
   'mss': 'Add. 19,513.',
   'ff': 'ff. 141-163',
   'page': 573}],
 'Prophecy of Merlin Silvester': [{'collection': 'Royal',
   'mss': '5. F. xv.',
   'ff': 'ff. 3 b',
   'page': 313},
  {'collection': 'Royal',
   'mss': '13. A. iii.',
   'ff': 'ff. 135 b, 136',
   'page': 315}],
 'Dares Phrygius': [{'collection': 'Royal',
   'mss': '6. C. viii.',
   'ff': 'ff. 123-133 b',
   'page': 17},
  {'collection': 'Royal',
   'mss': '10. A. x.',
   'ff': 'ff. 188-192 b',
   'page': 20},
  {'collection': 'Royal',
   'mss': '13. A. v.',
   'ff': 'ff. 88 b-98 b',
   'page': 23},
  {'collection': 'Royal',
   'mss': '15. A. xxii.',
   'ff': 'ff. 73-90',
   'page': 13},
  {'collection': 'Royal',
   'mss': '15. B. xi.',
   'ff': 'ff. 57-66 b',
   'page': 14},
  {'collection': 'Cotton',
   'mss': 'Caligula B. vii.',
   'ff': 'ff. 214-218 b',
   'page': 22},
  {'collection': 'Cotton',
   'mss': 'Vitellius A. xiii.',
   'ff': 'ff. 90',
   'page': 15},
  {'collection': 'Cotton',
   'mss': 'Vitellius C. viii.',
   'ff': 'ff. 5 b-6 b',
   'page': 18},
  {'collection': 'Cotton',
   'mss': 'Vespasian B. xxv.',
   'ff': 'ff. 98 b-117',
   'page': 12},
  {'collection': 'Cotton',
   'mss': 'Cleopatra B. v.',
   'ff': 'ff. 222-250',
   'page': 26},
  {'collection': 'Harley', 'mss': 'Harley 641.', 'ff': 'ff. 1-8', 'page': 20},
  {'collection': 'Burney',
   'mss': 'Burney 216.',
   'ff': 'ff. 89-93 b',
   'page': 16},
  {'collection': 'Burney',
   'mss': 'Burney 280.',
   'ff': 'ff. 20 b-38 b',
   'page': 21},
  {'collection': 'Sloane',
   'mss': 'Sloane 1619',
   'ff': 'ff. 29-37 b',
   'page': 19},
  {'collection': 'Additional',
   'mss': 'Add. 10,094.',
   'ff': 'ff. 1-14 b',
   'page': 24},
  {'collection': 'Additional', 'mss': 'Add. 15,042', 'ff': None, 'page': 25},
  {'collection': 'Additional',
   'mss': 'Add. 19,709.',
   'ff': 'ff. 1-7',
   'page': 26}],
 'Letters between Alexander and Dindimus': [{'collection': 'Royal',
   'mss': '6. E. iii.',
   'ff': 'ff. 111 b-112 b',
   'page': 138},
  {'collection': 'Royal',
   'mss': '7. A. i.',
   'ff': 'ff. 68 b-69 b',
   'page': 137}],
 'Alexandreis': [{'collection': 'Royal',
   'mss': '8. B. iv.',
   'ff': 'ff. 19-71 b',
   'page': 98},
  {'collection': 'Royal', 'mss': '15. A. x.', 'ff': 'ff. 2-89', 'page': 94},
  {'collection': 'Harley', 'mss': 'Harley 4745', 'ff': None, 'page': 103},
  {'collection': 'Harley', 'mss': 'Harley 5437', 'ff': None, 'page': 103},
  {'collection': 'Burney', 'mss': 'Burney 312', 'ff': None, 'page': 101},
  {'collection': 'Additional', 'mss': 'Add. 17,084', 'ff': None, 'page': 141},
  {'collection': 'Additional', 'mss': 'Add. 18,217', 'ff': None, 'page': 99},
  {'collection': 'Additional', 'mss': 'Add. 22,821', 'ff': None, 'page': 96}],
 'Prophecies of Merlin': [{'collection': 'Royal',
   'mss': '8. D. iii.',
   'ff': 'ff. 160 b-163',
   'page': 297},
  {'collection': 'Cotton',
   'mss': 'Julius A. v.',
   'ff': 'ff. 5, 53-57b, 177 b-179, and 180-181 b',
   'page': 299},
  {'collection': 'Cotton',
   'mss': 'Tiberius A. ix.',
   'ff': 'ff. 2-6',
   'page': 295},
  {'collection': 'Cotton',
   'mss': 'Caligula B. vii.',
   'ff': 'ff. 220 b-231 b',
   'page': 296},
  {'collection': 'Cotton',
   'mss': 'Nero A. iv.',
   'ff': 'ff. 63-76 b',
   'page': 297},
  {'collection': 'Cotton',
   'mss': 'Cleopatra C. iv.',
   'ff': 'ff. 74-122',
   'page': 310},
  {'collection': 'Cotton',
   'mss': 'Faustina A. viii.',
   'ff': 'ff. 109 b-116',
   'page': 292},
  {'collection': 'Arundel',
   'mss': 'Arundel 66.',
   'ff': 'ff. 267-268 b and 291 b',
   'page': 301},
  {'collection': 'Additional',
   'mss': 'Add. 6924.',
   'ff': 'ff. 73-124 and 164-',
   'page': 304}],
 'Guy of Warwick': [{'collection': 'Royal',
   'mss': '8. F. ix.',
   'ff': 'ff. 105-159',
   'page': 485},
  {'collection': 'Cotton',
   'mss': 'Vespasian D. ix.',
   'ff': 'ff. 40-43 b',
   'page': 492},
  {'collection': 'Harley',
   'mss': 'Harley 3775.',
   'ff': 'ff. 15-26 b',
   'page': 471},
  {'collection': 'Harley', 'mss': 'Harley 5243', 'ff': None, 'page': 497},
  {'collection': 'Harley',
   'mss': 'Harley 7333.',
   'ff': 'ff. 33-35 b',
   'page': 494},
  {'collection': 'Lansdowne',
   'mss': 'Lansdowne 699.',
   'ff': 'ff. 18 b-27 b',
   'page': 496},
  {'collection': 'Sloane',
   'mss': 'Sloane 1044.',
   'ff': 'ff. 625',
   'page': 489},
  {'collection': 'Additional',
   'mss': 'Add. 14,408.',
   'ff': 'ff. 74-77',
   'page': 490}],
 'Prophecy on Scotland': [{'collection': 'Royal',
   'mss': '9. B. ix.',
   'ff': 'ff. 2',
   'page': 327}],
 'Alexander the Great': [{'collection': 'Royal',
   'mss': '12. C. iv.',
   'ff': 'ff. 138-170',
   'page': 112},
  {'collection': 'Royal', 'mss': '13. A. i.', 'ff': None, 'page': 106},
  {'collection': 'Royal', 'mss': '13. A. v.', 'ff': 'ff. 2-23 b', 'page': 118},
  {'collection': 'Royal',
   'mss': '13. C. xii.',
   'ff': 'ff. 82-109 b',
   'page': 122},
  {'collection': 'Royal',
   'mss': '15. C. vi.',
   'ff': 'ff. 102 b-130 b',
   'page': 110},
  {'collection': 'Royal',
   'mss': '15. E. vi.',
   'ff': 'ff. 4 b-24 b',
   'page': 129},
  {'collection': 'Royal', 'mss': '19. D. i.', 'ff': 'ff. 1-46', 'page': 123},
  {'collection': 'Royal', 'mss': '20. A. v.', 'ff': None, 'page': 125},
  {'collection': 'Royal', 'mss': '20. B. xx.', 'ff': None, 'page': 128},
  {'collection': 'Cotton',
   'mss': 'Nero D. viii.',
   'ff': 'ff. 160-174 b',
   'page': 113},
  {'collection': 'Cotton',
   'mss': 'Galba E. xi.',
   'ff': 'ff. 111-125',
   'page': 115},
  {'collection': 'Cotton',
   'mss': 'Cleopatra D. v.',
   'ff': 'ff. 165 b-183',
   'page': 114},
  {'collection': 'Harley',
   'mss': 'Harley 527.',
   'ff': 'ff. 47-56 b',
   'page': 113},
  {'collection': 'Harley',
   'mss': 'Harley 2682.',
   'ff': 'ff. 180-192',
   'page': 109},
  {'collection': 'Harley', 'mss': 'Harley 4979', 'ff': None, 'page': 127},
  {'collection': 'Harley',
   'mss': 'Harley 5054.',
   'ff': 'ff. 124 b-181',
   'page': 119},
  {'collection': 'Arundel',
   'mss': 'Arundel 123.',
   'ff': 'ff. 43-71',
   'page': 120},
  {'collection': 'Burney',
   'mss': 'Burney 280.',
   'ff': 'ff. 1-20 b',
   'page': 118},
  {'collection': 'Sloane',
   'mss': 'Sloane 1619.',
   'ff': 'ff. 3-17 b',
   'page': 112},
  {'collection': 'Sloane',
   'mss': 'Sloane 1785.',
   'ff': 'ff. 2-13',
   'page': 131}],
 'Prophecy': [{'collection': 'Royal',
   'mss': '12. C. xii.',
   'ff': 'ff. 14-16 b',
   'page': 316}],
 'Fulk Fitz-Warin': [{'collection': 'Royal',
   'mss': '12. C. xii.',
   'ff': 'ff. 33-60 b',
   'page': 501}],
 'Amya and Amylion': [{'collection': 'Royal',
   'mss': '12. C. xii.',
   'ff': 'ff. 69-76',
   'page': 674}],
 'Tale of Two Lovers': [{'collection': 'Royal',
   'mss': '12. C. xx.',
   'ff': 'ff. 17-46',
   'page': 801},
  {'collection': 'Harley',
   'mss': 'Harley 1883.',
   'ff': 'ff. 119-135 b',
   'page': 799},
  {'collection': 'Harley',
   'mss': 'Harley 2492.',
   'ff': 'ff. 154 b-169 b',
   'page': 802}],
 'Historia Trojana': [{'collection': 'Royal',
   'mss': '12. D. iii.',
   'ff': 'ff. 38-143',
   'page': 49},
  {'collection': 'Royal',
   'mss': '13. C. xii.',
   'ff': 'ff. 6-32 b',
   'page': 50},
  {'collection': 'Royal',
   'mss': '15. C. xvi.',
   'ff': 'ff. 86-145',
   'page': 44},
  {'collection': 'Royal', 'mss': '16. F. ix.', 'ff': None, 'page': 54},
  {'collection': 'Harley',
   'mss': 'Harley 51.',
   'ff': 'ff. 3-105 b',
   'page': 52},
  {'collection': 'Harley', 'mss': 'Harley 176', 'ff': None, 'page': 47},
  {'collection': 'Harley', 'mss': 'Harley 3637', 'ff': None, 'page': 48},
  {'collection': 'Harley', 'mss': 'Harley 3681', 'ff': None, 'page': 54},
  {'collection': 'Harley',
   'mss': 'Harley 4123.',
   'ff': 'ff. 50-126',
   'page': 40},
  {'collection': 'Harley', 'mss': 'Harley 4387', 'ff': None, 'page': 53},
  {'collection': 'Lansdowne',
   'mss': 'Lansdowne 229.',
   'ff': 'ff. 164',
   'page': 61},
  {'collection': 'Arundel',
   'mss': 'Arundel 6',
   'ff': 'ff. 242-342 b',
   'page': 60},
  {'collection': 'Arundel', 'mss': 'Arundel 174', 'ff': None, 'page': 51},
  {'collection': 'Additional', 'mss': 'Add. 9785', 'ff': None, 'page': 57},
  {'collection': 'Additional', 'mss': 'Add. 15,477', 'ff': None, 'page': 43},
  {'collection': 'Additional', 'mss': 'Add. 22,155', 'ff': None, 'page': 46}],
 'Story of Troy': [{'collection': 'Royal',
   'mss': '12. D. iii.',
   'ff': 'ff. 152 b-158',
   'page': 34},
  {'collection': 'Royal',
   'mss': '13. A. iv.',
   'ff': 'ff. 22 b-23 b, 76-81 b',
   'page': 27}],
 'Prophecy of the Tenth Sibyl': [{'collection': 'Royal',
   'mss': '13. A. xiv.',
   'ff': 'ff. 244-247',
   'page': 194},
  {'collection': 'Royal',
   'mss': '15. A. xxii.',
   'ff': 'ff. 110-115',
   'page': 194},
  {'collection': 'Royal', 'mss': '15. B. xi.', 'ff': 'ff. 67-69', 'page': 193},
  {'collection': 'Cotton',
   'mss': 'Caligula A. x.',
   'ff': 'ff. 200-204',
   'page': 195},
  {'collection': 'Cotton',
   'mss': 'Caligula B. vii.',
   'ff': 'ff. 219, 220',
   'page': 193},
  {'collection': 'Cotton',
   'mss': 'Vespasian B. xxv.',
   'ff': 'ff. 117 b-123',
   'page': 192},
  {'collection': 'Cotton',
   'mss': 'Vespasian E. iv.',
   'ff': 'ff. 143-147',
   'page': 194},
  {'collection': 'Cotton',
   'mss': 'Titus D. iii.',
   'ff': 'ff. 143-147 b',
   'page': 191},
  {'collection': 'Cotton',
   'mss': 'Domitian xiii.',
   'ff': 'ff. 104-107',
   'page': 193},
  {'collection': 'Cotton',
   'mss': 'Domitian xiii.',
   'ff': 'ff. 132 b-134 b',
   'page': 195},
  {'collection': 'Egerton',
   'mss': 'Egerton 810',
   'ff': 'ff. 106-109 b',
   'page': 190}],
 'Karolellus': [{'collection': 'Royal',
   'mss': '13. A. xviii.',
   'ff': 'ff. 136-149 b',
   'page': 594}],
 'Roman de Brut': [{'collection': 'Royal',
   'mss': '13. A. xxi.',
   'ff': 'ff. 40 b-113',
   'page': 264},
  {'collection': 'Cotton',
   'mss': 'Vitellius A. x.',
   'ff': 'ff. 19-114 b',
   'page': 259},
  {'collection': 'Harley', 'mss': 'Harley 6508', 'ff': None, 'page': 263}],
 'Havelok': [{'collection': 'Royal',
   'mss': '13. A. xxi.',
   'ff': 'ff. 113-117 b',
   'page': 423},
  {'collection': 'Royal',
   'mss': '13. A. xxi.',
   'ff': 'ff. 113-117 b',
   'page': 940}],
 'Vita Merlini': [{'collection': 'Royal',
   'mss': '13. E. i.',
   'ff': 'ff. 143-146',
   'page': 289},
  {'collection': 'Cotton',
   'mss': 'Julius E. viii.',
   'ff': 'ff. 12 b-17 b',
   'page': 289},
  {'collection': 'Cotton',
   'mss': 'Vespasian E. iv.',
   'ff': 'ff. 112 b-138 b',
   'page': 278},
  {'collection': 'Cotton',
   'mss': 'Titus A. xix.',
   'ff': 'ff. 63-73 b',
   'page': 290},
  {'collection': 'Harley',
   'mss': 'Harley 655.',
   'ff': 'ff. 200 b-204 b',
   'page': 288}],
 'Prophecies of Merlin Silvester': [{'collection': 'Royal',
   'mss': '13. E. ix.',
   'ff': 'ff. 27',
   'page': 314},
  {'collection': 'Royal',
   'mss': '15. C. xvi.',
   'ff': 'ff. 183 b, 184',
   'page': 313},
  {'collection': 'Cotton',
   'mss': 'Cotton Appendix iv.',
   'ff': 'ff. 102 b',
   'page': 315}],
 'Historia Regum Britannia': [{'collection': 'Royal',
   'mss': '14. C. i.',
   'ff': 'ff. 80-137',
   'page': 238},
  {'collection': 'Royal',
   'mss': '15. C. xvi.',
   'ff': 'ff. 146-183 b',
   'page': 239}],
 'Apollonius of Tyre': [{'collection': 'Royal',
   'mss': '14. C. xi.',
   'ff': 'ff. 80-83 b',
   'page': 170},
  {'collection': 'Royal',
   'mss': '20. C. ii.',
   'ff': 'ff. 210-236',
   'page': 166},
  {'collection': 'Cotton',
   'mss': 'Vespasian A. xiii.',
   'ff': 'ff. 132-147 b',
   'page': 164},
  {'collection': 'Cotton',
   'mss': 'Titus D. iii.',
   'ff': 'ff. 127-137 b',
   'page': 169},
  {'collection': 'Arundel',
   'mss': 'Arundel 123.',
   'ff': 'ff. 33-42 b',
   'page': 164},
  {'collection': 'Arundel',
   'mss': 'Arundel 292.',
   'ff': 'ff. 41-61',
   'page': 163},
  {'collection': 'Sloane',
   'mss': 'Sloane 1619',
   'ff': 'ff. 18-29',
   'page': 161},
  {'collection': 'Sloane', 'mss': 'Sloane 2233', 'ff': None, 'page': 165},
  {'collection': 'Additional',
   'mss': 'Add. 4857.',
   'ff': 'ff. 28-56 b',
   'page': 167},
  {'collection': 'Additional',
   'mss': 'Add. 4864.',
   'ff': 'ff. 88-114 b',
   'page': 168}],
 'Le Chemin de Vaillance': [{'collection': 'Royal',
   'mss': '14. E. ii.',
   'ff': 'ff. 1-293',
   'page': 895}],
 "Livre de l'Ordre de Chevalerie": [{'collection': 'Royal',
   'mss': '14. E. ii.',
   'ff': 'ff. 337-353 b',
   'page': 922}],
 'Saint Graal': [{'collection': 'Royal',
   'mss': '14. E. iii.',
   'ff': 'ff. 3-88 b',
   'page': 341},
  {'collection': 'Royal', 'mss': '19. C. vii.', 'ff': None, 'page': 342},
  {'collection': 'Additional',
   'mss': 'Add. 10,292.',
   'ff': 'ff. 1-76',
   'page': 340}],
 'Lancelot du Lac': [{'collection': 'Royal',
   'mss': '14. E. iii.',
   'ff': 'ff. 89-161 b',
   'page': 354},
  {'collection': 'Royal', 'mss': '19. B. vii.', 'ff': None, 'page': 349},
  {'collection': 'Royal', 'mss': '19. C. viii.', 'ff': None, 'page': 345},
  {'collection': 'Royal', 'mss': '20. B. xix.', 'ff': None, 'page': 349},
  {'collection': 'Royal', 'mss': '20. C. vi.', 'ff': None, 'page': 350},
  {'collection': 'Royal', 'mss': '20. D. iii.', 'ff': None, 'page': 353},
  {'collection': 'Royal', 'mss': '20. D. iv.', 'ff': None, 'page': 351},
  {'collection': 'Harley', 'mss': 'Harley 4419', 'ff': None, 'page': 353},
  {'collection': 'Harley', 'mss': 'Harley 6341', 'ff': None, 'page': 355},
  {'collection': 'Lansdowne', 'mss': 'Lansdowne 757', 'ff': None, 'page': 347},
  {'collection': 'Additional', 'mss': 'Add. 10,293', 'ff': None, 'page': 352},
  {'collection': 'Additional', 'mss': 'Add. 10,294', 'ff': None, 'page': 352},
  {'collection': 'Additional', 'mss': 'Add. 17,443', 'ff': None, 'page': 348}],
 'Perceforest': [{'collection': 'Royal',
   'mss': '15. E. v.',
   'ff': None,
   'page': 377},
  {'collection': 'Royal', 'mss': '19. E. ii.', 'ff': None, 'page': 377},
  {'collection': 'Royal', 'mss': '19. E. iii.', 'ff': None, 'page': 377}],
 'Simon de Pouille': [{'collection': 'Royal',
   'mss': '15. E. vi.',
   'ff': 'ff. 25-42 b',
   'page': 627}],
 'Aspremont': [{'collection': 'Royal',
   'mss': '15. E. vi.',
   'ff': 'ff. 43-69 b',
   'page': 598},
  {'collection': 'Additional',
   'mss': 'Add. 10,508.',
   'ff': 'ff. 1-63 b',
   'page': 602}],
 'Fierabras': [{'collection': 'Royal',
   'mss': '15. E. vi.',
   'ff': 'ff. 70-85 b',
   'page': 615}],
 'Ogier le Danois': [{'collection': 'Royal',
   'mss': '15. E. vi.',
   'ff': 'ff. 86-154 b',
   'page': 604}],
 'Quatre fils Aimon': [{'collection': 'Royal',
   'mss': '15. E. vi.',
   'ff': 'ff. 155-206',
   'page': 622},
  {'collection': 'Royal', 'mss': '16. G. ii.', 'ff': None, 'page': 619},
  {'collection': 'Sloane', 'mss': 'Sloane 960', 'ff': None, 'page': 624}],
 'Pontus and Sidoine': [{'collection': 'Royal',
   'mss': '15. E. vi.',
   'ff': 'ff. 207-226 b',
   'page': 469}],
 'Guy of Warwick and Heraud of Ardennes': [{'collection': 'Royal',
   'mss': '15. E. vi.',
   'ff': 'ff. 227-272',
   'page': 487}],
 'Knight of the Swan': [{'collection': 'Royal',
   'mss': '15. E. vi.',
   'ff': 'ff. 273-292',
   'page': 708},
  {'collection': 'Cotton',
   'mss': 'Caligula A. ii.',
   'ff': 'ff. 125 b-129 b',
   'page': 710}],
 'Iliaca': [{'collection': 'Royal',
   'mss': '16. C. iv. A. B.',
   'ff': None,
   'page': 2},
  {'collection': 'Royal', 'mss': '16. D. iii. A. B.', 'ff': None, 'page': 6},

## aligner 2 tables :index_table + theme table
title | author | theme | cycle | collection | mss | ff | page

In [10]:
import json
import pandas as pd
with open("../results/theme_table_clean.json", 'r', encoding='utf-8')as f:
    theme_table=json.load(f)
print(theme_table.keys())

dict_keys(['Classical Romances', 'British and English Traditions', 'French Traditions', 'Miscellaneous Romance', 'Allegorical and Didactic Romance', 'Appendix'])

In [16]:
theme_table["Classical Romances"]

[{'title': 'Cycle of Troy: Heroica, by Flavius Philostratus', 'page': '1'},
 {'title': 'Cycle of Troy: Iliaca, by Joannes Tzetzes', 'page': '2'},
 {'title': 'Cycle of Troy: Dictys Cretensis', 'page': '9'},
 {'title': 'Cycle of Troy: Dares Phrygius', 'page': '12'},
 {'title': "Cycle of Troy: Latin Poems, by Simon Chèvre d'Or, etc",
  'page': '27'},
 {'title': 'Cycle of Troy: Roman de Troie, by Benoît de Sainte-More',
  'page': '35'},
 {'title': 'Cycle of Troy: Historia Trojana, by Guido delle Colonne',
  'page': '40'},
 {'title': 'Cycle of Troy: Trojumanna Saga', 'page': '62'},
 {'title': 'Cycle of Troy: Rimur af Trojumonnum, by Jon Jonsson',
  'page': '63'},
 {'title': 'Cycle of Troy: Recueil, by Raoul Le Fèvre', 'page': '64'},
 {'title': 'Cycle of Troy: Latin History of Troy', 'page': '66'},
 {'title': 'Cycle of Troy: Filostrato, by Boccaccio', 'page': '67'},
 {'title': 'Cycle of Troy: Troilus and Chryseyde, by Chaucer', 'page': '70'},
 {'title': 'Cycle of Troy: Troy Book, by Lydgate', 'page': '75'},
 {'title': "Cycle of Troy: Roman d'Eneas", 'page': '82'},
 {'title': 'Cycle of Troy: Romance of Troy', 'page': '84'},
 {'title': 'Romance of Thebes, by Lydgate', 'page': '87'},
 {'title': 'Romance of Jason, from Raoul Le Fèvre (Dutch)', 'page': '92'},
 {'title': 'Cycle of Alexander: Alexandreis, by Gaultier de Châtillon',
  'page': '94'},
 {'title': 'Cycle of Alexander: Alexanders Saga, by Brandr Jonsson',
  'page': '104'},
 {'title': 'Cycle of Alexander: Alexander, abridged from Julius Valerius',
  'page': '106'},
 {'title': 'Cycle of Alexander: Alexander, or Historia de Preliis',
  'page': '120'},
 {'title': 'Cycle of Alexander: Marvels of India, etc', 'page': '131'},
 {'title': 'Cycle of Alexander: Treatise on the Brahmins, ascribed to Palladius of Galatia',
  'page': '134'},
 {'title': 'Cycle of Alexander: Letters of Dindimus the Brahmin, etc',
  'page': '136'},
 {'title': 'Cycle of Alexander: Alexandreis, by Ulrich von Eschenbach',
  'page': '141'},
 {'title': "Cycle of Alexander: La Vengeance d'Alexandre", 'page': '143'},
 {'title': 'Cycle of Alexander: Voeux du Paon', 'page': '146'},
 {'title': 'Cycle of Alexander: Florimont, by Aimé de Varennes',
  'page': '156'},
 {'title': 'Apollonius of Tyre', 'page': '161'},
 {'title': 'Sir Orpheo', 'page': '171'},
 {'title': 'Athis et Profilias, by Alexandre de Bernay', 'page': '173'},
 {'title': 'Titus and Vespasian, a chanson de geste', 'page': '176'},
 {'title': 'Titus and Vespasian, an English poem', 'page': '180'},
 {'title': 'Prophecy of the tenth Sibyl', 'page': '190'},
 {'title': 'Life of Virgil, in Icelandic (from the Dutch)', 'page': '196'}]

In [11]:
def extract_cycle(s):
    if "cycle" in s.lower():
        left, right = s.split(":", 1)
        return left.strip(), right.strip()
    return None, s.strip()
    
def extract_author(s):
    if ", by" in s:
        left, right = s.split(", by", 1)
        return left.strip(), right.strip()
    return s.strip(), None

def get_short_title(s):
    if '(' in s:
        s=re.sub(r'\s*\(.*?\)', '', s).strip()
        # re.sub(pattern, replacement, string)
        # 0+ space, (, 1+ letters, )
    if "," in s:
        first, rest=s.split(',',1)
        return first

    return s

# s="Cycle of Arthur: Iwein, by Hartmann von Aue"
# s="Life of Harold, king of England"
s="Ricciardetto, by Niccolo Fortiguerra"

cycle, title_author = extract_cycle(s)
title, author =extract_author(title_author)
short_title=get_short_title(title)
print("cycle:",cycle)
print("title:",title)
print('short title:', short_title)
print("author:",author)

cycle: None
title: Ricciardetto
short title: Ricciardetto
author: Niccolo Fortiguerra

In [ ]:

from rapidfuzz import process, fuzz

def get_mss_info(title_theme, index_table_clean, score_cutoff=70):

    # 1. EXACT match
    if title_theme in index_table_clean:
        title_index=title_theme
        return title_index, index_table_clean[title_theme]
    
    # 2. FUZZY match
    result = process.extractOne(
        title_theme,
        index_table_clean.keys(),
        scorer=fuzz.ratio,
        score_cutoff=score_cutoff
    )
    
    if result:
        best_match, score, _ = result
        title_index=best_match
        # print(f"Fuzzy match: {best_match} (score={score})")
        return title_index, index_table_clean[best_match]
    # print(f"[No match] found for {title}")
    return None, []


title="Roman de la Bose"#"Iliaca"#"Heroica"
title, mss_info=get_mss_info(title, index_table_clean)
print(title,len(mss_info))
for info in mss_info:
    print(info)

Roman de la Rose 12
{'collection': 'Royal', 'mss': '19. A. xviii.', 'ff': None, 'page': 885}
{'collection': 'Royal', 'mss': '19. B. xii.', 'ff': 'ff. 2-147 b', 'page': 888}
{'collection': 'Royal', 'mss': '19. B. xiii.', 'ff': None, 'page': 874}
{'collection': 'Royal', 'mss': '20. A. xvii.', 'ff': None, 'page': 880}
{'collection': 'Royal', 'mss': '20. D. vii.', 'ff': None, 'page': 889}
{'collection': 'Harley', 'mss': 'Harley 4425', 'ff': None, 'page': 892}
{'collection': 'Additional', 'mss': 'Add. 12,042', 'ff': None, 'page': 887}
{'collection': 'Additional', 'mss': 'Add. 16,169.', 'ff': 'ff. 1, 477', 'page': 894}
{'collection': 'Additional', 'mss': 'Add. 31,840', 'ff': None, 'page': 884}
{'collection': 'Egerton', 'mss': 'Egerton 881', 'ff': None, 'page': 879}
{'collection': 'Egerton', 'mss': 'Egerton 1069', 'ff': None, 'page': 890}
{'collection': 'Egerton', 'mss': 'Egerton 2022', 'ff': None, 'page': 891}

In [136]:
## ---match mss info and theme info ---

table_clean=[]
for theme, works in theme_table.items():
    for work in works:
        # ---theme---
        page=work['page'] 
        s=work['title']
        cycle, title_author = extract_cycle(s)
        title_theme, author =extract_author(title_author)
        
        # ---mss---  
        # 高分 exact / near match; 低分 short title match  
        title_index, mss_info=get_mss_info(title_theme, index_table_clean, score_cutoff=80)
        
        if not mss_info:
            short_title_theme=get_short_title(title_theme)
            # print('short title:',short_title)
            title_index, mss_info=get_mss_info(short_title_theme, index_table_clean, score_cutoff=60)

        if not mss_info:
            print(f"[No match] found for {title_theme}")
            data={
                'title_theme':title_theme,
                'title_index':None,
                'author':author,
                'theme':theme,
                'cycle':cycle,
                'collection': None,
                'mss':None,
                'ff': None,
                'page':page
            } 
            table_clean.append(data)
        for info in mss_info:
            data={
                'title_theme':title_theme,
                'title_index':title_index,
                'author':author,
                'theme':theme,
                'cycle':cycle,
                'collection': info.get("collection",None),
                'mss': info.get("mss",None),
                'ff': info.get("ff",None),
                'page':page
            } 
            table_clean.append(data)

[No match] found for Latin Poems
[No match] found for Recueil
[No match] found for Adam Bell, and other Ballads of Forest life
[No match] found for Voyage de Charlemagne
[No match] found for Chevalier au Cygne
[No match] found for Diana
[No match] found for Siege of Milan and Sir Otuel

In [137]:
##----- add no match in index_table in table_clean!----
table_clean_title_index=set([data['title_index'] for data in table_clean])

index_table_nomatch = {
    title_index: data
    for title_index, data in index_table_clean.items()
    if title_index not in table_clean_title_index
}
print(f"no match title index:\n{index_table_nomatch.keys()}\n")

for title_index, infos in index_table_nomatch.items():
    # print(title_index)
    # print(len(infos))
    for info in infos :
        data={
            'title_theme':None,
            'title_index':title_index,
            'author':None,
            'theme':None,
            'cycle':None,
            'collection': info.get('collection',None),
            'mss':info.get('mss',None),
            'ff': info.get('ff',None),
            'page':info.get('page',None),
        } 
        table_clean.append(data)
        
print(len(table_clean))
print(table_clean)
with open("../results/table_clean.json","w", encoding='utf-8')as f:
    json.dump(table_clean, f, indent=2, ensure_ascii=False)

no match title index:
dict_keys(['Historia Regum Britanniae', 'Prophecy of Merlin Silvester', 'Letters between Alexander and Dindimus', 'Prophecies of Merlin', 'Prophecy on Scotland', 'Alexander the Great', 'Prophecy', 'Amya and Amylion', 'Story of Troy', 'Prophecies of Merlin Silvester', 'Guy of Warwick and Heraud of Ardennes', 'Knight of the Swan', 'Voyage of Charlemagne to Jerusalem and Constantinople', 'Recueil des Histoires de Troie', 'Sir Launfal', 'Prophecy of Merlin', 'Prophecies', "Merlin's Prophecy of the Six Kings", "Lisamon's Brut", 'Floyras and Blanchefleur', 'Ipomodon', 'Lanval', 'Fall of Troy', 'Fall of Troy and Adventures of Æneas', 'Two Prophecies', 'Prophecies of Merlin, etc.', 'Whole Prophecy of Scotland', 'Story of Troy and Adventures of Æneas', 'Brut y Brenhinoedd', 'Prophecy of the Lily, the Lion, and the Son of Man', 'Four Prophecies', 'Political Prophecies', 'Six Fabliaux', 'Prophecy of Thomas of Erceldoune', 'Letter of Dindimus to Alexander the Great', "L'Ordène de Chevalerie", 'Richard Cœur-de-Lion', 'Prophecies taken from Geoffrey of Monmouth and others', 'Kings of Britain', 'Abridgement of Historia Trojana', 'Chanson de Roland', "Chanson d'Aspremont", 'Prophecies of Merlin, Gildas, and Thomas of Ercildoune', 'Life of Robin Hood', 'Collection of Prophecies', 'Five Romantic Tales', 'Ívents saga', 'Eight Romantic Tales', 'Parcevals saga and Valvers þáttr', 'Möttuls saga', 'Partalópa saga', 'Seven Romantic Tales', 'Three Romantic Tales', 'Saga of Ajax Frækni', 'Merlínus Spá', 'Juglet', 'Fioccolo', 'Rimur of Remund', 'Collection of Anecdotes', 'Valentine and Orson and Tales', 'Ten Romantic Tales', 'Patient Griselda', 'Argenis', 'Merlinus Spá', 'Brut Gruffydd ap Arthur', 'Extracts from Brut y Brenhinoedd', 'Isarles y Ffynnawn', 'Brut Tyailio', 'Voeux du Paon and Restor du Paon', 'Amis and Amylion', 'May Colvin', 'The King of Tars and the Soudan of Damas', 'Nine Romantic Tales', 'Story of Sigurgaror', 'Fertrams saga', 'The Grene Knight, Turke and Gowin, The Marriage of Sir Gawaine', 'Sir Lambewell', 'Guye and Amarant', 'Three Ballads of Forest Life', 'Guy and Phillis', 'Robin Hood Ballad', 'Libius Disconius', 'Guy and Colebrande', 'Two Ballads relating to Adam Bell', 'A Propecye', "Robin Hood's Garland", 'Ballads of Scotland', 'Two Charlemagne Romances', 'Ipomedon and Prothesilaus'])

583

In [138]:
import pandas as pd
df_table=pd.DataFrame(table_clean)
display(df_table.head())
df_table.to_csv("../results/table_clean.csv", index=False)
print(df_table.shape)

,title_theme,title_index,author,theme,cycle,collection,mss,ff,page
0,Heroica,Heroica,Flavius Philostratus,Classical Romances,Cycle of Troy,Royal,16. C. xxiii.,ff. 2-69 b,1
1,Iliaca,Iliaca,Joannes Tzetzes,Classical Romances,Cycle of Troy,Royal,16. C. iv. A. B.,None,2
2,Iliaca,Iliaca,Joannes Tzetzes,Classical Romances,Cycle of Troy,Royal,16. D. iii. A. B.,None,2
3,Iliaca,Iliaca,Joannes Tzetzes,Classical Romances,Cycle of Troy,Harley,Harley 5662.,ff. 1-56,2
4,Dictys Cretensis,Dictys Cretensis,None,Classical Romances,Cycle of Troy,Harley,Harley 3514,None,9

(583, 9)

In [140]:
df_table[['title_theme','title_index']].isna().value_counts()

title_theme  title_index
False        False          403
True         False          173
False        True             7
Name: count, dtype: int64